# Introduction

<!--- For HTML Only --- Equivalent code for .pdf must be included in preamble.tex -->
`r if (!knitr:::is_latex_output()) '
$\\DeclareMathOperator*{\\argmin}{argmin}$
$\\newcommand{\\var}{\\mathrm{Var}}$
$\\newcommand{\\bfa}[2]{{\\rm\\bf #1}[#2]}$
$\\newcommand{\\rma}[2]{{\\rm     #1}[#2]}$'`

These are notes for the Sampling section of STAT395/455.  The course
overlaps to some extent with STAT392/439, but there is a greater 
emphasis on R coding, computation, summary and display. 

## Lecture Plan

Course Learning Objectives

-	Describe the steps in the survey process, including the sources of survey error;
-	Draw samples from a sample frame under a variety of sample designs, and compute survey weights;
-	Carry out, interpret and present statistical inference procedures on survey data, including adjustments for non-response.

Lecture plan (3 lectures + 1 tutorial per week)

Bring a laptop to the Friday (tutorial) lecture.

### Week 1 – Sampling and The Survey Process {-}

Chapters 1-4

* Sampling
* The survey process, sources of survey error
* Populations and Frames
* Sampling in finite and infinite populations;
  Basics of SRSWOR inference; sample weights;
* **Tutorial:** Sampling basics; Population and Frames

### Week 2 – Sample Designs {-}

*	Simple random sampling, with and without replacement
* Introduction to sample weights
* Probabiiity proportional to size sampling
* Linear Systematic Random Sampling
* Stratified sampling
* One and Two stage cluster sampling
* Sampling in complex designs
* **Tutorial:** using R to draw samples and compute survey weights

### Week 3 - Inference with the R survey package {-}

* Using R to specify sample designs
* Inference in simple and complex designs, including regression
* Definition and interpretation of the design effect
* **Tutorial:** using R to specify designs and draw inferences

### Week 4 – Non-response and complex designs {-}

*	Post-stratification for non-response adjustment
*	Jackknife inference
* Imputation for item non-response
* **Tutorial:** psot-stratification and raking adjustments to weights; imputation; jackknife inference

## Recommended reading

There are lots of books on sample surveys.

 * Thomas Lumley's book 'Complex Surveys' (@Lumley2010) is a good introduction to sample survey analysis with R,
   and accompanies the `survey` package (@survey2004).
 * Groves et al. 'Survey Methodology' (groves.etal) is a good general summary of the important issues in survey design.
 * Sarndal, Swensson and Wretman is a classic in the field of the theory of sampling (@ssw)
 * Likewise the books by @cochran and @kish
 * Little and Rubin have a great book on missing data (@littlerubin)
 * More recent are the books by @lohr and @scheaffer.mendenhall.ott
 * And in 1994 StatsNZ published 'A Guide to Good Survey Design' (@statsnz)
 * Notes from the STAT392 course on Sample Surveys 
   https://homepages.ecs.vuw.ac.nz/~rarnold/STAT392/SampleSurveysBook/_book/index.html
 * A crash guide to using iNZight for sample surveys
   https://homepages.ecs.vuw.ac.nz/~rarnold/STAT392/iNZightManual/_book/index.html
   (iNZight is free software, using the `survey` package in the back end.)

And also
 
 * CRAN site on R resources for Official Statistics https://cran.r-project.org/web/views/OfficialStatistics.html
 * Online book on using R for survey analysis:
   https://bookdown.org/jimr1603/Intermediate_R_-_R_for_Survey_Analysis/
 * This gallery of R graphs https://r-graph-gallery.com/
 
Some simple lectures on Sample Surveys

 * https://r-project.ro/conference2017/presentations/Camelia_Goga_sondages.pdf
 * Notes for epidemiologists: https://www.epirhandbook.com/en/new_pages/survey_analysis.html
 * Notes on imputation: https://www.r-bloggers.com/2023/01/imputation-in-r-top-3-ways-for-imputing-missing-data/
 * An online book about spatial sampling https://dickbrus.github.io/SpatialSamplingwithR/
 * From Qualtrics https://www.qualtrics.com/articles/strategy-research/sampling-methods/

Data

 * UC Irvine Machine Learning data repository: http://archive.ics.uci.edu/
 * Some free microdata sets: https://asdfree.com/
 * Kaggle data repository: https://www.kaggle.com/
   * Airline dataset from Kaggle:
     https://www.kaggle.com/datasets/thedevastator/airlines-traffic-passenger-statistics
     [distributed under the Creative Commons Licence 4.0: https://creativecommons.org/licenses/by-nc-sa/4.0/]
 * Address file from LINZ: https://data.linz.govt.nz/layer/123113-nz-addresses/
 * List of NZ schools https://www.educationcounts.govt.nz/directories/list-of-nz-schools
 * Data on Population, GDP and Military Expenditure from 'Our World in Data' https://ourworldindata.org/
 * And this list of survey data sources with suggestions for analysis https://asdfree.com/
 
## R Packages

* `survey` package (@survey2004) with this handy summary of command uses
   https://stats.oarc.ucla.edu/r/seminars/survey-data-analysis-with-r/
* `srvyr` a dplyr wrapper for the `survey` package and `jtools` which also provides some extensions
* `mice` package for imputation
 
```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'survey', 'srvyr', 'mice'
), 'packages.bib')
```

<!--- For HTML Only --- Equivalent code for .pdf must be included in preamble.tex -->
`r if (!knitr:::is_latex_output()) '
$\\DeclareMathOperator*{\\argmin}{argmin}$
$\\newcommand{\\var}{\\mathrm{Var}}$
$\\newcommand{\\bfa}[2]{{\\rm\\bf #1}[#2]}$
$\\newcommand{\\rma}[2]{{\\rm     #1}[#2]}$'`
