# Designing Surveys

<!--- For HTML Only --- Equivalent code for .pdf must be included in preamble.tex -->
`r if (!knitr:::is_latex_output()) '
$\\DeclareMathOperator*{\\argmin}{argmin}$
$\\newcommand{\\var}{\\mathrm{Var}}$
$\\newcommand{\\bfa}[2]{{\\rm\\bf #1}[#2]}$
$\\newcommand{\\rma}[2]{{\\rm     #1}[#2]}$
$\\newcommand{\\estm}{\\widehat}$'`

The design of surveys is a massive topic, and we can't cover much here.
The key principle is that everything that is done in the design of a survey
should be done to meet the Objectives (the research goals) of the survey. Nothing
else matters.

For our purposes calculation of the sample size required when designing 
a survey is the most significant single decision to make since it determines
the standard errors for the survey estimates.  In real life the decision
about sample size is often severely constrained by available resources.  

## Another interpretation of the Deff

Assume that for sample size $n$ the variance of an estimator 
in a specific design has the approximate formula 
\[
    \bfa{Var}{\widehat{T}_\text{design}} = \frac{c_\text{design}}{n}
\]
then using the definition of the Deff, the ratio of the variance with respect to
SRSWOR, then
\begin{eqnarray}
   \bfa{Deff}{\widehat{T}_{\text{design}}} 
       &=& \frac{\bfa{Var}{\widehat{T}_{\text{design}}}}{\bfa{Var}{\widehat{T}_{\text{SRSWOR}}}}\\
       &=& \frac{c_\text{design}/n}{c_\text{SRSWOR}/n}\\ 
       &=& \frac{c_\text{design}}{c_\text{SRSWOR}}
\end{eqnarray}
So if we want to find the sample sizes at which the variances
in the design of interest and SRSWOR are equal, then we set
\begin{eqnarray}
   V_\text{design} &=& V_\text{SRSWOR}\\
   \frac{c_\text{design}}{n_\text{design}} &=& \frac{c_\text{SRSWOR}}{n_\text{SRSWOR}}\\
   n_\text{design} &=& \frac{c_\text{design}}{c_\text{SRSWOR}}n_\text{SRSWOR}\\
                   &=& \bfa{Deff}{\widehat{T}_\text{design}} n_\text{SRSWOR}
\end{eqnarray}
This means that a rough way to compute the sample size required in a complex design
is to first calculate the sample size we'd need in SRSWOR, and then scale it by
the Deff for the complex design.

If the Deff is 2 (as it may be in a cluster design for example), then we need twice
the sample size an SRSWOR would need in order to achieve the same standard error.

## Computing the Required Sample Size

  1. Identify your **design estimate** -- this is the estimate that will
     underlie a headline you could imagine being written about your survey.

  1. Identify the desired MOE, $m$, for this design estimate, noting whether
     you want this MOE to apply to the overall estimate, or for that estimate in
     each of, say, $H$ subgroups/strata.

  1. Compute the sample size required, $n_1$, assuming that you're going to select a
     Simple Random Sample and ignoring the fpc.  

     For estimation of a mean $\bar{Y}$ of some characteristic $y$:
     \[
      n_1 = \left(\frac{Z}{MOE}\right)^2 s^2
     \]
     where $Z$ is appropriate for the desired level of confidence and $s$ is the
     estimated population standard deviation of the characteristic $y$.

     For estimation of a proportion $P$:
     \[
      n_1 = \left(\frac{Z}{MOE}\right)^2 p(1-p)
     \]
     where $p$ is the estimated proportion, or 0.5 if really unknown.

  1. If the sample size is a substantial proportion of the population or
     subgroup size $N$, then apply the fpc adjustment:
     \[
        n_2 = \frac{n_1}{1+\frac{n_1}{N}}
     \]

  1. If you have $H$ subgroups and are using equal allocation then multiply by $H$
     \[
        n_3 = Hn_2
     \]
     or alternatively sum over the $n_2$ values in each of the strata you've
     defined.

  1. Apply the design effect (Deff) appropriate for the actual design you'll
     be using.
     \[
        n_4 = \text{Deff}\times n_3
     \]

  1. Adjust for anticipated non-response: if response rate $\phi$ is expected
     then 
     \[
        n_5 = \frac{n_4}{\phi}
     \]
     (If non-response is likely to vary between strata, then apply this correction 
     to $n_2$, within each stratum.)
     
