--- 
title: "STAT395: Sampling"
author: "Richard Arnold et al."
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Sampling notes."
output: 
  bookdown::html_document2: default
  bookdown::pdf_book: 
    documentclass: krantz
    latex_engine: xelatex
    keep_tex: true
    includes:
      in_header: preamble.tex
  bookdown::pdf_document2: 
    documentclass: krantz
    latex_engine: xelatex
    keep_tex: true
    includes:
      in_header: preamble.tex
---

<!--- For HTML Only --- Equivalent code for .pdf must be included in preamble.tex -->
`r if (!knitr:::is_latex_output()) '
$\\DeclareMathOperator*{\\argmin}{argmin}$
$\\newcommand{\\var}{\\mathrm{Var}}$
$\\newcommand{\\bfa}[2]{{\\rm\\bf #1}[#2]}$
$\\newcommand{\\rma}[2]{{\\rm     #1}[#2]}$'`

```{r echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.align="center")
```

```{r echo=FALSE, warning=FALSE, error=FALSE}
library(haven)
library(dplyr)
library(tidyr)
library(ggplot2)
library(kableExtra)
library(survey)
library(srvyr)
library(sampling)
library(jtools)
library(mice)
library(scales)
source("utils.R")
```

