```{r}
pop <- read.csv("data/population.csv")
pop <- pop |> filter(Year==2023) |> 
  rename(Country=Entity, Population=all.years) |>
  arrange(Country) 
pop <- pop[!grepl("^OWID_",pop$Code),]
pop <- pop[!grepl("^UN_",pop$Code),]
pop <- pop[pop$Code!="",]
pop$Prob <- pop$Population/sum(pop$Population)
row.names(pop) <- NULL

gdp <- read.csv("data/government-expenditure-vs-gdp.csv")
gdp <- gdp |> filter(Year==2023) |> 
  rename(Country=Entity, Region="World.region.according.to.OWID") |>
  rename(GovtSpend="Government.expenditure") |>
  arrange(Country) 
gdp <- gdp[!grepl("^OWID_",pop$Code),]
gdp <- gdp[!grepl("^UN_",pop$Code),]
gdp <- gdp[gdp$Code!="",]
row.names(gdp) <- NULL

gdp <- merge(gdp,pop)
gdp$Prob <- gdp$Population/sum(gdp$Population)
gdp$GDPPerCapita <- gdp$GDP/gdp$Population

mil <- read.csv("data/military-spending-sipri.csv")
#mil <- read.csv("data/military-expenditure-as-a-share-of-government-spending.csv")
mil <- mil |> filter(Year==2023) |> 
  rename(Country=Entity, Region="World.region.according.to.OWID") |>
  rename(MilSpend=Military.expenditure) |>
  select(-Region) |>
  arrange(Country) 
mil <- mil[!grepl("^OWID_",pop$Code),]
mil <- mil[!grepl("^UN_",pop$Code),]
mil <- mil[pop$Code!="",]
row.names(mil) <- NULL

mil <- merge(gdp,mil)
#write.csv(mil, ,row.names=FALSE)
```

### Demonstration of ps SE improvement

```{r}
set.seed(222)
R <- 100
sim <- t(sapply(1:R, 
              function(i) {
  ss <- apipopc |> 
    select.2sc(n=100, cfraction=0.30, mmin=2, clustervar="dnum") 
  d1 <- svydesign(ids=~dnum+snum, fpc=~bigN1+bigN2, data=ss)  
  d2 <- postStratify(d1, strata=~stype, population=stype.benchmarks)
  e1 <- ff(svymean(~api00, design=d1))
  e2 <- ff(svymean(~api00, design=d2))
  return(c(e1,e2))
}))
```


```{r}
par(mfrow=c(1,2))
hist(sim[,1],main="Simple estimates",xlim=c(0.9,1.1)*range(sim[,c(1,3)]))
abline(v=mean(apipopc$api00),col="red",lwd=2)
hist(sim[,3],main="Postratified estimates",xlim=c(0.9,1.1)*range(sim[,c(1,3)]))
abline(v=mean(apipopc$api00),col="red",lwd=2)
```

```{r}
par(mfrow=c(1,2))
hist(sim[,2],main="SE of Simple estimates",xlim=c(0.8,1.2)*range(sim[,c(2,4)]))
abline(v=sd(sim[,1]),col="red",lwd=2)
hist(sim[,4],main="SE of Postratified estimates",xlim=c(0.8,1.2)*range(sim[,c(2,4)]))
abline(v=sd(sim[,3]),col="red",lwd=2)

```



