<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Sample Designs in R | STAT395: Sampling</title>
  <meta name="description" content="Sampling notes." />
  <meta name="generator" content="bookdown 0.44 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Sample Designs in R | STAT395: Sampling" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Sampling notes." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Sample Designs in R | STAT395: Sampling" />
  
  <meta name="twitter:description" content="Sampling notes." />
  

<meta name="author" content="Richard Arnold et al." />


<meta name="date" content="2026-04-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="sample-designs.html"/>
<link rel="next" href="survey-analysis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">STAT395: Sampling</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#lecture-plan"><i class="fa fa-check"></i><b>1.1</b> Lecture Plan</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#week-1-the-survey-process"><i class="fa fa-check"></i>Week 1 – The Survey Process</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#week-2-sampling"><i class="fa fa-check"></i>Week 2 – Sampling</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#week-3---inference-with-the-r-survey-package"><i class="fa fa-check"></i>Week 3 - Inference with the R survey package</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#week-4-non-response-and-complex-designs"><i class="fa fa-check"></i>Week 4 – Non-response and complex designs</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#assignment-4-10-due-end-of-week-12-covers-material-from-weeks-9-11"><i class="fa fa-check"></i>Assignment 4 (10%) [due end of Week 12: covers material from Weeks 9-11]</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#test-2-30-assessment-period-1.5-hours-closed-book"><i class="fa fa-check"></i>Test 2 (30%) [assessment period] [1.5 hours, closed book]</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#recommended-reading"><i class="fa fa-check"></i><b>1.2</b> Recommended reading</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#r-packages"><i class="fa fa-check"></i><b>1.3</b> R Packages</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>2</b> Sampling</a>
<ul>
<li class="chapter" data-level="2.1" data-path="sampling.html"><a href="sampling.html#random-numbers"><i class="fa fa-check"></i><b>2.1</b> Random numbers</a></li>
<li class="chapter" data-level="2.2" data-path="sampling.html"><a href="sampling.html#sampling-from-categorical-random-variables"><i class="fa fa-check"></i><b>2.2</b> Sampling from categorical random variables</a></li>
<li class="chapter" data-level="2.3" data-path="sampling.html"><a href="sampling.html#sampling-from-discrete-numerical-random-variables"><i class="fa fa-check"></i><b>2.3</b> Sampling from discrete numerical random variables</a></li>
<li class="chapter" data-level="2.4" data-path="sampling.html"><a href="sampling.html#sampling-from-continuous-random-variables"><i class="fa fa-check"></i><b>2.4</b> Sampling from continuous random variables</a></li>
<li class="chapter" data-level="2.5" data-path="sampling.html"><a href="sampling.html#sampling-from-a-finite-collection"><i class="fa fa-check"></i><b>2.5</b> Sampling from a finite collection</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="sampling.html"><a href="sampling.html#sampling-without-replacement"><i class="fa fa-check"></i><b>2.5.1</b> Sampling without replacement</a></li>
<li class="chapter" data-level="2.5.2" data-path="sampling.html"><a href="sampling.html#sampling-with-replacement"><i class="fa fa-check"></i><b>2.5.2</b> Sampling with replacement</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="sample-surveys.html"><a href="sample-surveys.html"><i class="fa fa-check"></i><b>3</b> Sample Surveys</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sample-surveys.html"><a href="sample-surveys.html#the-survey-process"><i class="fa fa-check"></i><b>3.1</b> The Survey Process</a></li>
<li class="chapter" data-level="3.2" data-path="sample-surveys.html"><a href="sample-surveys.html#populations-and-frames"><i class="fa fa-check"></i><b>3.2</b> Populations and Frames</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="sample-surveys.html"><a href="sample-surveys.html#what-is-a-sampling-frame"><i class="fa fa-check"></i><b>3.2.1</b> What is a sampling frame?</a></li>
<li class="chapter" data-level="3.2.2" data-path="sample-surveys.html"><a href="sample-surveys.html#what-is-a-good-sampling-frame"><i class="fa fa-check"></i><b>3.2.2</b> What is a <em>good</em> sampling frame?</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="sample-surveys.html"><a href="sample-surveys.html#approaches-to-sampling"><i class="fa fa-check"></i><b>3.3</b> Approaches to sampling</a></li>
<li class="chapter" data-level="3.4" data-path="sample-surveys.html"><a href="sample-surveys.html#example-datasets"><i class="fa fa-check"></i><b>3.4</b> Example datasets</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="sample-surveys.html"><a href="sample-surveys.html#api"><i class="fa fa-check"></i><b>3.4.1</b> API</a></li>
<li class="chapter" data-level="3.4.2" data-path="sample-surveys.html"><a href="sample-surveys.html#from-the-dplyr-package"><i class="fa fa-check"></i><b>3.4.2</b> From the dplyr package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="statistical-inference.html"><a href="statistical-inference.html"><i class="fa fa-check"></i><b>4</b> Statistical Inference</a>
<ul>
<li class="chapter" data-level="4.1" data-path="statistical-inference.html"><a href="statistical-inference.html#inference-in-infinite-populations"><i class="fa fa-check"></i><b>4.1</b> Inference in infinite populations</a></li>
<li class="chapter" data-level="4.2" data-path="statistical-inference.html"><a href="statistical-inference.html#inference-in-finite-populations"><i class="fa fa-check"></i><b>4.2</b> Inference in finite populations</a></li>
<li class="chapter" data-level="4.3" data-path="statistical-inference.html"><a href="statistical-inference.html#the-survey-inference-process"><i class="fa fa-check"></i><b>4.3</b> The survey inference process</a></li>
<li class="chapter" data-level="4.4" data-path="statistical-inference.html"><a href="statistical-inference.html#example"><i class="fa fa-check"></i><b>4.4</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="sample-designs.html"><a href="sample-designs.html"><i class="fa fa-check"></i><b>5</b> Sample Designs</a>
<ul>
<li class="chapter" data-level="5.1" data-path="sample-designs.html"><a href="sample-designs.html#census"><i class="fa fa-check"></i><b>5.1</b> Census</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations"><i class="fa fa-check"></i>Design considerations</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="sample-designs.html"><a href="sample-designs.html#simple-random-sampling-without-replacement-srswor"><i class="fa fa-check"></i><b>5.2</b> Simple Random Sampling Without Replacement (SRSWOR)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-1"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-1"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="sample-designs.html"><a href="sample-designs.html#simple-random-sampling-with-replacement-srswr"><i class="fa fa-check"></i><b>5.3</b> Simple Random Sampling With Replacement (SRSWR)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-2"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-2"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="sample-designs.html"><a href="sample-designs.html#probability-proportion-to-size-sampling-ppswr"><i class="fa fa-check"></i><b>5.4</b> Probability proportion to size Sampling (PPSWR)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-3"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-3"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="sample-designs.html"><a href="sample-designs.html#linear-systematic-random-sample-lsrs"><i class="fa fa-check"></i><b>5.5</b> Linear Systematic Random Sample (LSRS)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-4"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-4"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="sample-designs.html"><a href="sample-designs.html#stratified-simple-random-sample-stsrs"><i class="fa fa-check"></i><b>5.6</b> Stratified Simple Random Sample (STSRS)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-5"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-5"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="sample-designs.html"><a href="sample-designs.html#one-stage-cluster-sampling-1sc"><i class="fa fa-check"></i><b>5.7</b> One stage cluster sampling (1SC)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-6"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-6"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="sample-designs.html"><a href="sample-designs.html#two-stage-cluster-sampling-2sc"><i class="fa fa-check"></i><b>5.8</b> Two stage cluster sampling (2SC)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-7"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-7"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="sample-designs.html"><a href="sample-designs.html#complex-multistage-designs"><i class="fa fa-check"></i><b>5.9</b> Complex multistage designs</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html"><i class="fa fa-check"></i><b>6</b> Sample Designs in R</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#census-1"><i class="fa fa-check"></i><b>6.1</b> Census</a></li>
<li class="chapter" data-level="6.2" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#simple-random-sample-without-replacement-srswor"><i class="fa fa-check"></i><b>6.2</b> Simple Random Sample WithOut Replacement (SRSWOR)</a></li>
<li class="chapter" data-level="6.3" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#probability-proportional-to-size-with-replacement-ppswr"><i class="fa fa-check"></i><b>6.3</b> Probability Proportional to Size With Replacement (PPSWR)</a></li>
<li class="chapter" data-level="6.4" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#stratified-sample"><i class="fa fa-check"></i><b>6.4</b> Stratified Sample</a></li>
<li class="chapter" data-level="6.5" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#one-stage-cluster-design-1sc"><i class="fa fa-check"></i><b>6.5</b> One stage cluster design (1SC)</a></li>
<li class="chapter" data-level="6.6" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#two-stage-cluster-design-2sc"><i class="fa fa-check"></i><b>6.6</b> Two stage cluster design (2SC)</a></li>
<li class="chapter" data-level="6.7" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#stratified-two-stage-cluster-design"><i class="fa fa-check"></i><b>6.7</b> Stratified two stage cluster design</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="survey-analysis.html"><a href="survey-analysis.html"><i class="fa fa-check"></i><b>7</b> Survey Analysis</a>
<ul>
<li class="chapter" data-level="7.1" data-path="survey-analysis.html"><a href="survey-analysis.html#continous-variables"><i class="fa fa-check"></i><b>7.1</b> Continous variables</a>
<ul>
<li class="chapter" data-level="" data-path="survey-analysis.html"><a href="survey-analysis.html#display"><i class="fa fa-check"></i>Display</a></li>
<li class="chapter" data-level="" data-path="survey-analysis.html"><a href="survey-analysis.html#estimation"><i class="fa fa-check"></i>Estimation</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="survey-analysis.html"><a href="survey-analysis.html#categorical-variables"><i class="fa fa-check"></i><b>7.2</b> Categorical Variables</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="post-stratification.html"><a href="post-stratification.html"><i class="fa fa-check"></i><b>8</b> Post-stratification</a>
<ul>
<li class="chapter" data-level="8.1" data-path="post-stratification.html"><a href="post-stratification.html#replicate-weights"><i class="fa fa-check"></i><b>8.1</b> Replicate weights</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="designing-surveys.html"><a href="designing-surveys.html"><i class="fa fa-check"></i><b>9</b> Designing Surveys</a>
<ul>
<li class="chapter" data-level="9.1" data-path="designing-surveys.html"><a href="designing-surveys.html#another-interpretation-of-the-deff"><i class="fa fa-check"></i><b>9.1</b> Another interpretation of the Deff</a></li>
<li class="chapter" data-level="9.2" data-path="designing-surveys.html"><a href="designing-surveys.html#computing-the-required-sample-size"><i class="fa fa-check"></i><b>9.2</b> Computing the Required Sample Size</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="appendix"><span><b> </b></span></li>
<li class="chapter" data-level="A" data-path="placeholder-appendix.html"><a href="placeholder-appendix.html"><i class="fa fa-check"></i><b>A</b> Placeholder Appendix</a></li>
<li class="divider"></li>
<li>Lecture notes</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STAT395: Sampling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sample-designs-in-r" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">6</span> Sample Designs in R<a href="sample-designs-in-r.html#sample-designs-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!--- For HTML Only --- Equivalent code for .pdf must be included in preamble.tex -->
<p><span class="math inline">\(\DeclareMathOperator*{\argmin}{argmin}\)</span>
<span class="math inline">\(\newcommand{\var}{\mathrm{Var}}\)</span>
<span class="math inline">\(\newcommand{\bfa}[2]{{\rm\bf #1}[#2]}\)</span>
<span class="math inline">\(\newcommand{\rma}[2]{{\rm     #1}[#2]}\)</span>
<span class="math inline">\(\newcommand{\estm}{\widehat}\)</span></p>
<p>The method of anlalysis of survey data depends crucially on its sample
design. Simple methods of analysis which neglect the sample design can
lead to estimates which are severely biased, and standard errors that
are incorrect.</p>
<p>In the this and the following Chapter we’ll use the <code>survey</code> package in R to carry out analyses.
We’ll use the <code>schools</code> data set as our primary example, but also use
data on populations and Gross Domestic Product for each country in 2023
from the ‘Our World in Data’ website.</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="sample-designs-in-r.html#cb148-1" tabindex="-1"></a><span class="co"># Census</span></span>
<span id="cb148-2"><a href="sample-designs-in-r.html#cb148-2" tabindex="-1"></a>schools.census <span class="ot">&lt;-</span> schools <span class="sc">|&gt;</span> <span class="fu">select.srswor</span>(<span class="at">n=</span><span class="fu">nrow</span>(schools))</span>
<span id="cb148-3"><a href="sample-designs-in-r.html#cb148-3" tabindex="-1"></a><span class="co"># SRSWOR</span></span>
<span id="cb148-4"><a href="sample-designs-in-r.html#cb148-4" tabindex="-1"></a>schools.srswor <span class="ot">&lt;-</span> schools <span class="sc">|&gt;</span> <span class="fu">select.srswor</span>(<span class="at">n=</span><span class="dv">20</span>)</span>
<span id="cb148-5"><a href="sample-designs-in-r.html#cb148-5" tabindex="-1"></a><span class="co"># PPSWR</span></span>
<span id="cb148-6"><a href="sample-designs-in-r.html#cb148-6" tabindex="-1"></a>schools.ppswr <span class="ot">&lt;-</span> schools <span class="sc">|&gt;</span> <span class="fu">select.ppswr</span>(<span class="at">n=</span><span class="dv">20</span>, <span class="at">sizevar=</span><span class="st">&quot;Total&quot;</span>)</span>
<span id="cb148-7"><a href="sample-designs-in-r.html#cb148-7" tabindex="-1"></a><span class="co"># STSRS</span></span>
<span id="cb148-8"><a href="sample-designs-in-r.html#cb148-8" tabindex="-1"></a>schools.stsrs <span class="ot">&lt;-</span> schools <span class="sc">|&gt;</span> <span class="fu">select.stsrs</span>(<span class="at">n=</span><span class="dv">60</span>, <span class="at">stratumvar=</span><span class="st">&quot;Education_Region&quot;</span>)</span>
<span id="cb148-9"><a href="sample-designs-in-r.html#cb148-9" tabindex="-1"></a><span class="co"># 1SC</span></span>
<span id="cb148-10"><a href="sample-designs-in-r.html#cb148-10" tabindex="-1"></a>schools<span class="fl">.1</span>sc <span class="ot">&lt;-</span> schools <span class="sc">|&gt;</span> <span class="fu">select.1sc</span>(<span class="at">n=</span><span class="dv">10</span>, <span class="at">clustervar=</span><span class="st">&quot;Territorial_Authority&quot;</span>)</span>
<span id="cb148-11"><a href="sample-designs-in-r.html#cb148-11" tabindex="-1"></a><span class="co"># 2SC</span></span>
<span id="cb148-12"><a href="sample-designs-in-r.html#cb148-12" tabindex="-1"></a>schools<span class="fl">.2</span>sc <span class="ot">&lt;-</span> schools <span class="sc">|&gt;</span> <span class="fu">select.2sc</span>(<span class="at">n=</span><span class="dv">10</span>, <span class="at">cfraction=</span><span class="fl">0.20</span>, <span class="at">mmin=</span><span class="dv">2</span>, </span>
<span id="cb148-13"><a href="sample-designs-in-r.html#cb148-13" tabindex="-1"></a>                                     <span class="at">clustervar=</span><span class="st">&quot;Territorial_Authority&quot;</span>)</span>
<span id="cb148-14"><a href="sample-designs-in-r.html#cb148-14" tabindex="-1"></a><span class="co"># ST2SC</span></span>
<span id="cb148-15"><a href="sample-designs-in-r.html#cb148-15" tabindex="-1"></a>schools.st2sc <span class="ot">&lt;-</span> schools <span class="sc">|&gt;</span> <span class="fu">select.st2sc</span>(<span class="at">n=</span><span class="dv">30</span>, <span class="at">stratumvar=</span><span class="st">&quot;Region&quot;</span>, <span class="at">allocation=</span><span class="st">&quot;proportional&quot;</span>,</span>
<span id="cb148-16"><a href="sample-designs-in-r.html#cb148-16" tabindex="-1"></a>                                <span class="at">cfraction=</span><span class="fl">0.20</span>, <span class="at">clustervar=</span><span class="st">&quot;Territorial_Authority&quot;</span>)</span></code></pre></div>
<p>In order to make estimates from sampled data using the <code>survey</code> package
we need to specify the sample design we’re using.
We’ll do this for the various sample designs covered in the
previous chapter.</p>
<blockquote>
<p>Note that in the <code>survey</code> package we identify variables with their names without
quotes and with a <code>~</code> symbol in front. (If you’re interested you can
use the <code>survyr</code> package which is a <code>dplyr</code>-like wrapper for <code>survey</code>
with functions defined so that the <code>~</code> isn’t necessary.)</p>
</blockquote>
<p>We’ll define each design, and then use it to estimate the mean
size of school rolls in the population (stored in the variable <code>Total</code> in
the <code>schools</code> data frame. (One exception will be the PPSWR example
where we’ll select a sample of countries using their population size
as the size variable.)</p>
<p>The true mean school size is</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="sample-designs-in-r.html#cb149-1" tabindex="-1"></a>ybar <span class="ot">&lt;-</span> <span class="fu">mean</span>(schools<span class="sc">$</span>Total)</span>
<span id="cb149-2"><a href="sample-designs-in-r.html#cb149-2" tabindex="-1"></a>ybar</span></code></pre></div>
<pre><code>## [1] 334.481</code></pre>
<div id="census-1" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Census<a href="sample-designs-in-r.html#census-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The analysis of a census is trivial (at least, if there is no non-response).
We can create a census dataset by taking an SRSWOR of size <span class="math inline">\(n=N\)</span>.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="sample-designs-in-r.html#cb151-1" tabindex="-1"></a>schools.census <span class="ot">&lt;-</span> schools <span class="sc">|&gt;</span> <span class="fu">select.srswor</span>(<span class="at">n=</span><span class="fu">nrow</span>(schools))</span></code></pre></div>
<p>This function adds the column <code>bigN</code> to the dataset, which contains
population size <span class="math inline">\(N\)</span> repeated on every row.</p>
<p>Now we can specify the design.</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="sample-designs-in-r.html#cb152-1" tabindex="-1"></a>schools.census.des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id=</span><span class="sc">~</span><span class="dv">1</span>, <span class="at">data=</span>schools.census, <span class="at">fpc=</span><span class="sc">~</span>bigN)</span></code></pre></div>
<p>Note that we tell R which column contains the population size using the <code>fpc</code> argument.
Our data aren’t clustered, so the <code>id</code> variable (which identifies clusters) is set to 1.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="sample-designs-in-r.html#cb153-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Total, <span class="at">design=</span>schools.census.des, <span class="at">deff=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##         mean     SE DEff
## Total 334.48   0.00  NaN</code></pre>
<p>The estimated mean is 334.48, which is of course
exactly equal to the population mean - and note that the standard error is zero:
censuses have no sampling error. We’ve measured everything there is to measure
so we have no uncertainty.</p>
<p>We’ve requested <code>Deff=TRUE</code>, and have got a Deff value of NaN, which means
not able to be calculated. We’ll discuss what this means later on.</p>
<p>If we had left out the <code>fpc</code> command</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="sample-designs-in-r.html#cb155-1" tabindex="-1"></a>schools.census.des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id=</span><span class="sc">~</span><span class="dv">1</span>, <span class="at">data=</span>schools.census)</span></code></pre></div>
<pre><code>## Warning in svydesign.default(id = ~1, data = schools.census): No weights or
## probabilities supplied, assuming equal probability</code></pre>
<p>we get a warning that we can interpret as R assuming an SRSWR from an infinite population.</p>
<p>The estimated mean is the same, but the standard error are now what’d we’d have learned
from first year statistics.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="sample-designs-in-r.html#cb157-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Total, <span class="at">design=</span>schools.census.des, <span class="at">deff=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##           mean       SE DEff
## Total 334.4810   8.4582  Inf</code></pre>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="sample-designs-in-r.html#cb159-1" tabindex="-1"></a>sy <span class="ot">&lt;-</span> <span class="fu">sd</span>(schools.census<span class="sc">$</span>Total)</span>
<span id="cb159-2"><a href="sample-designs-in-r.html#cb159-2" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(schools.census)</span>
<span id="cb159-3"><a href="sample-designs-in-r.html#cb159-3" tabindex="-1"></a>se <span class="ot">&lt;-</span> sy<span class="sc">/</span><span class="fu">sqrt</span>(n)</span></code></pre></div>
<p>i.e. the standard error is
<span class="math display">\[
   \bfa{SE}{\widehat{\bar{Y}}}
   = \frac{s_y}{\sqrt{n}}
   = \frac{423.162}{\sqrt{2503}} = 8.458
\]</span></p>
<p>Also notice that the <code>Deff</code> value has changed to <code>Inf</code> (meaning infinity) -
again we’ll come back to what this means this shortly.</p>
</div>
<div id="simple-random-sample-without-replacement-srswor" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Simple Random Sample WithOut Replacement (SRSWOR)<a href="sample-designs-in-r.html#simple-random-sample-without-replacement-srswor" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s draw a sample of <span class="math inline">\(n=60\)</span> schools from the population by SRSWOR.</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="sample-designs-in-r.html#cb160-1" tabindex="-1"></a>schools.srswor <span class="ot">&lt;-</span> schools <span class="sc">|&gt;</span> <span class="fu">select.srswor</span>(<span class="at">n=</span><span class="dv">60</span>)</span></code></pre></div>
<p>To specify the design we use the same syntax as above:</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="sample-designs-in-r.html#cb161-1" tabindex="-1"></a>schools.srswor.des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id=</span><span class="sc">~</span><span class="dv">1</span>, <span class="at">data=</span>schools.srswor, <span class="at">fpc=</span><span class="sc">~</span>bigN)</span></code></pre></div>
<p>Estimating the mean school size is also just the same:</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="sample-designs-in-r.html#cb162-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Total, <span class="at">design=</span>schools.srswor.des, <span class="at">deff=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##          mean      SE DEff
## Total 347.367  49.582    1</code></pre>
<p>This is the mean of a genuine sample now, so we have an estimated mean value that
differs from the truth, and the standard error is gauge of its accuracy.</p>
<p>The standard error comes from the finite population corrected formula:</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="sample-designs-in-r.html#cb164-1" tabindex="-1"></a>bigN <span class="ot">&lt;-</span> <span class="fu">first</span>(schools.srswor<span class="sc">$</span>bigN) <span class="co"># take the entry in the first row: they&#39;re all the same</span></span>
<span id="cb164-2"><a href="sample-designs-in-r.html#cb164-2" tabindex="-1"></a>sy <span class="ot">&lt;-</span> <span class="fu">sd</span>(schools.srswor<span class="sc">$</span>Total)</span>
<span id="cb164-3"><a href="sample-designs-in-r.html#cb164-3" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(schools.srswor)</span>
<span id="cb164-4"><a href="sample-designs-in-r.html#cb164-4" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">-</span>n<span class="sc">/</span>bigN)<span class="sc">*</span>sy<span class="sc">/</span><span class="fu">sqrt</span>(n)</span></code></pre></div>
<p><span class="math display">\[
   \bfa{SE}{\widehat{\bar{Y}}}
   = \sqrt{1-\frac{n}{N}}\frac{s_y}{\sqrt{n}}
   = \sqrt{1-\frac{60}{2503}}
     \frac{388.745}{\sqrt{60}} = 49.582
\]</span></p>
<p>Compare this to the simple SE, which is just slightly bigger</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="sample-designs-in-r.html#cb165-1" tabindex="-1"></a>se <span class="ot">&lt;-</span> sy<span class="sc">/</span><span class="fu">sqrt</span>(n)</span></code></pre></div>
<p><span class="math display">\[
   \bfa{SE}{\widehat{\bar{Y}}}
   = \frac{s_y}{\sqrt{n}}
   = \frac{388.745}{\sqrt{60}} = 50.187
\]</span>
This is what we get if we omit the <code>fpc</code></p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="sample-designs-in-r.html#cb166-1" tabindex="-1"></a>schools.srswor.des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id=</span><span class="sc">~</span><span class="dv">1</span>, <span class="at">data=</span>schools.srswor)</span></code></pre></div>
<pre><code>## Warning in svydesign.default(id = ~1, data = schools.srswor): No weights or
## probabilities supplied, assuming equal probability</code></pre>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="sample-designs-in-r.html#cb168-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Total, <span class="at">design=</span>schools.srswor.des, <span class="at">deff=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##          mean      SE DEff
## Total 347.367  50.187  Inf</code></pre>
</div>
<div id="probability-proportional-to-size-with-replacement-ppswr" class="section level2 hasAnchor" number="6.3">
<h2><span class="header-section-number">6.3</span> Probability Proportional to Size With Replacement (PPSWR)<a href="sample-designs-in-r.html#probability-proportional-to-size-with-replacement-ppswr" class="anchor-section" aria-label="Anchor link to header"></a></h2>
We have a dataset from ‘Our World in Data’ giving population sizes,
Gross Domestic Product and military expenditure in 2023 (all in US dollars).
The first 10 rows are below:
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Country
</th>
<th style="text-align:left;">
Code
</th>
<th style="text-align:right;">
GovtSpend
</th>
<th style="text-align:right;">
GDP
</th>
<th style="text-align:left;">
Region
</th>
<th style="text-align:right;">
Population
</th>
<th style="text-align:right;">
GDPPerCapita
</th>
<th style="text-align:right;">
MilSpend
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Albania
</td>
<td style="text-align:left;">
ALB
</td>
<td style="text-align:right;">
1863822443
</td>
<td style="text-align:right;">
1.496298e+10
</td>
<td style="text-align:left;">
Europe
</td>
<td style="text-align:right;">
2811660
</td>
<td style="text-align:right;">
5321.759
</td>
<td style="text-align:right;">
397617600
</td>
</tr>
<tr>
<td style="text-align:left;">
Algeria
</td>
<td style="text-align:left;">
DZA
</td>
<td style="text-align:right;">
44321604142
</td>
<td style="text-align:right;">
2.151440e+11
</td>
<td style="text-align:left;">
Africa
</td>
<td style="text-align:right;">
46164222
</td>
<td style="text-align:right;">
4660.405
</td>
<td style="text-align:right;">
18263968000
</td>
</tr>
<tr>
<td style="text-align:left;">
Angola
</td>
<td style="text-align:left;">
AGO
</td>
<td style="text-align:right;">
15741572839
</td>
<td style="text-align:right;">
1.032363e+11
</td>
<td style="text-align:left;">
Africa
</td>
<td style="text-align:right;">
36749909
</td>
<td style="text-align:right;">
2809.157
</td>
<td style="text-align:right;">
1247846300
</td>
</tr>
<tr>
<td style="text-align:left;">
Argentina
</td>
<td style="text-align:left;">
ARG
</td>
<td style="text-align:right;">
111098899281
</td>
<td style="text-align:right;">
5.916847e+11
</td>
<td style="text-align:left;">
South America
</td>
<td style="text-align:right;">
45538402
</td>
<td style="text-align:right;">
12993.093
</td>
<td style="text-align:right;">
4882353000
</td>
</tr>
<tr>
<td style="text-align:left;">
Armenia
</td>
<td style="text-align:left;">
ARM
</td>
<td style="text-align:right;">
1598415044
</td>
<td style="text-align:right;">
1.540616e+10
</td>
<td style="text-align:left;">
Asia
</td>
<td style="text-align:right;">
2943398
</td>
<td style="text-align:right;">
5234.142
</td>
<td style="text-align:right;">
1326245800
</td>
</tr>
<tr>
<td style="text-align:left;">
Australia
</td>
<td style="text-align:left;">
AUS
</td>
<td style="text-align:right;">
385802798739
</td>
<td style="text-align:right;">
1.649425e+12
</td>
<td style="text-align:left;">
Oceania
</td>
<td style="text-align:right;">
26451126
</td>
<td style="text-align:right;">
62357.456
</td>
<td style="text-align:right;">
32387990000
</td>
</tr>
<tr>
<td style="text-align:left;">
Austria
</td>
<td style="text-align:left;">
AUT
</td>
<td style="text-align:right;">
84758230499
</td>
<td style="text-align:right;">
4.246078e+11
</td>
<td style="text-align:left;">
Europe
</td>
<td style="text-align:right;">
9130434
</td>
<td style="text-align:right;">
46504.669
</td>
<td style="text-align:right;">
4452228000
</td>
</tr>
<tr>
<td style="text-align:left;">
Azerbaijan
</td>
<td style="text-align:left;">
AZE
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:right;">
5.755883e+10
</td>
<td style="text-align:left;">
Asia
</td>
<td style="text-align:right;">
10318209
</td>
<td style="text-align:right;">
5578.374
</td>
<td style="text-align:right;">
3561670700
</td>
</tr>
<tr>
<td style="text-align:left;">
Bahrain
</td>
<td style="text-align:left;">
BHR
</td>
<td style="text-align:right;">
6908975351
</td>
<td style="text-align:right;">
3.996681e+10
</td>
<td style="text-align:left;">
Asia
</td>
<td style="text-align:right;">
1569674
</td>
<td style="text-align:right;">
25461.855
</td>
<td style="text-align:right;">
1622393700
</td>
</tr>
<tr>
<td style="text-align:left;">
Bangladesh
</td>
<td style="text-align:left;">
BGD
</td>
<td style="text-align:right;">
18377804014
</td>
<td style="text-align:right;">
3.232800e+11
</td>
<td style="text-align:left;">
Asia
</td>
<td style="text-align:right;">
171466986
</td>
<td style="text-align:right;">
1885.377
</td>
<td style="text-align:right;">
3782793000
</td>
</tr>
</tbody>
</table>
<p>We can select a PPSWR using population as the size variable</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="sample-designs-in-r.html#cb170-1" tabindex="-1"></a>mil.ppswr <span class="ot">&lt;-</span> mil <span class="sc">|&gt;</span> <span class="fu">select.ppswr</span>(<span class="at">n=</span><span class="dv">30</span>, <span class="at">sizevar=</span><span class="st">&quot;Population&quot;</span>)</span></code></pre></div>
<p>The <code>weight</code> column here combines the weight over the number of times a unit is selected</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="sample-designs-in-r.html#cb171-1" tabindex="-1"></a>mil.ppswr.des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id=</span><span class="sc">~</span><span class="dv">1</span>, <span class="at">data=</span>mil.ppswr, <span class="at">weight=</span><span class="sc">~</span>weight)</span></code></pre></div>
<p>The mean military expenditure per country is</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="sample-designs-in-r.html#cb172-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>MilSpend, <span class="at">design=</span>mil.ppswr.des, <span class="at">deff=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##                mean         SE   DEff
## MilSpend 7.4657e+10 3.4650e+10 1.0362</code></pre>
<p>though more interesting is the <strong>total</strong> of this variable, to see
how much the world is spending.</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="sample-designs-in-r.html#cb174-1" tabindex="-1"></a><span class="fu">svytotal</span>(<span class="sc">~</span>MilSpend, <span class="at">design=</span>mil.ppswr.des, <span class="at">deff=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##               total         SE  DEff
## MilSpend 1.1199e+13 5.3452e+12 1.096</code></pre>
<blockquote>
<p>The estimation of the <strong>total</strong> of a variable is only something
that makes sense in a finite population, and is a type of estimate
that is rarely found anywhere outside sample survey analysis.</p>
<p>It is frequently of interest in Official (i.e. government) statistics
that we want to estimate the total number of people with a certain characteristic,
or the total amount of a commodity being exported, or total export earnings.</p>
</blockquote>
<p>Note again that in a with replacement design we can’t apply the finite
population correction.</p>
</div>
<div id="stratified-sample" class="section level2 hasAnchor" number="6.4">
<h2><span class="header-section-number">6.4</span> Stratified Sample<a href="sample-designs-in-r.html#stratified-sample" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Recall that in this design we specify a set of groups called strata, and
each population unit belongs to one of these strata.</p>
<p>Selecting a sample of <span class="math inline">\(n=60\)</span> schools by equal allocation across the 12
Education Regions:</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="sample-designs-in-r.html#cb176-1" tabindex="-1"></a>schools.stsrs <span class="ot">&lt;-</span> schools <span class="sc">|&gt;</span> <span class="fu">select.stsrs</span>(<span class="at">n=</span><span class="dv">60</span>, <span class="at">stratumvar=</span><span class="st">&quot;Education_Region&quot;</span>)</span></code></pre></div>
<p>Specify this design</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="sample-designs-in-r.html#cb177-1" tabindex="-1"></a>schools.stsrs.des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id=</span><span class="sc">~</span><span class="dv">1</span>, <span class="at">strata=</span><span class="sc">~</span>Education_Region, <span class="at">fpc=</span><span class="sc">~</span>Nh,</span>
<span id="cb177-2"><a href="sample-designs-in-r.html#cb177-2" tabindex="-1"></a>                               <span class="at">data=</span>schools.stsrs,</span>
<span id="cb177-3"><a href="sample-designs-in-r.html#cb177-3" tabindex="-1"></a>                               <span class="at">survey.lonely.psu=</span><span class="st">&quot;remove&quot;</span>)</span></code></pre></div>
<p>Note that we’ve included the option <code>survey.lonely.psu="remove"</code> to mean
that the estimation of standard errors doesn’t fail if a stratum only has a single
PSU.</p>
<p>We can now return to estimating the mean school size</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="sample-designs-in-r.html#cb178-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Total, <span class="at">design=</span>schools.stsrs.des, <span class="at">deff=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##          mean      SE   DEff
## Total 337.235  39.972 0.6816</code></pre>
<p>Now it’s finally time to talk about the <strong>Design Effect</strong>, or the Deff for short.</p>
<p>The Deff of an estimator <span class="math inline">\(\widehat{T}\)</span> of a population characteristic <span class="math inline">\(T\)</span> in
a particular sample design is defined to be
<span class="math display">\[
   \bfa{Deff}{\widehat{T}_{\text{design}}}
   =
   \frac{\bfa{Var}{\widehat{T}_{\text{design}}}}{
         \bfa{Var}{\widehat{T}_{\text{SRSWOR}}}}
   =
   \left(\frac{\bfa{SE}{\widehat{T}_{\text{design}}}}{
               \bfa{SE}{\widehat{T}_{\text{SRSWOR}}}}\right)^2
\]</span>
where both estimators are based on samples of the same size.</p>
<p>It tells us how the standard error differs between our design of
interest and a SRSWOR of the same sample size.</p>
<p>Note that</p>
<ul>
<li>We have a different Deff for every estimate we make from a survey.</li>
<li>A Deff$&lt;$1 means that the Standard Errors are smaller than what
we’d get in SRSWOR. A small Deff indicates a <strong>more efficient</strong> design.</li>
<li>A Deff of 1 means the design is no better than SRSWOR - and of course
(look back above) the Deffs of all estimates in SRSWOR are 1 by definition.</li>
<li>If we’re dealing with a census, then the Standard Error is zero,
and in any case there’s no difference between designs, so the Deff
isn’t defined.</li>
<li><strong>Stratified designs</strong> can achieve Deffs much much less than 1 if their strata
are well defined to be informative about the estimates of interest. e.g.
in business surveys where the strata are defined by business size we
can get very good Deffs.</li>
<li><strong>Cluster designs</strong> often have Deffs greater than 1, which show them to be
significantly less efficient than SRSWOR.</li>
</ul>
<p>The Deff values we get from R are approximations, and aren’t very reliable
when sample sizes are small. But do notice that we have a Deff&lt;1 here
for the stratified sample of <span class="math inline">\(n=60\)</span> units, and the SE is lower than
that achieved in the SRSWOR of <span class="math inline">\(n=60\)</span> units above.</p>
</div>
<div id="one-stage-cluster-design-1sc" class="section level2 hasAnchor" number="6.5">
<h2><span class="header-section-number">6.5</span> One stage cluster design (1SC)<a href="sample-designs-in-r.html#one-stage-cluster-design-1sc" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A one stage cluster design takes <span class="math inline">\(n=10\)</span> Territorial Authority areas (TAs) at random
and selects all schools in each selected TA.</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="sample-designs-in-r.html#cb180-1" tabindex="-1"></a>schools<span class="fl">.1</span>sc <span class="ot">&lt;-</span> schools <span class="sc">|&gt;</span> <span class="fu">select.1sc</span>(<span class="at">n=</span><span class="dv">10</span>, <span class="at">clustervar=</span><span class="st">&quot;Territorial_Authority&quot;</span>)</span></code></pre></div>
<p>We need a column <code>bigN</code> which gives the number of TAs in the population.</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="sample-designs-in-r.html#cb181-1" tabindex="-1"></a>schools<span class="fl">.1</span>sc.des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id=</span><span class="sc">~</span>Territorial_Authority, <span class="at">data=</span>schools<span class="fl">.1</span>sc, </span>
<span id="cb181-2"><a href="sample-designs-in-r.html#cb181-2" tabindex="-1"></a>                             <span class="at">fpc=</span><span class="sc">~</span>bigN)</span></code></pre></div>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="sample-designs-in-r.html#cb182-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Total, <span class="at">design=</span>schools<span class="fl">.1</span>sc.des, <span class="at">deff=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##          mean      SE   DEff
## Total 287.197  43.829 5.7634</code></pre>
<p>The Deff of this one stage cluster sample is bad (much larger than 1) - this is due to
strong differences between TAs in the mean school size. The more the clusters differ from
each other on the characteristic of interest, the worse the Deff gets.</p>
</div>
<div id="two-stage-cluster-design-2sc" class="section level2 hasAnchor" number="6.6">
<h2><span class="header-section-number">6.6</span> Two stage cluster design (2SC)<a href="sample-designs-in-r.html#two-stage-cluster-design-2sc" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A two stage cluster design takes <span class="math inline">\(n=10\)</span> Territorial Authority areas (TAs) at random
and selects 20% of the schools in each selected TA.</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="sample-designs-in-r.html#cb184-1" tabindex="-1"></a>schools<span class="fl">.2</span>sc <span class="ot">&lt;-</span> schools <span class="sc">|&gt;</span> <span class="fu">select.2sc</span>(<span class="at">n=</span><span class="dv">10</span>, <span class="at">cfraction=</span><span class="fl">0.20</span>, <span class="at">mmin=</span><span class="dv">2</span>, </span>
<span id="cb184-2"><a href="sample-designs-in-r.html#cb184-2" tabindex="-1"></a>                                     <span class="at">clustervar=</span><span class="st">&quot;Territorial_Authority&quot;</span>)</span></code></pre></div>
<p>We need a column <code>bigN1</code> which gives the number of TAs in the population, and
<code>bigN2</code> which is the number of schools in each TA. We also need to specify names
of unique identifiers of the first stage units (the PSUs: these are Territorial Authorities)
and the second stage units (the SSUs: these are Schools).</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="sample-designs-in-r.html#cb185-1" tabindex="-1"></a>schools<span class="fl">.2</span>sc.des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id=</span><span class="sc">~</span>Territorial_Authority<span class="sc">+</span>School_Id, <span class="at">data=</span>schools<span class="fl">.2</span>sc, </span>
<span id="cb185-2"><a href="sample-designs-in-r.html#cb185-2" tabindex="-1"></a>                             <span class="at">fpc=</span><span class="sc">~</span>bigN1<span class="sc">+</span>bigN2,</span>
<span id="cb185-3"><a href="sample-designs-in-r.html#cb185-3" tabindex="-1"></a>                             <span class="at">survey.lonely.psu=</span><span class="st">&quot;remove&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="sample-designs-in-r.html#cb186-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Total, <span class="at">design=</span>schools<span class="fl">.2</span>sc.des, <span class="at">deff=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##          mean      SE   DEff
## Total 486.981  84.261 2.1739</code></pre>
</div>
<div id="stratified-two-stage-cluster-design" class="section level2 hasAnchor" number="6.7">
<h2><span class="header-section-number">6.7</span> Stratified two stage cluster design<a href="sample-designs-in-r.html#stratified-two-stage-cluster-design" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Finally here is a stratified two stage sample of schools within TA’s with Regions.
The Regions are strata, the TAs are clusters within the Regions, and then 20% of
schools are sampled in the selected TAs.</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="sample-designs-in-r.html#cb188-1" tabindex="-1"></a>schools.st2sc <span class="ot">&lt;-</span> schools <span class="sc">|&gt;</span> <span class="fu">select.st2sc</span>(<span class="at">n=</span><span class="dv">30</span>, <span class="at">stratumvar=</span><span class="st">&quot;Region&quot;</span>, <span class="at">allocation=</span><span class="st">&quot;proportional&quot;</span>,</span>
<span id="cb188-2"><a href="sample-designs-in-r.html#cb188-2" tabindex="-1"></a>                                         <span class="at">cfraction=</span><span class="fl">0.20</span>, <span class="at">clustervar=</span><span class="st">&quot;Territorial_Authority&quot;</span>)</span></code></pre></div>
<p>The design is the same as the two stage cluster sample, except we add the stratum specification.</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="sample-designs-in-r.html#cb189-1" tabindex="-1"></a>schools.st2sc.des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id=</span><span class="sc">~</span>Territorial_Authority<span class="sc">+</span>School_Id, <span class="at">strata=</span><span class="sc">~</span>Region, <span class="at">data=</span>schools.st2sc, </span>
<span id="cb189-2"><a href="sample-designs-in-r.html#cb189-2" tabindex="-1"></a>                               <span class="at">fpc=</span><span class="sc">~</span>bigN1<span class="sc">+</span>bigN2,</span>
<span id="cb189-3"><a href="sample-designs-in-r.html#cb189-3" tabindex="-1"></a>                               <span class="at">survey.lonely.psu=</span><span class="st">&quot;remove&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="sample-designs-in-r.html#cb190-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Total, <span class="at">design=</span>schools.st2sc.des, <span class="at">deff=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##          mean      SE  DEff
## Total 295.326  25.898 1.248</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sample-designs.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="survey-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf", "_main.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
