<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Statistical Inference | STAT395: Sampling</title>
  <meta name="description" content="Sampling notes." />
  <meta name="generator" content="bookdown 0.44 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Statistical Inference | STAT395: Sampling" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Sampling notes." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Statistical Inference | STAT395: Sampling" />
  
  <meta name="twitter:description" content="Sampling notes." />
  

<meta name="author" content="Richard Arnold et al." />


<meta name="date" content="2026-04-08" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="sample-surveys.html"/>
<link rel="next" href="sample-designs.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">STAT395: Sampling</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introductory Remarks</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#lecture-plan"><i class="fa fa-check"></i><b>1.1</b> Lecture Plan</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#week-1-the-survey-process"><i class="fa fa-check"></i>Week 1 – The Survey Process</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#week-2-sampling"><i class="fa fa-check"></i>Week 2 – Sampling</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#week-3---inference-with-the-r-survey-package"><i class="fa fa-check"></i>Week 3 - Inference with the R survey package</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#week-4-non-response-and-complex-designs"><i class="fa fa-check"></i>Week 4 – Non-response and complex designs</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#assignment-4-10-due-end-of-week-12-covers-material-from-weeks-9-11"><i class="fa fa-check"></i>Assignment 4 (10%) [due end of Week 12: covers material from Weeks 9-11]</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#test-2-30-assessment-period-1.5-hours-closed-book"><i class="fa fa-check"></i>Test 2 (30%) [assessment period] [1.5 hours, closed book]</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#recommended-reading"><i class="fa fa-check"></i><b>1.2</b> Recommended reading</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#r-packages"><i class="fa fa-check"></i><b>1.3</b> R Packages</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>2</b> Sampling</a>
<ul>
<li class="chapter" data-level="2.1" data-path="sampling.html"><a href="sampling.html#random-numbers"><i class="fa fa-check"></i><b>2.1</b> Random numbers</a></li>
<li class="chapter" data-level="2.2" data-path="sampling.html"><a href="sampling.html#sampling-from-categorical-random-variables"><i class="fa fa-check"></i><b>2.2</b> Sampling from categorical random variables</a></li>
<li class="chapter" data-level="2.3" data-path="sampling.html"><a href="sampling.html#sampling-from-discrete-numerical-random-variables"><i class="fa fa-check"></i><b>2.3</b> Sampling from discrete numerical random variables</a></li>
<li class="chapter" data-level="2.4" data-path="sampling.html"><a href="sampling.html#sampling-from-continuous-random-variables"><i class="fa fa-check"></i><b>2.4</b> Sampling from continuous random variables</a></li>
<li class="chapter" data-level="2.5" data-path="sampling.html"><a href="sampling.html#sampling-from-a-finite-collection"><i class="fa fa-check"></i><b>2.5</b> Sampling from a finite collection</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="sampling.html"><a href="sampling.html#sampling-without-replacement"><i class="fa fa-check"></i><b>2.5.1</b> Sampling without replacement</a></li>
<li class="chapter" data-level="2.5.2" data-path="sampling.html"><a href="sampling.html#sampling-with-replacement"><i class="fa fa-check"></i><b>2.5.2</b> Sampling with replacement</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="sample-surveys.html"><a href="sample-surveys.html"><i class="fa fa-check"></i><b>3</b> Sample Surveys</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sample-surveys.html"><a href="sample-surveys.html#the-survey-process"><i class="fa fa-check"></i><b>3.1</b> The Survey Process</a></li>
<li class="chapter" data-level="3.2" data-path="sample-surveys.html"><a href="sample-surveys.html#populations-and-frames"><i class="fa fa-check"></i><b>3.2</b> Populations and Frames</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="sample-surveys.html"><a href="sample-surveys.html#what-is-a-sampling-frame"><i class="fa fa-check"></i><b>3.2.1</b> What is a sampling frame?</a></li>
<li class="chapter" data-level="3.2.2" data-path="sample-surveys.html"><a href="sample-surveys.html#what-is-a-good-sampling-frame"><i class="fa fa-check"></i><b>3.2.2</b> What is a <em>good</em> sampling frame?</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="sample-surveys.html"><a href="sample-surveys.html#approaches-to-sampling"><i class="fa fa-check"></i><b>3.3</b> Approaches to sampling</a></li>
<li class="chapter" data-level="3.4" data-path="sample-surveys.html"><a href="sample-surveys.html#example-datasets"><i class="fa fa-check"></i><b>3.4</b> Example datasets</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="sample-surveys.html"><a href="sample-surveys.html#api"><i class="fa fa-check"></i><b>3.4.1</b> API</a></li>
<li class="chapter" data-level="3.4.2" data-path="sample-surveys.html"><a href="sample-surveys.html#from-the-dplyr-package"><i class="fa fa-check"></i><b>3.4.2</b> From the dplyr package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="statistical-inference.html"><a href="statistical-inference.html"><i class="fa fa-check"></i><b>4</b> Statistical Inference</a></li>
<li class="chapter" data-level="5" data-path="sample-designs.html"><a href="sample-designs.html"><i class="fa fa-check"></i><b>5</b> Sample Designs</a></li>
<li class="chapter" data-level="6" data-path="inference-with-r.html"><a href="inference-with-r.html"><i class="fa fa-check"></i><b>6</b> Inference with R</a></li>
<li class="chapter" data-level="7" data-path="missing-data.html"><a href="missing-data.html"><i class="fa fa-check"></i><b>7</b> Missing data</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="appendix"><span><b> </b></span></li>
<li class="chapter" data-level="A" data-path="computing-the-required-sample-size.html"><a href="computing-the-required-sample-size.html"><i class="fa fa-check"></i><b>A</b> Computing the Required Sample Size</a></li>
<li class="divider"></li>
<li>Lecture notes</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STAT395: Sampling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistical-inference" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Statistical Inference<a href="statistical-inference.html#statistical-inference" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!--- For HTML Only --- Equivalent code for .pdf must be included in preamble.tex -->
<p><span class="math inline">\(\DeclareMathOperator*{\argmin}{argmin}\)</span>
<span class="math inline">\(\newcommand{\var}{\mathrm{Var}}\)</span>
<span class="math inline">\(\newcommand{\bfa}[2]{{\rm\bf #1}[#2]}\)</span>
<span class="math inline">\(\newcommand{\rma}[2]{{\rm     #1}[#2]}\)</span>
<span class="math inline">\(\newcommand{\estm}{\widehat}\)</span></p>
<p>Let’s briefly review a few familiar results from earlier statistics courses.</p>
<p>Most of what we’ve done in earlier courses has assumed that we have
a <strong>simple random sample</strong> from an <strong>infinite</strong> population.</p>
<p>We’ll use data from the <code>starwars</code> dataset (in the <code>dplyr</code> package). There
are data on 87 characters, including their heights in centimetres.<br />
Six heights are missing, but let’s just guess them so we have no missing data
(this process of inventing data has a respectable name: <strong>‘imputation’</strong>,
and we’ll come back to it later).</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="statistical-inference.html#cb108-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb108-2"><a href="statistical-inference.html#cb108-2" tabindex="-1"></a><span class="fu">data</span>(starwars)</span>
<span id="cb108-3"><a href="statistical-inference.html#cb108-3" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(starwars<span class="sc">$</span>height))</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="statistical-inference.html#cb110-1" tabindex="-1"></a>starwars <span class="ot">&lt;-</span> starwars <span class="sc">%&gt;%</span> </span>
<span id="cb110-2"><a href="statistical-inference.html#cb110-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">height=</span><span class="fu">case_when</span>(name<span class="sc">==</span><span class="st">&quot;Arvel Crynyd&quot;</span> <span class="sc">~</span> <span class="dv">172</span>, <span class="co"># same as Luke</span></span>
<span id="cb110-3"><a href="statistical-inference.html#cb110-3" tabindex="-1"></a>                          name<span class="sc">==</span><span class="st">&quot;Finn&quot;</span> <span class="sc">~</span> <span class="dv">172</span>, <span class="co"># same as Luke</span></span>
<span id="cb110-4"><a href="statistical-inference.html#cb110-4" tabindex="-1"></a>                          name<span class="sc">==</span><span class="st">&quot;Rey&quot;</span> <span class="sc">~</span> <span class="dv">150</span>,  <span class="co"># same as Leia</span></span>
<span id="cb110-5"><a href="statistical-inference.html#cb110-5" tabindex="-1"></a>                          name<span class="sc">==</span><span class="st">&quot;Poe Dameron&quot;</span> <span class="sc">~</span> <span class="dv">172</span>, <span class="co"># same as Luke</span></span>
<span id="cb110-6"><a href="statistical-inference.html#cb110-6" tabindex="-1"></a>                          name<span class="sc">==</span><span class="st">&quot;BB8&quot;</span> <span class="sc">~</span> <span class="dv">96</span>, <span class="co"># same as R2D2</span></span>
<span id="cb110-7"><a href="statistical-inference.html#cb110-7" tabindex="-1"></a>                          name<span class="sc">==</span><span class="st">&quot;Captain Phasma&quot;</span> <span class="sc">~</span> <span class="dv">167</span>, <span class="co"># same as C3P0</span></span>
<span id="cb110-8"><a href="statistical-inference.html#cb110-8" tabindex="-1"></a>                          <span class="at">.default=</span>height))</span></code></pre></div>
<p>The mean height <span class="math inline">\(\bar{Y}\)</span> of characters in the Star Wars universe is a <strong>population parameter</strong>.
We can <strong>estimate</strong> it from a sample of characters.</p>
<blockquote>
<p><strong>Note:</strong> we’re using capital letters for <strong>population parameters</strong>
(<span class="math inline">\(\bar{Y}\)</span> is the population mean), and lower case letters for <strong>sample statistics</strong>
(<span class="math inline">\(\bar{y}\)</span> is the sample mean).</p>
<p>It’s also common to see Greek letters for <strong>population parameters</strong> (e.g. <span class="math inline">\(\mu\)</span> for the
population mean), upper case latin letters for random variables, and lower case latin letters
for sample statistics.</p>
</blockquote>
<p>For the purposes of this exercise let’s imagine there are only <span class="math inline">\(N=87\)</span> individuals in the entire
Star Wars universe. Let’s draw a random sample of <span class="math inline">\(n=20\)</span> from this population of <span class="math inline">\(N=87\)</span>:</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="statistical-inference.html#cb111-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">222</span>)</span>
<span id="cb111-2"><a href="statistical-inference.html#cb111-2" tabindex="-1"></a>bigN <span class="ot">&lt;-</span> <span class="fu">nrow</span>(starwars)</span>
<span id="cb111-3"><a href="statistical-inference.html#cb111-3" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb111-4"><a href="statistical-inference.html#cb111-4" tabindex="-1"></a>samplemembers <span class="ot">&lt;-</span> starwars[<span class="fu">sample</span>(bigN, n, <span class="at">replace=</span><span class="cn">FALSE</span>),]</span>
<span id="cb111-5"><a href="statistical-inference.html#cb111-5" tabindex="-1"></a>samplemembers <span class="sc">%&gt;%</span></span>
<span id="cb111-6"><a href="statistical-inference.html#cb111-6" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(name,height,mass,hair_color,homeworld) <span class="sc">%&gt;%</span></span>
<span id="cb111-7"><a href="statistical-inference.html#cb111-7" tabindex="-1"></a>  <span class="fu">kbl</span>() <span class="sc">%&gt;%</span></span>
<span id="cb111-8"><a href="statistical-inference.html#cb111-8" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
name
</th>
<th style="text-align:right;">
height
</th>
<th style="text-align:right;">
mass
</th>
<th style="text-align:left;">
hair_color
</th>
<th style="text-align:left;">
homeworld
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Tarfful
</td>
<td style="text-align:right;">
234
</td>
<td style="text-align:right;">
136
</td>
<td style="text-align:left;">
brown
</td>
<td style="text-align:left;">
Kashyyyk
</td>
</tr>
<tr>
<td style="text-align:left;">
Jek Tono Porkins
</td>
<td style="text-align:right;">
180
</td>
<td style="text-align:right;">
110
</td>
<td style="text-align:left;">
brown
</td>
<td style="text-align:left;">
Bestine IV
</td>
</tr>
<tr>
<td style="text-align:left;">
Bossk
</td>
<td style="text-align:right;">
190
</td>
<td style="text-align:right;">
113
</td>
<td style="text-align:left;">
none
</td>
<td style="text-align:left;">
Trandosha
</td>
</tr>
<tr>
<td style="text-align:left;">
Lando Calrissian
</td>
<td style="text-align:right;">
177
</td>
<td style="text-align:right;">
79
</td>
<td style="text-align:left;">
black
</td>
<td style="text-align:left;">
Socorro
</td>
</tr>
<tr>
<td style="text-align:left;">
IG-88
</td>
<td style="text-align:right;">
200
</td>
<td style="text-align:right;">
140
</td>
<td style="text-align:left;">
none
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Kit Fisto
</td>
<td style="text-align:right;">
196
</td>
<td style="text-align:right;">
87
</td>
<td style="text-align:left;">
none
</td>
<td style="text-align:left;">
Glee Anselm
</td>
</tr>
<tr>
<td style="text-align:left;">
Biggs Darklighter
</td>
<td style="text-align:right;">
183
</td>
<td style="text-align:right;">
84
</td>
<td style="text-align:left;">
black
</td>
<td style="text-align:left;">
Tatooine
</td>
</tr>
<tr>
<td style="text-align:left;">
Obi-Wan Kenobi
</td>
<td style="text-align:right;">
182
</td>
<td style="text-align:right;">
77
</td>
<td style="text-align:left;">
auburn, white
</td>
<td style="text-align:left;">
Stewjon
</td>
</tr>
<tr>
<td style="text-align:left;">
Quarsh Panaka
</td>
<td style="text-align:right;">
183
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:left;">
black
</td>
<td style="text-align:left;">
Naboo
</td>
</tr>
<tr>
<td style="text-align:left;">
Mace Windu
</td>
<td style="text-align:right;">
188
</td>
<td style="text-align:right;">
84
</td>
<td style="text-align:left;">
none
</td>
<td style="text-align:left;">
Haruun Kal
</td>
</tr>
<tr>
<td style="text-align:left;">
Ratts Tyerel
</td>
<td style="text-align:right;">
79
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:left;">
none
</td>
<td style="text-align:left;">
Aleen Minor
</td>
</tr>
<tr>
<td style="text-align:left;">
Beru Whitesun Lars
</td>
<td style="text-align:right;">
165
</td>
<td style="text-align:right;">
75
</td>
<td style="text-align:left;">
brown
</td>
<td style="text-align:left;">
Tatooine
</td>
</tr>
<tr>
<td style="text-align:left;">
Chewbacca
</td>
<td style="text-align:right;">
228
</td>
<td style="text-align:right;">
112
</td>
<td style="text-align:left;">
brown
</td>
<td style="text-align:left;">
Kashyyyk
</td>
</tr>
<tr>
<td style="text-align:left;">
Jabba Desilijic Tiure
</td>
<td style="text-align:right;">
175
</td>
<td style="text-align:right;">
1358
</td>
<td style="text-align:left;">
NA
</td>
<td style="text-align:left;">
Nal Hutta
</td>
</tr>
<tr>
<td style="text-align:left;">
Rugor Nass
</td>
<td style="text-align:right;">
206
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:left;">
none
</td>
<td style="text-align:left;">
Naboo
</td>
</tr>
<tr>
<td style="text-align:left;">
Sly Moore
</td>
<td style="text-align:right;">
178
</td>
<td style="text-align:right;">
48
</td>
<td style="text-align:left;">
none
</td>
<td style="text-align:left;">
Umbara
</td>
</tr>
<tr>
<td style="text-align:left;">
Dormé
</td>
<td style="text-align:right;">
165
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:left;">
brown
</td>
<td style="text-align:left;">
Naboo
</td>
</tr>
<tr>
<td style="text-align:left;">
Leia Organa
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
49
</td>
<td style="text-align:left;">
brown
</td>
<td style="text-align:left;">
Alderaan
</td>
</tr>
<tr>
<td style="text-align:left;">
Finn
</td>
<td style="text-align:right;">
172
</td>
<td style="text-align:right;">
NA
</td>
<td style="text-align:left;">
black
</td>
<td style="text-align:left;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Darth Maul
</td>
<td style="text-align:right;">
175
</td>
<td style="text-align:right;">
80
</td>
<td style="text-align:left;">
none
</td>
<td style="text-align:left;">
Dathomir
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="statistical-inference.html#cb112-1" tabindex="-1"></a><span class="fu">hist</span>(samplemembers<span class="sc">$</span>height, <span class="at">xlab=</span><span class="st">&quot;Height (cm)&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Frequency&quot;</span>, </span>
<span id="cb112-2"><a href="statistical-inference.html#cb112-2" tabindex="-1"></a>     <span class="at">breaks=</span><span class="dv">15</span>, <span class="at">main=</span><span class="st">&quot;Heights of Star Wars characters&quot;</span>)</span>
<span id="cb112-3"><a href="statistical-inference.html#cb112-3" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(samplemembers<span class="sc">$</span>height),<span class="at">col=</span><span class="st">&quot;red&quot;</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:starwarssample"></span>
<img src="_main_files/figure-html/starwarssample-1.png" alt="Histogram of heights of a sample of Star Wars characters (vertical line at the sample mean)" width="480" />
<p class="caption">
Figure 4.1: Histogram of heights of a sample of Star Wars characters (vertical line at the sample mean)
</p>
</div>
<p>Compute the sample mean <span class="math inline">\(\bar{y}\)</span> and standard deviation <span class="math inline">\(s_y\)</span>:</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="statistical-inference.html#cb113-1" tabindex="-1"></a>ybar <span class="ot">&lt;-</span> <span class="fu">mean</span>(samplemembers<span class="sc">$</span>height)</span>
<span id="cb113-2"><a href="statistical-inference.html#cb113-2" tabindex="-1"></a>ybar</span></code></pre></div>
<pre><code>## [1] 180.3</code></pre>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="statistical-inference.html#cb115-1" tabindex="-1"></a>sdy <span class="ot">&lt;-</span> <span class="fu">sd</span>(samplemembers<span class="sc">$</span>height)</span>
<span id="cb115-2"><a href="statistical-inference.html#cb115-2" tabindex="-1"></a>sdy</span></code></pre></div>
<pre><code>## [1] 31.13147</code></pre>
<p>We know how to make a point estimate <span class="math inline">\(\widehat{\bar{Y}}\)</span> for the population
mean <span class="math inline">\(\bar{Y}\)</span> (remember that a hat <span class="math inline">\(\widehat{.}\)</span> over a symbol indicates
an estimate of that parameter): the population mean is estimated by the sample
mean <span class="math inline">\(\bar{y}\)</span>:
<span class="math display">\[
    \widehat{\bar{Y}} = \bar{y} = 180.3
\]</span>
and a 95% confidence interval is given by
<span class="math display">\[\begin{eqnarray}
    \widehat{\bar{Y}} \pm \bfa{MOE}{\widehat{\bar{Y}}}
    &amp;=&amp; \widehat{\bar{Y}} \pm T^\ast_{n-1}\times \bfa{SE}{\widehat{\bar{Y}}}\\
    &amp;=&amp;  \bar{y} \pm T^\ast_{n-1}\times\frac{s_y}{\sqrt{n}}\\
    &amp;=&amp;
    180.3 \pm 2.09 \times \frac{31.1}{\sqrt{20}}\\
    &amp;=&amp;
    180.3 \pm 2.09 \times 6.96\\
    &amp;=&amp;
    180.3 \pm 14.6\\
    &amp;=&amp;
    (165.7,194.9)
\end{eqnarray}\]</span></p>
<p>Here:</p>
<ul>
<li><span class="math inline">\(\bfa{SE}{\widehat{\bar{Y}}}\)</span> is the <strong>standard error</strong> or <strong>sampling error</strong> of the
estimator <span class="math inline">\(\widehat{\bar{Y}}\)</span> of the population mean <span class="math inline">\(\bar{Y}\)</span>;</li>
<li><span class="math inline">\(T^\ast_{n-1}\)</span> is the quantile of the <span class="math inline">\(t-\)</span>distribution with <span class="math inline">\(n-1\)</span> degrees of
freedom so that the interval <span class="math inline">\([-T^\ast_{n-1},+T^\ast_{n-1}]\)</span> encloses 95% of the probability
of the <span class="math inline">\(t-\)</span>distribution;</li>
<li><span class="math inline">\(\bfa{MOE}{\widehat{\bar{Y}}}\)</span> is the <strong>margin of error</strong>, the half-width of the confidence interval,
and is the standard error scaled by <span class="math inline">\(T^\ast_{n-1}\)</span>.</li>
</ul>
<p>This is what is known as a <strong>model based</strong> estimate, the statistical model being
<span class="math display" id="eq:simplelinearmodel">\[\begin{equation}
   y_i = \mu + \varepsilon_i \qquad \text{where $\varepsilon_i\overset{\rm iid}{\sim} N(0,\sigma^2)$}
   \tag{4.1}
\end{equation}\]</span>
There are just two parameters here: the population mean <span class="math inline">\(\mu\)</span>, and the population
standard deviation <span class="math inline">\(\sigma\)</span>.</p>
<p>We can fit this simplest of all linear regression models using the <code>lm()</code> function and
get the same results:</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="statistical-inference.html#cb117-1" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(height <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data=</span>samplemembers)</span>
<span id="cb117-2"><a href="statistical-inference.html#cb117-2" tabindex="-1"></a><span class="fu">summary</span>(lm1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = height ~ 1, data = samplemembers)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -101.30   -6.05    0.70   11.20   53.70 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  180.300      6.961    25.9 2.77e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 31.13 on 19 degrees of freedom</code></pre>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="statistical-inference.html#cb119-1" tabindex="-1"></a><span class="fu">confint</span>(lm1)</span></code></pre></div>
<pre><code>##              2.5 % 97.5 %
## (Intercept) 165.73 194.87</code></pre>
<p>Here <code>(Intercept)</code> is the estimate for <span class="math inline">\(\mu\)</span>, the population mean.<br />
The ‘residual standard error’ in the R output is actually what we’d rather
call <span class="math inline">\(\widehat{\sigma}\)</span>, our estimate of the standard deivation <span class="math inline">\(\sigma\)</span>.</p>
<p>The confidence interval is only valid if the model in equation <a href="statistical-inference.html#eq:simplelinearmodel">(4.1)</a>
holds: i.e. if the data are normally distributed about the mean. The histogram
in Figure <a href="statistical-inference.html#fig:starwarssample">4.1</a> suggests that this is not the case however, since
there is a clear outlier at low height.</p>
<blockquote>
<p>The Central Limit Theorem (CLT) tells us that if <span class="math inline">\(n\)</span> is large enough then our
estimate for <span class="math inline">\(\mu\)</span> is useable, and its confidence interval realistic, even
if the model in equation <a href="statistical-inference.html#eq:simplelinearmodel">(4.1)</a> doesn’t actually hold.</p>
<p>The CLT enables a lot of statistics to yield meaningful results even
without our knowing the true data generation model.</p>
<p>In this course most of the examples will have sample sizes large enough
that the CLT will mean our results are valid.</p>
</blockquote>
<p>The standard error of an estimate is the variability
of estimates between different samples: in fact it is defined as the standard deviation
of all possible estimates from all possible estimates drawn using the
same sample design.</p>
<p>In an infinite population there are an infinite number of possible samples.</p>
<p>However in a finite population that isn’t the case. In a population of size <span class="math inline">\(N\)</span>
if we draw a simple random sample without replacement of size <span class="math inline">\(n\)</span> there are
<span class="math display">\[\begin{eqnarray}
    \binom{N}{n} &amp;=&amp; {}^NC_n\\
                 &amp;=&amp; \frac{N!}{n! (N-n)!}\\
                 &amp;=&amp; \frac{N\times (N-1)\times (N-2)\times ... \times (N-n+1)}{
                           n\times (n-1)\times (n-2)\times ... \times 1}
\end{eqnarray}\]</span>
possible samples: i.e. the number of ways it is possible to draw <span class="math inline">\(n\)</span> objects
from a collection of <span class="math inline">\(N\)</span> without regard to the order they are selected.</p>
<p>In our example of selecting <span class="math inline">\(n=20\)</span> from <span class="math inline">\(N=87\)</span> there are an astronomical
number of possible samples:
<span class="math display">\[
   \binom{87}{20} = \frac{87!}{20!67!} = 2.38\times 10^{19}
\]</span>
There is of course only one way to select a census though:
<span class="math display">\[  
   \binom{87}{87} = \frac{87!}{87!0!} = 1
\]</span>
(using the at first face slightly annoying definition 0!=1). Since there’s only
one possible sample when we’re drawing a census the variation among sample estimates
from different samples is zero: i.e. the standard error is zero.</p>
<p>It’s also true that if <span class="math inline">\(n\)</span> is close to <span class="math inline">\(N\)</span> then sample estimates hardly differ from
one another.</p>
<p>We clearly need a modification of our standard error formula
<span class="math display">\[
   \bfa{SE}{\widehat{\bar{Y}}} = \frac{s_y}{\sqrt{n}}
   \qquad \text{(Infinite population)}
\]</span>
to allow for sample sizes <span class="math inline">\(n\)</span> being close to the population size.</p>
<p>That modification is the <strong>finite population correction (fpc)</strong>:
<span class="math display">\[
   \bfa{SE}{\widehat{\bar{Y}}} = \sqrt{1-\frac{n}{N}}\times\frac{s_y}{\sqrt{n}}
   \qquad \text{(Finite population)}
\]</span>
The factor <span class="math inline">\(\sqrt{1-n/N}\)</span> squashes the standard error to zero in the case that <span class="math inline">\(n=N\)</span>,
but for very small <span class="math inline">\(n\)</span> has a value close to 1, and makes no difference at all.</p>
<p>In our example we had a standard error of
<span class="math display">\[\begin{eqnarray}
  \bfa{SE}{\widehat{\bar{Y}}} &amp;=&amp; \frac{s_y}{\sqrt{n}}\\
                              &amp;=&amp; \frac{31.1}{\sqrt{20}}\\
                              &amp;=&amp; 6.96
\end{eqnarray}\]</span>
If we incorporate the fpc this becomes
<span class="math display">\[\begin{eqnarray}
  \bfa{SE}{\widehat{\bar{Y}}} &amp;=&amp; \sqrt{1-\frac{n}{N}}\times\frac{s_y}{\sqrt{n}}\\
                              &amp;=&amp; \sqrt{1-\frac{20}{87}}\frac{31.1}{\sqrt{20}}\\
                              &amp;=&amp; 0.8776 \times \frac{31.1}{\sqrt{20}}\\
                              &amp;=&amp; 6.11
\end{eqnarray}\]</span>
This narrows the confidence interval for the estimate of the population mean height
from (165.7,194.9)
to (167.5,193.1).</p>
<p>This is a <strong>design based</strong> confidence interval, in which it is the sample design
which foremost in our derivation of standard errors.</p>
<p>There is quite a lot of theory behind derivation of standard errors in the complex
designs which arise in sample surveys.</p>
<p>The <code>survey</code> package in R implements the consequences of sample designs which will
mean we can use the theory without having to derive it.</p>
<p>For example here’s a call to some <code>survey</code> package functions which
gives us the effect of the fpc in our example:</p>
<pre><code>##         mean     SE
## height 180.3 6.1089</code></pre>
<pre><code>##           2.5 %   97.5 %
## height 168.3268 192.2732</code></pre>
<p>If you’re interested in the theory take a look at a text like <span class="citation">Särndal, Swensson, and Wretmann (<a href="#ref-ssw">1992</a>)</span>.</p>

</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-ssw" class="csl-entry">
Särndal, C-E., B. Swensson, and J. Wretmann. 1992. <em>Model Assisted Survey Sampling</em>. New York: Springer-Verlag.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sample-surveys.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sample-designs.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf", "_main.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
