<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Survey Analysis | STAT395: Sampling</title>
  <meta name="description" content="Sampling notes." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Survey Analysis | STAT395: Sampling" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Sampling notes." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Survey Analysis | STAT395: Sampling" />
  
  <meta name="twitter:description" content="Sampling notes." />
  

<meta name="author" content="Richard Arnold et al." />


<meta name="date" content="2026-05-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="sample-designs-in-r.html"/>
<link rel="next" href="weight-adjustments.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">STAT395: Sampling</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#lecture-plan"><i class="fa fa-check"></i><b>1.1</b> Lecture Plan</a>
<ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#week-1-sampling-and-the-survey-process"><i class="fa fa-check"></i>Week 1 – Sampling and The Survey Process</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#week-2-sample-designs"><i class="fa fa-check"></i>Week 2 – Sample Designs</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#week-3---inference-with-the-r-survey-package"><i class="fa fa-check"></i>Week 3 - Inference with the R survey package</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#week-4-non-response-and-complex-designs"><i class="fa fa-check"></i>Week 4 – Non-response and complex designs</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#recommended-reading"><i class="fa fa-check"></i><b>1.2</b> Recommended reading</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#r-packages"><i class="fa fa-check"></i><b>1.3</b> R Packages</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>2</b> Sampling</a>
<ul>
<li class="chapter" data-level="2.1" data-path="sampling.html"><a href="sampling.html#random-numbers"><i class="fa fa-check"></i><b>2.1</b> Random numbers</a></li>
<li class="chapter" data-level="2.2" data-path="sampling.html"><a href="sampling.html#sampling-from-categorical-random-variables"><i class="fa fa-check"></i><b>2.2</b> Sampling from categorical random variables</a></li>
<li class="chapter" data-level="2.3" data-path="sampling.html"><a href="sampling.html#sampling-from-discrete-numerical-random-variables"><i class="fa fa-check"></i><b>2.3</b> Sampling from discrete numerical random variables</a></li>
<li class="chapter" data-level="2.4" data-path="sampling.html"><a href="sampling.html#sampling-from-continuous-random-variables"><i class="fa fa-check"></i><b>2.4</b> Sampling from continuous random variables</a></li>
<li class="chapter" data-level="2.5" data-path="sampling.html"><a href="sampling.html#sampling-from-a-finite-collection"><i class="fa fa-check"></i><b>2.5</b> Sampling from a finite collection</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="sampling.html"><a href="sampling.html#sampling-without-replacement"><i class="fa fa-check"></i><b>2.5.1</b> Sampling without replacement</a></li>
<li class="chapter" data-level="2.5.2" data-path="sampling.html"><a href="sampling.html#sampling-with-replacement"><i class="fa fa-check"></i><b>2.5.2</b> Sampling with replacement</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="sample-surveys.html"><a href="sample-surveys.html"><i class="fa fa-check"></i><b>3</b> Sample Surveys</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sample-surveys.html"><a href="sample-surveys.html#the-survey-process"><i class="fa fa-check"></i><b>3.1</b> The Survey Process</a></li>
<li class="chapter" data-level="3.2" data-path="sample-surveys.html"><a href="sample-surveys.html#populations-and-frames"><i class="fa fa-check"></i><b>3.2</b> Populations and Frames</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="sample-surveys.html"><a href="sample-surveys.html#what-is-a-sampling-frame"><i class="fa fa-check"></i><b>3.2.1</b> What is a sampling frame?</a></li>
<li class="chapter" data-level="3.2.2" data-path="sample-surveys.html"><a href="sample-surveys.html#what-is-a-good-sampling-frame"><i class="fa fa-check"></i><b>3.2.2</b> What is a <em>good</em> sampling frame?</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="sample-surveys.html"><a href="sample-surveys.html#approaches-to-sampling"><i class="fa fa-check"></i><b>3.3</b> Approaches to sampling</a></li>
<li class="chapter" data-level="3.4" data-path="sample-surveys.html"><a href="sample-surveys.html#example-datasets"><i class="fa fa-check"></i><b>3.4</b> Example datasets</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="sample-surveys.html"><a href="sample-surveys.html#api"><i class="fa fa-check"></i><b>3.4.1</b> API</a></li>
<li class="chapter" data-level="3.4.2" data-path="sample-surveys.html"><a href="sample-surveys.html#from-the-dplyr-package"><i class="fa fa-check"></i><b>3.4.2</b> From the dplyr package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="statistical-inference.html"><a href="statistical-inference.html"><i class="fa fa-check"></i><b>4</b> Statistical Inference</a>
<ul>
<li class="chapter" data-level="4.1" data-path="statistical-inference.html"><a href="statistical-inference.html#inference-in-infinite-populations"><i class="fa fa-check"></i><b>4.1</b> Inference in infinite populations</a></li>
<li class="chapter" data-level="4.2" data-path="statistical-inference.html"><a href="statistical-inference.html#inference-in-finite-populations"><i class="fa fa-check"></i><b>4.2</b> Inference in finite populations</a></li>
<li class="chapter" data-level="4.3" data-path="statistical-inference.html"><a href="statistical-inference.html#the-survey-inference-process"><i class="fa fa-check"></i><b>4.3</b> The survey inference process</a></li>
<li class="chapter" data-level="4.4" data-path="statistical-inference.html"><a href="statistical-inference.html#example"><i class="fa fa-check"></i><b>4.4</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="sample-designs.html"><a href="sample-designs.html"><i class="fa fa-check"></i><b>5</b> Sample Designs</a>
<ul>
<li class="chapter" data-level="5.1" data-path="sample-designs.html"><a href="sample-designs.html#census"><i class="fa fa-check"></i><b>5.1</b> Census</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations"><i class="fa fa-check"></i>Design considerations</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="sample-designs.html"><a href="sample-designs.html#simple-random-sampling-without-replacement-srswor"><i class="fa fa-check"></i><b>5.2</b> Simple Random Sampling Without Replacement (SRSWOR)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-1"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-1"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="sample-designs.html"><a href="sample-designs.html#simple-random-sampling-with-replacement-srswr"><i class="fa fa-check"></i><b>5.3</b> Simple Random Sampling With Replacement (SRSWR)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-2"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-2"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="sample-designs.html"><a href="sample-designs.html#probability-proportion-to-size-sampling-ppswr"><i class="fa fa-check"></i><b>5.4</b> Probability proportion to size Sampling (PPSWR)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-3"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-3"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="sample-designs.html"><a href="sample-designs.html#linear-systematic-random-sample-lsrs"><i class="fa fa-check"></i><b>5.5</b> Linear Systematic Random Sample (LSRS)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-4"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-4"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="sample-designs.html"><a href="sample-designs.html#stratified-simple-random-sample-stsrs"><i class="fa fa-check"></i><b>5.6</b> Stratified Simple Random Sample (STSRS)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-5"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-5"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="sample-designs.html"><a href="sample-designs.html#one-stage-cluster-sampling-1sc"><i class="fa fa-check"></i><b>5.7</b> One stage cluster sampling (1SC)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-6"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-6"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="sample-designs.html"><a href="sample-designs.html#two-stage-cluster-sampling-2sc"><i class="fa fa-check"></i><b>5.8</b> Two stage cluster sampling (2SC)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-7"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-7"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="sample-designs.html"><a href="sample-designs.html#complex-multistage-designs"><i class="fa fa-check"></i><b>5.9</b> Complex multistage designs</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html"><i class="fa fa-check"></i><b>6</b> Sample Designs in R</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#census-1"><i class="fa fa-check"></i><b>6.1</b> Census</a></li>
<li class="chapter" data-level="6.2" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#simple-random-sample-without-replacement-srswor"><i class="fa fa-check"></i><b>6.2</b> Simple Random Sample WithOut Replacement (SRSWOR)</a></li>
<li class="chapter" data-level="6.3" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#probability-proportional-to-size-with-replacement-ppswr"><i class="fa fa-check"></i><b>6.3</b> Probability Proportional to Size With Replacement (PPSWR)</a></li>
<li class="chapter" data-level="6.4" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#stratified-sample"><i class="fa fa-check"></i><b>6.4</b> Stratified Sample</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#design-effect"><i class="fa fa-check"></i><b>6.4.1</b> Design Effect</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#one-stage-cluster-design-1sc"><i class="fa fa-check"></i><b>6.5</b> One stage cluster design (1SC)</a></li>
<li class="chapter" data-level="6.6" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#two-stage-cluster-design-2sc"><i class="fa fa-check"></i><b>6.6</b> Two stage cluster design (2SC)</a></li>
<li class="chapter" data-level="6.7" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#stratified-two-stage-cluster-design"><i class="fa fa-check"></i><b>6.7</b> Stratified two stage cluster design</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="survey-analysis.html"><a href="survey-analysis.html"><i class="fa fa-check"></i><b>7</b> Survey Analysis</a>
<ul>
<li class="chapter" data-level="7.1" data-path="survey-analysis.html"><a href="survey-analysis.html#continous-variables"><i class="fa fa-check"></i><b>7.1</b> Continous variables</a>
<ul>
<li class="chapter" data-level="" data-path="survey-analysis.html"><a href="survey-analysis.html#display"><i class="fa fa-check"></i>Display</a></li>
<li class="chapter" data-level="" data-path="survey-analysis.html"><a href="survey-analysis.html#estimation"><i class="fa fa-check"></i>Estimation</a></li>
<li class="chapter" data-level="7.1.1" data-path="survey-analysis.html"><a href="survey-analysis.html#relative-sampling-errors-rses"><i class="fa fa-check"></i><b>7.1.1</b> Relative Sampling Errors (RSEs)</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="survey-analysis.html"><a href="survey-analysis.html#categorical-variables"><i class="fa fa-check"></i><b>7.2</b> Categorical Variables</a></li>
<li class="chapter" data-level="7.3" data-path="survey-analysis.html"><a href="survey-analysis.html#ratio-estimation"><i class="fa fa-check"></i><b>7.3</b> Ratio estimation</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="weight-adjustments.html"><a href="weight-adjustments.html"><i class="fa fa-check"></i><b>8</b> Weight adjustments</a>
<ul>
<li class="chapter" data-level="8.1" data-path="weight-adjustments.html"><a href="weight-adjustments.html#weight-calibration"><i class="fa fa-check"></i><b>8.1</b> Weight Calibration</a>
<ul>
<li class="chapter" data-level="" data-path="weight-adjustments.html"><a href="weight-adjustments.html#poststratfication-as-a-treatment-for-non-response"><i class="fa fa-check"></i>Poststratfication as a treatment for non-response</a></li>
<li class="chapter" data-level="" data-path="weight-adjustments.html"><a href="weight-adjustments.html#raking"><i class="fa fa-check"></i>Raking</a></li>
<li class="chapter" data-level="" data-path="weight-adjustments.html"><a href="weight-adjustments.html#another-example"><i class="fa fa-check"></i>Another example</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="weight-adjustments.html"><a href="weight-adjustments.html#replicate-weights"><i class="fa fa-check"></i><b>8.2</b> Replicate weights</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="imputation.html"><a href="imputation.html"><i class="fa fa-check"></i><b>9</b> Imputation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="imputation.html"><a href="imputation.html#mean-median-or-mode-imputation"><i class="fa fa-check"></i><b>9.1</b> Mean, median or mode imputation</a></li>
<li class="chapter" data-level="9.2" data-path="imputation.html"><a href="imputation.html#hot-deck-imputation"><i class="fa fa-check"></i><b>9.2</b> Hot deck imputation</a></li>
<li class="chapter" data-level="9.3" data-path="imputation.html"><a href="imputation.html#cell-methods"><i class="fa fa-check"></i><b>9.3</b> Cell methods</a></li>
<li class="chapter" data-level="9.4" data-path="imputation.html"><a href="imputation.html#regression-methods"><i class="fa fa-check"></i><b>9.4</b> Regression methods</a></li>
<li class="chapter" data-level="9.5" data-path="imputation.html"><a href="imputation.html#multiple-imputation"><i class="fa fa-check"></i><b>9.5</b> Multiple imputation</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="designing-surveys.html"><a href="designing-surveys.html"><i class="fa fa-check"></i><b>10</b> Designing Surveys</a>
<ul>
<li class="chapter" data-level="10.1" data-path="designing-surveys.html"><a href="designing-surveys.html#another-interpretation-of-the-deff"><i class="fa fa-check"></i><b>10.1</b> Another interpretation of the Deff</a></li>
<li class="chapter" data-level="10.2" data-path="designing-surveys.html"><a href="designing-surveys.html#computing-the-required-sample-size"><i class="fa fa-check"></i><b>10.2</b> Computing the Required Sample Size</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li>Lecture notes</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STAT395: Sampling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="survey-analysis" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">7</span> Survey Analysis<a href="survey-analysis.html#survey-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!--- For HTML Only --- Equivalent code for .pdf must be included in preamble.tex -->
<p><span class="math inline">\(\DeclareMathOperator*{\argmin}{argmin}\)</span>
<span class="math inline">\(\newcommand{\var}{\mathrm{Var}}\)</span>
<span class="math inline">\(\newcommand{\bfa}[2]{{\rm\bf #1}[#2]}\)</span>
<span class="math inline">\(\newcommand{\rma}[2]{{\rm     #1}[#2]}\)</span>
<span class="math inline">\(\newcommand{\estm}{\widehat}\)</span></p>
<p>With the ability to load a survey dataset and specify its survey design
we’re now ready to do some analysis.</p>
<p>We’ll use the <code>api</code> dataset which comes with the survey package: it’s a
set of observations of the Academic Performance Index (API) on all
California Schools with at least 100 students in the years 1999 and 2000.</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="survey-analysis.html#cb203-1" tabindex="-1"></a><span class="fu">data</span>(api)</span></code></pre></div>
<p>In particular we’ll use the <code>apiclus2</code> dataset, which is a two stage
cluster sample of 126 schools drawn from the population of 6194.
The top 10 rows of the data set and some of the key variables are shown below.</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="survey-analysis.html#cb204-1" tabindex="-1"></a>apiclus2<span class="sc">$</span>stype <span class="ot">&lt;-</span> <span class="fu">factor</span>(apiclus2<span class="sc">$</span>stype, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">&quot;E&quot;</span>,<span class="st">&quot;M&quot;</span>,<span class="st">&quot;H&quot;</span>))</span>
<span id="cb204-2"><a href="survey-analysis.html#cb204-2" tabindex="-1"></a><span class="fu">levels</span>(apiclus2<span class="sc">$</span>stype) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Elementary&quot;</span>,<span class="st">&quot;Middle&quot;</span>,<span class="st">&quot;High&quot;</span>)</span>
<span id="cb204-3"><a href="survey-analysis.html#cb204-3" tabindex="-1"></a></span>
<span id="cb204-4"><a href="survey-analysis.html#cb204-4" tabindex="-1"></a>apiclus2 <span class="sc">|&gt;</span></span>
<span id="cb204-5"><a href="survey-analysis.html#cb204-5" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n=</span><span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb204-6"><a href="survey-analysis.html#cb204-6" tabindex="-1"></a>  <span class="fu">select</span>(cds, stype, name, dnum, cnum, api99, api00) <span class="sc">|&gt;</span></span>
<span id="cb204-7"><a href="survey-analysis.html#cb204-7" tabindex="-1"></a>  <span class="fu">kbl</span>() <span class="sc">|&gt;</span></span>
<span id="cb204-8"><a href="survey-analysis.html#cb204-8" tabindex="-1"></a>  <span class="fu">kable_styling</span>()</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
cds
</th>
<th style="text-align:left;">
stype
</th>
<th style="text-align:left;">
name
</th>
<th style="text-align:right;">
dnum
</th>
<th style="text-align:right;">
cnum
</th>
<th style="text-align:right;">
api99
</th>
<th style="text-align:right;">
api00
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
31667796031017
</td>
<td style="text-align:left;">
Elementary
</td>
<td style="text-align:left;">
Alta-Dutch Flat
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
785
</td>
<td style="text-align:right;">
821
</td>
</tr>
<tr>
<td style="text-align:left;">
55751846054837
</td>
<td style="text-align:left;">
Elementary
</td>
<td style="text-align:left;">
Tenaya Elementa
</td>
<td style="text-align:right;">
63
</td>
<td style="text-align:right;">
54
</td>
<td style="text-align:right;">
718
</td>
<td style="text-align:right;">
773
</td>
</tr>
<tr>
<td style="text-align:left;">
41688746043517
</td>
<td style="text-align:left;">
Elementary
</td>
<td style="text-align:left;">
Panorama Elemen
</td>
<td style="text-align:right;">
83
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
632
</td>
<td style="text-align:right;">
600
</td>
</tr>
<tr>
<td style="text-align:left;">
41688746043509
</td>
<td style="text-align:left;">
Middle
</td>
<td style="text-align:left;">
Lipman Middle
</td>
<td style="text-align:right;">
83
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
740
</td>
<td style="text-align:right;">
740
</td>
</tr>
<tr>
<td style="text-align:left;">
41688746043491
</td>
<td style="text-align:left;">
Elementary
</td>
<td style="text-align:left;">
Brisbane Elemen
</td>
<td style="text-align:right;">
83
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
711
</td>
<td style="text-align:right;">
716
</td>
</tr>
<tr>
<td style="text-align:left;">
40687266042998
</td>
<td style="text-align:left;">
Elementary
</td>
<td style="text-align:left;">
Cayucos Element
</td>
<td style="text-align:right;">
117
</td>
<td style="text-align:right;">
39
</td>
<td style="text-align:right;">
779
</td>
<td style="text-align:right;">
811
</td>
</tr>
<tr>
<td style="text-align:left;">
20651936023881
</td>
<td style="text-align:left;">
Elementary
</td>
<td style="text-align:left;">
Fuller (Merle L
</td>
<td style="text-align:right;">
132
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
432
</td>
<td style="text-align:right;">
472
</td>
</tr>
<tr>
<td style="text-align:left;">
20651936023931
</td>
<td style="text-align:left;">
Elementary
</td>
<td style="text-align:left;">
Fairmead Elemen
</td>
<td style="text-align:right;">
132
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
494
</td>
<td style="text-align:right;">
520
</td>
</tr>
<tr>
<td style="text-align:left;">
20651936023907
</td>
<td style="text-align:left;">
Middle
</td>
<td style="text-align:left;">
Wilson Elementa
</td>
<td style="text-align:right;">
132
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
589
</td>
<td style="text-align:right;">
568
</td>
</tr>
<tr>
<td style="text-align:left;">
06615980631259
</td>
<td style="text-align:left;">
High
</td>
<td style="text-align:left;">
Colusa High
</td>
<td style="text-align:right;">
152
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
585
</td>
<td style="text-align:right;">
591
</td>
</tr>
</tbody>
</table>
The full set of variables in the dataset is:
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:left;">
Description
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
cds
</td>
<td style="text-align:left;">
Unique identifier
</td>
</tr>
<tr>
<td style="text-align:left;">
stype
</td>
<td style="text-align:left;">
Elementary/Middle/High School
</td>
</tr>
<tr>
<td style="text-align:left;">
name
</td>
<td style="text-align:left;">
School name (15 characters)
</td>
</tr>
<tr>
<td style="text-align:left;">
sname
</td>
<td style="text-align:left;">
School name (40 characters)
</td>
</tr>
<tr>
<td style="text-align:left;">
snum
</td>
<td style="text-align:left;">
School number
</td>
</tr>
<tr>
<td style="text-align:left;">
dname
</td>
<td style="text-align:left;">
District name
</td>
</tr>
<tr>
<td style="text-align:left;">
dnum
</td>
<td style="text-align:left;">
District number
</td>
</tr>
<tr>
<td style="text-align:left;">
cname
</td>
<td style="text-align:left;">
County name
</td>
</tr>
<tr>
<td style="text-align:left;">
cnum
</td>
<td style="text-align:left;">
County number
</td>
</tr>
<tr>
<td style="text-align:left;">
flag
</td>
<td style="text-align:left;">
reason for missing data
</td>
</tr>
<tr>
<td style="text-align:left;">
pcttest
</td>
<td style="text-align:left;">
percentage of students tested
</td>
</tr>
<tr>
<td style="text-align:left;">
api00
</td>
<td style="text-align:left;">
API in 2000
</td>
</tr>
<tr>
<td style="text-align:left;">
api99
</td>
<td style="text-align:left;">
API in 1999
</td>
</tr>
<tr>
<td style="text-align:left;">
target
</td>
<td style="text-align:left;">
target for change in API
</td>
</tr>
<tr>
<td style="text-align:left;">
growth
</td>
<td style="text-align:left;">
Change in API
</td>
</tr>
<tr>
<td style="text-align:left;">
sch.wide
</td>
<td style="text-align:left;">
Met school-wide growth target?
</td>
</tr>
<tr>
<td style="text-align:left;">
comp.imp
</td>
<td style="text-align:left;">
Met Comparable Improvement target
</td>
</tr>
<tr>
<td style="text-align:left;">
both
</td>
<td style="text-align:left;">
Met both targets
</td>
</tr>
<tr>
<td style="text-align:left;">
awards
</td>
<td style="text-align:left;">
Eligible for awards program
</td>
</tr>
<tr>
<td style="text-align:left;">
meals
</td>
<td style="text-align:left;">
Percentage of students eligible for subsidized meals
</td>
</tr>
<tr>
<td style="text-align:left;">
ell
</td>
<td style="text-align:left;">
‘English Language Learners’ (percent)
</td>
</tr>
<tr>
<td style="text-align:left;">
yr.rnd
</td>
<td style="text-align:left;">
Year-round school
</td>
</tr>
<tr>
<td style="text-align:left;">
mobility
</td>
<td style="text-align:left;">
percentage of students for whom this is the first year at the school
</td>
</tr>
<tr>
<td style="text-align:left;">
acs.k3
</td>
<td style="text-align:left;">
average class size years K-3
</td>
</tr>
<tr>
<td style="text-align:left;">
acs.46
</td>
<td style="text-align:left;">
average class size years 4-6
</td>
</tr>
<tr>
<td style="text-align:left;">
acs.core
</td>
<td style="text-align:left;">
Number of core academic courses
</td>
</tr>
<tr>
<td style="text-align:left;">
pct.resp
</td>
<td style="text-align:left;">
percent where parental education level is known
</td>
</tr>
<tr>
<td style="text-align:left;">
not.hsg
</td>
<td style="text-align:left;">
percent parents not high-school graduates
</td>
</tr>
<tr>
<td style="text-align:left;">
hsg
</td>
<td style="text-align:left;">
percent parents who are high-school graduates
</td>
</tr>
<tr>
<td style="text-align:left;">
some.col
</td>
<td style="text-align:left;">
percent parents with some college
</td>
</tr>
<tr>
<td style="text-align:left;">
col.grad
</td>
<td style="text-align:left;">
percent parents with college degree
</td>
</tr>
<tr>
<td style="text-align:left;">
grad.sch
</td>
<td style="text-align:left;">
percent parents with postgraduate education
</td>
</tr>
<tr>
<td style="text-align:left;">
avg.ed
</td>
<td style="text-align:left;">
average parental education level
</td>
</tr>
<tr>
<td style="text-align:left;">
full
</td>
<td style="text-align:left;">
percent fully qualified teachers
</td>
</tr>
<tr>
<td style="text-align:left;">
emer
</td>
<td style="text-align:left;">
percent teachers with emergency qualifications
</td>
</tr>
<tr>
<td style="text-align:left;">
enroll
</td>
<td style="text-align:left;">
number of students enrolled
</td>
</tr>
<tr>
<td style="text-align:left;">
api.stu
</td>
<td style="text-align:left;">
number of students tested.
</td>
</tr>
</tbody>
</table>
<p>The <code>apiclus2</code> dataset was drawn by taking a sample of districts (labelled by district number <code>dnum</code>),
and then a sample of schools within districts (schools are labelled by their school number <code>snum</code>).<br />
The column <code>fpc1</code> contains the number of districts (757), and the column <code>fpc2</code> contains the
number of schools in each district (which varies by district).</p>
<p>We can specify this two stage cluster design using</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="survey-analysis.html#cb205-1" tabindex="-1"></a>apiclus2.des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">ids=</span><span class="sc">~</span>dnum<span class="sc">+</span>snum, <span class="at">fpc=</span><span class="sc">~</span>fpc1<span class="sc">+</span>fpc2, <span class="at">data=</span>apiclus2)</span></code></pre></div>
<p>The <code>summary()</code> function tells us the basics of the design we’ve just specified:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="survey-analysis.html#cb206-1" tabindex="-1"></a><span class="fu">summary</span>(apiclus2.des)</span></code></pre></div>
<pre><code>## 2 - level Cluster Sampling design
## With (40, 126) clusters.
## svydesign(ids = ~dnum + snum, fpc = ~fpc1 + fpc2, data = apiclus2)
## Probabilities:
##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
## 0.003669 0.037743 0.052840 0.042390 0.052840 0.052840 
## Population size (PSUs): 757 
## Data variables:
##  [1] &quot;cds&quot;      &quot;stype&quot;    &quot;name&quot;     &quot;sname&quot;    &quot;snum&quot;     &quot;dname&quot;   
##  [7] &quot;dnum&quot;     &quot;cname&quot;    &quot;cnum&quot;     &quot;flag&quot;     &quot;pcttest&quot;  &quot;api00&quot;   
## [13] &quot;api99&quot;    &quot;target&quot;   &quot;growth&quot;   &quot;sch.wide&quot; &quot;comp.imp&quot; &quot;both&quot;    
## [19] &quot;awards&quot;   &quot;meals&quot;    &quot;ell&quot;      &quot;yr.rnd&quot;   &quot;mobility&quot; &quot;acs.k3&quot;  
## [25] &quot;acs.46&quot;   &quot;acs.core&quot; &quot;pct.resp&quot; &quot;not.hsg&quot;  &quot;hsg&quot;      &quot;some.col&quot;
## [31] &quot;col.grad&quot; &quot;grad.sch&quot; &quot;avg.ed&quot;   &quot;full&quot;     &quot;emer&quot;     &quot;enroll&quot;  
## [37] &quot;api.stu&quot;  &quot;pw&quot;       &quot;fpc1&quot;     &quot;fpc2&quot;</code></pre>
<p>We can see that from the summary that <span class="math inline">\(n=40\)</span> districts were sampled (out of <span class="math inline">\(N=757\)</span>).
Let’s count the number of schools sampled per district. We’ll just display the top 15 largest
districts:</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="survey-analysis.html#cb208-1" tabindex="-1"></a>apiclus2 <span class="sc">|&gt;</span></span>
<span id="cb208-2"><a href="survey-analysis.html#cb208-2" tabindex="-1"></a>  <span class="fu">group_by</span>(dnum,dname) <span class="sc">|&gt;</span></span>
<span id="cb208-3"><a href="survey-analysis.html#cb208-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Mi=</span><span class="fu">first</span>(fpc2),<span class="at">mi=</span><span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb208-4"><a href="survey-analysis.html#cb208-4" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb208-5"><a href="survey-analysis.html#cb208-5" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Mi)) <span class="sc">|&gt;</span></span>
<span id="cb208-6"><a href="survey-analysis.html#cb208-6" tabindex="-1"></a>  <span class="fu">slice_head</span>(<span class="at">n=</span><span class="dv">15</span>) <span class="sc">|&gt;</span></span>
<span id="cb208-7"><a href="survey-analysis.html#cb208-7" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">col.names=</span><span class="fu">c</span>(<span class="st">&quot;dnum&quot;</span>,<span class="st">&quot;District Name&quot;</span>,<span class="st">&quot;$M_i$&quot;</span>,<span class="st">&quot;$m_i$&quot;</span>),<span class="at">escape=</span><span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb208-8"><a href="survey-analysis.html#cb208-8" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
dnum
</th>
<th style="text-align:left;">
District Name
</th>
<th style="text-align:right;">
<span class="math inline">\(M_i\)</span>
</th>
<th style="text-align:right;">
<span class="math inline">\(m_i\)</span>
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
620
</td>
<td style="text-align:left;">
Sacramento City Unified
</td>
<td style="text-align:right;">
72
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
570
</td>
<td style="text-align:left;">
Pomona Unified
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
575
</td>
<td style="text-align:left;">
Poway Unified
</td>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
638
</td>
<td style="text-align:left;">
San Lorenzo Unified
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
200
</td>
<td style="text-align:left;">
El Centro Elementary
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
731
</td>
<td style="text-align:left;">
Sylvan Union Elementary
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
596
</td>
<td style="text-align:left;">
Rincon Valley Union Elem
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
639
</td>
<td style="text-align:left;">
San Lorenzo Valley Unif
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
781
</td>
<td style="text-align:left;">
Walnut Creek Elementary
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
295
</td>
<td style="text-align:left;">
Healdsburg Unified
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
403
</td>
<td style="text-align:left;">
Los Gatos Union Elem
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
480
</td>
<td style="text-align:left;">
Natomas Unified
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
534
</td>
<td style="text-align:left;">
Palo Verde Unified
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
549
</td>
<td style="text-align:left;">
Piedmont City Unified
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:right;">
173
</td>
<td style="text-align:left;">
Del Mar Union Elementary
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
4
</td>
</tr>
</tbody>
</table>
<p>After the 10 largest districts a census of schools is taken in each selected
district <span class="math inline">\(m_i=M_i\)</span></p>
<div id="continous-variables" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Continous variables<a href="survey-analysis.html#continous-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Consider the key outcome variable `api00``, the API score in the year
2000 for each school.</p>
<div id="display" class="section level3 unnumbered hasAnchor">
<h3>Display<a href="survey-analysis.html#display" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The basic workhorse for the display of numerical variables is the histogram</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="survey-analysis.html#cb209-1" tabindex="-1"></a><span class="fu">svyhist</span>(<span class="sc">~</span>api00, <span class="at">design=</span>apiclus2.des, <span class="at">prob=</span><span class="cn">FALSE</span>,</span>
<span id="cb209-2"><a href="survey-analysis.html#cb209-2" tabindex="-1"></a>        <span class="at">xlab=</span><span class="st">&quot;API Score (Year 2000)&quot;</span>, </span>
<span id="cb209-3"><a href="survey-analysis.html#cb209-3" tabindex="-1"></a>        <span class="at">main=</span><span class="st">&quot;Weighted distribution of API (2000) scores&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-150"></span>
<img src="_main_files/figure-html/unnamed-chunk-150-1.png" alt="Weighted histogram of API (2000) scores" width="480" />
<p class="caption">
Figure 7.1: Weighted histogram of API (2000) scores
</p>
</div>
<p>Note that this histogram differs strongly from the simple histogram
of the sample values:</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb210-1"><a href="survey-analysis.html#cb210-1" tabindex="-1"></a><span class="fu">hist</span>(apiclus2<span class="sc">$</span>api00, </span>
<span id="cb210-2"><a href="survey-analysis.html#cb210-2" tabindex="-1"></a>        <span class="at">xlab=</span><span class="st">&quot;API Score (Year 2000)&quot;</span>, </span>
<span id="cb210-3"><a href="survey-analysis.html#cb210-3" tabindex="-1"></a>        <span class="at">main=</span><span class="st">&quot;Unweighted distribution of API (2000) scores&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-151"></span>
<img src="_main_files/figure-html/unnamed-chunk-151-1.png" alt="Unweighted histogram of API (2000) sample data" width="480" />
<p class="caption">
Figure 7.2: Unweighted histogram of API (2000) sample data
</p>
</div>
<p>a warning to us that with survey data we can go badly astray if we ignore
the sample design.</p>
<p>Boxplots are an alternative to histograms:</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="survey-analysis.html#cb211-1" tabindex="-1"></a><span class="fu">svyboxplot</span>(api00<span class="sc">~</span><span class="dv">1</span>, <span class="at">design=</span>apiclus2.des, </span>
<span id="cb211-2"><a href="survey-analysis.html#cb211-2" tabindex="-1"></a>           <span class="at">ylab=</span><span class="st">&quot;API (2000)&quot;</span>, <span class="at">main=</span><span class="st">&quot;API (2000) Scores&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-152"></span>
<img src="_main_files/figure-html/unnamed-chunk-152-1.png" alt="Distribution of API (2000) sample data" width="480" />
<p class="caption">
Figure 7.3: Distribution of API (2000) sample data
</p>
</div>
<p>… especially if we want to display variables divided by a category:</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="survey-analysis.html#cb212-1" tabindex="-1"></a><span class="fu">svyboxplot</span>(api00<span class="sc">~</span>stype, <span class="at">design=</span>apiclus2.des, </span>
<span id="cb212-2"><a href="survey-analysis.html#cb212-2" tabindex="-1"></a>           <span class="at">xlab=</span><span class="st">&quot;School Type&quot;</span>,</span>
<span id="cb212-3"><a href="survey-analysis.html#cb212-3" tabindex="-1"></a>           <span class="at">ylab=</span><span class="st">&quot;API (2000)&quot;</span>, <span class="at">main=</span><span class="st">&quot;API (2000) Scores&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-153"></span>
<img src="_main_files/figure-html/unnamed-chunk-153-1.png" alt="Distribution of API (2000) sample data" width="480" />
<p class="caption">
Figure 7.4: Distribution of API (2000) sample data
</p>
</div>
<p>If we have two continuous variables we can plot them as a scatterplot, showing
the weights of each observation:</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="survey-analysis.html#cb213-1" tabindex="-1"></a><span class="fu">svyplot</span>(api00<span class="sc">~</span>api99, <span class="at">design=</span>apiclus2.des, <span class="at">style=</span><span class="st">&quot;bubble&quot;</span>,</span>
<span id="cb213-2"><a href="survey-analysis.html#cb213-2" tabindex="-1"></a>        <span class="at">xlab=</span><span class="st">&quot;API (1999)&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;API (2000)&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-154"></span>
<img src="_main_files/figure-html/unnamed-chunk-154-1.png" alt="Distribution of API scores in 1999 and 2000" width="480" />
<p class="caption">
Figure 7.5: Distribution of API scores in 1999 and 2000
</p>
</div>
</div>
<div id="estimation" class="section level3 unnumbered hasAnchor">
<h3>Estimation<a href="survey-analysis.html#estimation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We’ve already seen that we can estimate means using the <code>svymean()</code> function.</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb214-1"><a href="survey-analysis.html#cb214-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>api00, <span class="at">design=</span>apiclus2.des)</span></code></pre></div>
<pre><code>##         mean     SE
## api00 670.81 30.099</code></pre>
<p>The <code>jtools</code> package allows us to estimate the population standard deviation too</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="survey-analysis.html#cb216-1" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb216-2"><a href="survey-analysis.html#cb216-2" tabindex="-1"></a><span class="fu">svysd</span>(<span class="sc">~</span>api00, <span class="at">design=</span>apiclus2.des)</span></code></pre></div>
<pre><code>##       std. dev.
## api00    136.83</code></pre>
<p>(<strong>Pause a minute</strong> and remind yourself of the difference between a standard deviation and
a standard error.)</p>
<p>We can estimates means for a set of separate variables, using a perhaps uninintuitive notation:</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="survey-analysis.html#cb218-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>api99<span class="sc">+</span>api00, <span class="at">design=</span>apiclus2.des)</span></code></pre></div>
<pre><code>##         mean     SE
## api99 645.03 29.711
## api00 670.81 30.099</code></pre>
<p>or for a variable split by categories by wrapping <code>svymean()</code> up inside a call to <code>svyby()</code></p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="survey-analysis.html#cb220-1" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>api00, <span class="at">by=</span><span class="sc">~</span>stype, svymean, <span class="at">design=</span>apiclus2.des)</span></code></pre></div>
<pre><code>##                 stype    api00       se
## Elementary Elementary 692.8104 29.92660
## Middle         Middle 642.3520 45.09132
## High             High 598.3407 17.69417</code></pre>
<p>A <strong>dotchart</strong> is a nice way of showing the estimated means and their confidence intervals:</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="survey-analysis.html#cb222-1" tabindex="-1"></a>ss <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="sc">~</span>api00, <span class="at">by=</span><span class="sc">~</span>stype, svymean, <span class="at">design=</span>apiclus2.des)</span>
<span id="cb222-2"><a href="survey-analysis.html#cb222-2" tabindex="-1"></a>sc <span class="ot">&lt;-</span> <span class="fu">confint</span>(ss)</span>
<span id="cb222-3"><a href="survey-analysis.html#cb222-3" tabindex="-1"></a>ns <span class="ot">&lt;-</span> <span class="fu">nrow</span>(sc)</span>
<span id="cb222-4"><a href="survey-analysis.html#cb222-4" tabindex="-1"></a><span class="fu">dotchart</span>(ss, <span class="at">xlim=</span><span class="fu">range</span>(sc), <span class="at">xlab=</span><span class="st">&quot;Mean API (2000) Score&quot;</span>)</span>
<span id="cb222-5"><a href="survey-analysis.html#cb222-5" tabindex="-1"></a><span class="fu">arrows</span>(sc[,<span class="dv">1</span>], <span class="dv">1</span><span class="sc">:</span>ns, sc[,<span class="dv">2</span>], <span class="dv">1</span><span class="sc">:</span>ns, <span class="at">angle=</span><span class="dv">90</span>, <span class="at">code=</span><span class="dv">3</span>, <span class="at">length=</span><span class="fl">0.1</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-159"></span>
<img src="_main_files/figure-html/unnamed-chunk-159-1.png" alt="Mean API (2000) scores by School Type" width="480" />
<p class="caption">
Figure 7.6: Mean API (2000) scores by School Type
</p>
</div>
<p>If we want to test statistical hypotheses about differences between groups
one way is to use the regression framework</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="survey-analysis.html#cb223-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">svyglm</span>(api00<span class="sc">~</span>stype, <span class="at">design=</span>apiclus2.des))</span></code></pre></div>
<pre><code>## 
## Call:
## svyglm(formula = api00 ~ stype, design = apiclus2.des)
## 
## Survey design:
## svydesign(ids = ~dnum + snum, fpc = ~fpc1 + fpc2, data = apiclus2)
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   692.81      29.93  23.150  &lt; 2e-16 ***
## stypeMiddle   -50.46      25.30  -1.994  0.05354 .  
## stypeHigh     -94.47      28.21  -3.348  0.00188 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 17528.44)
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<p>Here we can see that with Elementary as the reference level we
get the same estimate of the mean API reported as the <code>(Intercept)</code>.
We further see that there is no significant difference between Middle
and Elementary Schools in mean API, but the mean API is significantly lower
at High Schools compared to Elementary Schools.</p>
<p>Regressions take of course take lots of variables into account, and
we can apply familiar regression techniques to investigating
conditional associations between predictors and a continuous outcome.</p>
<p>For example we can test whether the percentage of children at a school
who have free school meals (i.e. the <code>meals</code> variable) associates with the
API score:</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="survey-analysis.html#cb225-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">svyglm</span>(api00<span class="sc">~</span>stype<span class="sc">+</span>meals, <span class="at">design=</span>apiclus2.des))</span></code></pre></div>
<pre><code>## 
## Call:
## svyglm(formula = api00 ~ stype + meals, design = apiclus2.des)
## 
## Survey design:
## svydesign(ids = ~dnum + snum, fpc = ~fpc1 + fpc2, data = apiclus2)
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  874.8638    16.4677  53.126  &lt; 2e-16 ***
## stypeMiddle  -60.9517    20.6964  -2.945  0.00563 ** 
## stypeHigh   -169.2128    20.2618  -8.351 6.06e-10 ***
## meals         -3.2367     0.2888 -11.209 2.70e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 5560.106)
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<p>… and there is indeed a strong negative association: the higher the
<code>meals</code> value the lower the API score.</p>
<p>We can estimate <strong>totals</strong> using the <code>svytotal()</code> function - for example
we can estimate the total number of students enrolled at all schools in
California:</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="survey-analysis.html#cb227-1" tabindex="-1"></a><span class="fu">svytotal</span>(<span class="sc">~</span>enroll, <span class="at">design=</span>apiclus2.des, <span class="at">na.rm=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>##          total     SE
## enroll 2639273 799638</code></pre>
<p>Although note that we have had to remove some schools with unknown
<code>enroll</code> values by stating <code>na.rm=TRUE</code>, and these forced removals likely mean
that our estimate of the total is an underestimate.</p>
<p>Confidence intervals can be calculated using the <code>confint()</code> function</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="survey-analysis.html#cb229-1" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">svymean</span>(<span class="sc">~</span>api99<span class="sc">+</span>api00, <span class="at">design=</span>apiclus2.des), <span class="at">level=</span><span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##          2.5 %   97.5 %
## api99 586.8009 703.2670
## api00 611.8188 729.8048</code></pre>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="survey-analysis.html#cb231-1" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">svyby</span>(<span class="sc">~</span>api00, <span class="at">by=</span><span class="sc">~</span>stype, svymean, <span class="at">design=</span>apiclus2.des))</span></code></pre></div>
<pre><code>##               2.5 %   97.5 %
## Elementary 634.1553 751.4655
## Middle     553.9746 730.7294
## High       563.6607 633.0206</code></pre>
<p>The standard errors can be directly extracted using <code>SE()</code></p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="survey-analysis.html#cb233-1" tabindex="-1"></a><span class="fu">SE</span>(<span class="fu">svyby</span>(<span class="sc">~</span>api00, <span class="at">by=</span><span class="sc">~</span>stype, svymean, <span class="at">design=</span>apiclus2.des))</span></code></pre></div>
<pre><code>## [1] 29.92660 45.09132 17.69417</code></pre>
</div>
<div id="relative-sampling-errors-rses" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Relative Sampling Errors (RSEs)<a href="survey-analysis.html#relative-sampling-errors-rses" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The <strong>relative standard errors</strong>, also known as <strong>relative sampling errors</strong>
(RSEs) can be extracted by <code>cv()</code>:</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="survey-analysis.html#cb235-1" tabindex="-1"></a><span class="fu">cv</span>(<span class="fu">svyby</span>(<span class="sc">~</span>api00, <span class="at">by=</span><span class="sc">~</span>stype, svymean, <span class="at">design=</span>apiclus2.des))</span></code></pre></div>
<pre><code>## Elementary     Middle       High 
## 0.04319595 0.07019721 0.02957206</code></pre>
<p>RSEs are a useful measure of quality of estimates of quantities that are
strictly positive, such as the API score.</p>
<p>If we learned that the SE of an estimate (e.g. the mean of <code>api00</code>) was
30.1 we wouldn’t be able to assess whether it
was a good estimate or not without knowing that the value of the estimate
was 670.81. A good way to assess the quality of
an estimate is the SE of an estimate <span class="math inline">\(\widehat{T}\)</span> as a proportion of
the estimate <span class="math inline">\(\widehat{T}\)</span>:
<span class="math display">\[
   \bfa{RSE}{\widehat{T}} = \frac{\bfa{SE}{\widehat{T}}}{\widehat{T}}
\]</span>
For overall mean <code>api00</code> the RSE is
<span class="math display">\[
   \bfa{RSE}{\widehat{\bar{Y}}}
   = \frac{30.1}{670.81}
   = 0.045
\]</span>
This is a highly precise estimate: the SE is only 4.5%
of the value of the estimate.</p>
<p>Good RSEs are only a few percent at most. Poor RSEs are larger than 10%, and anything bigger
than 20% isn’t really publishable.</p>
<p>In general a standard deviation divided by a mean goes by the term
<strong>coefficient of variation</strong> (CV), which is why the R function is
called <code>cv()</code>.</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="survey-analysis.html#cb237-1" tabindex="-1"></a><span class="fu">cv</span>(<span class="fu">svymean</span>(<span class="sc">~</span>api00, <span class="at">design=</span>apiclus2.des))</span></code></pre></div>
<pre><code>##            api00
## api00 0.04486956</code></pre>
</div>
</div>
<div id="categorical-variables" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Categorical Variables<a href="survey-analysis.html#categorical-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The workhorse display for categorical variables is the barplot,
showing <strong>proportions</strong> in categories. Proportions are first calculated
using the <code>svymean()</code> function:</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="survey-analysis.html#cb239-1" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">svymean</span>(<span class="sc">~</span>stype, <span class="at">design=</span>apiclus2.des),</span>
<span id="cb239-2"><a href="survey-analysis.html#cb239-2" tabindex="-1"></a>        <span class="at">names=</span><span class="fu">levels</span>(apiclus2<span class="sc">$</span>stype),</span>
<span id="cb239-3"><a href="survey-analysis.html#cb239-3" tabindex="-1"></a>        <span class="at">xlab=</span><span class="st">&quot;School Type&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Proportion&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-169"></span>
<img src="_main_files/figure-html/unnamed-chunk-169-1.png" alt="Estimates of the proportions of Schools of each type" width="480" />
<p class="caption">
Figure 7.7: Estimates of the proportions of Schools of each type
</p>
</div>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="survey-analysis.html#cb240-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>stype, <span class="at">design=</span>apiclus2.des)</span></code></pre></div>
<pre><code>##                    mean     SE
## stypeElementary 0.68118 0.0556
## stypeMiddle     0.18450 0.0222
## stypeHigh       0.13432 0.0567</code></pre>
<p>It’s worth pausing to recognise that a proportion is a mean of a special
type of variable called an <strong>indicator variable</strong>: it takes the value 1 if
the observation is a member of specific category and 0 if not. Add up all the ones
and zeroes and you get the number of observations in the category, and divide
by the number of observations you get a proportion.
<span class="math display">\[
    p = \frac{1 + 0 + 1 + 1 + 0 + 0 + ....}{n} = \frac{1}{n}\sum_{i=1}^n Y_i
\]</span>
where <span class="math inline">\(Y_i\)</span> is an indicator variable.</p>
<p>With sample data we calculate <strong>weighted sums</strong> though:
<span class="math display">\[
   \widehat{p} = \frac{\sum_{i=1}^n w_i Y_i}{\sum_{i=1}^n w_i} = \frac{\widehat{Y}}{\widehat{N}}
\]</span>
where the top line of this fraction is <span class="math inline">\(\widehat{Y}\)</span>, our estimate of the
number of individuals (in a finite population) who belong to the category of
interest. The bottom line is <span class="math inline">\(\widehat{N}\)</span>, the estimated size of the population.
<span class="math inline">\(\widehat{N}\)</span> is exact in some designs (e.g. SRSWOR, or Stratified SRSWOR), but
is approximate in other designs (especially cluster designs).</p>
<p>These total estimates within categories can be estimated using the <code>svytotal()</code>
function.</p>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="survey-analysis.html#cb242-1" tabindex="-1"></a><span class="fu">svytotal</span>(<span class="sc">~</span>stype, <span class="at">design=</span>apiclus2.des)</span></code></pre></div>
<pre><code>##                   total      SE
## stypeElementary 3493.56 1119.75
## stypeMiddle      946.25  311.81
## stypeHigh        688.87  289.35</code></pre>
<p>When creating barplots of estimated proportions and/or totals
we really should indicate the uncertainties in our
estimates, and show confidence intervals on the bars. We can use the standard
errors provided by <code>svymean()</code> and <code>svytotal()</code>: the function <code>confint()</code>
will provide these:</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="survey-analysis.html#cb244-1" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">svytotal</span>(<span class="sc">~</span>stype, <span class="at">design=</span>apiclus2.des))</span></code></pre></div>
<pre><code>##                     2.5 %   97.5 %
## stypeElementary 1298.8892 5688.221
## stypeMiddle      335.1077 1557.392
## stypeHigh        121.7472 1255.993</code></pre>
<p>These confidence intervals are symmetric about the point estimates:</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="survey-analysis.html#cb246-1" tabindex="-1"></a>ss <span class="ot">&lt;-</span> <span class="fu">svymean</span>(<span class="sc">~</span>stype, <span class="at">design=</span>apiclus2.des)</span>
<span id="cb246-2"><a href="survey-analysis.html#cb246-2" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">confint</span>(ss)</span>
<span id="cb246-3"><a href="survey-analysis.html#cb246-3" tabindex="-1"></a>bp <span class="ot">&lt;-</span> <span class="fu">barplot</span>(ss, <span class="at">xlab=</span><span class="st">&quot;School Type&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Estimated Size&quot;</span>,</span>
<span id="cb246-4"><a href="survey-analysis.html#cb246-4" tabindex="-1"></a>              <span class="at">names=</span><span class="fu">levels</span>(apiclus2<span class="sc">$</span>stype),</span>
<span id="cb246-5"><a href="survey-analysis.html#cb246-5" tabindex="-1"></a>              <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fu">max</span>(ci)))</span>
<span id="cb246-6"><a href="survey-analysis.html#cb246-6" tabindex="-1"></a><span class="fu">arrows</span>(bp, ci[,<span class="dv">1</span>], bp, ci[,<span class="dv">2</span>], <span class="at">angle=</span><span class="dv">90</span>, <span class="at">length=</span><span class="fl">0.2</span>, <span class="at">code=</span><span class="dv">3</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-173"></span>
<img src="_main_files/figure-html/unnamed-chunk-173-1.png" alt="Estimated proportions of schools by school type - with symmetric confidence intervals" width="480" />
<p class="caption">
Figure 7.8: Estimated proportions of schools by school type - with symmetric confidence intervals
</p>
</div>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="survey-analysis.html#cb247-1" tabindex="-1"></a><span class="fu">names</span>(ss) <span class="ot">&lt;-</span> <span class="fu">levels</span>(apiclus2<span class="sc">$</span>stype)</span>
<span id="cb247-2"><a href="survey-analysis.html#cb247-2" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">as.numeric</span>(ss),ci) <span class="sc">|&gt;</span></span>
<span id="cb247-3"><a href="survey-analysis.html#cb247-3" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">col.names=</span><span class="fu">c</span>(<span class="st">&quot;Estimate&quot;</span>,<span class="st">&quot;2.5%&quot;</span>,<span class="st">&quot;97.5%&quot;</span>), </span>
<span id="cb247-4"><a href="survey-analysis.html#cb247-4" tabindex="-1"></a>      <span class="at">digits=</span><span class="dv">3</span>,</span>
<span id="cb247-5"><a href="survey-analysis.html#cb247-5" tabindex="-1"></a>      <span class="at">caption=</span><span class="st">&quot;Symmetric confidence interval estimates&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb247-6"><a href="survey-analysis.html#cb247-6" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:tabci.symmetric)Symmetric confidence interval estimates
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
2.5%
</th>
<th style="text-align:right;">
97.5%
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
stypeElementary
</td>
<td style="text-align:right;">
0.681
</td>
<td style="text-align:right;">
0.572
</td>
<td style="text-align:right;">
0.790
</td>
</tr>
<tr>
<td style="text-align:left;">
stypeMiddle
</td>
<td style="text-align:right;">
0.185
</td>
<td style="text-align:right;">
0.141
</td>
<td style="text-align:right;">
0.228
</td>
</tr>
<tr>
<td style="text-align:left;">
stypeHigh
</td>
<td style="text-align:right;">
0.134
</td>
<td style="text-align:right;">
0.023
</td>
<td style="text-align:right;">
0.246
</td>
</tr>
</tbody>
</table>
<p>These symmetric intervals are actually somewhat unrealistic, because
<code>confint()</code> doesn’t know it’s dealing with indicator variables, and
doesn’t take into account the fact that proportions and totals can’t go
negative.</p>
<p>A better method of constructing confidence intervals is the special
function <code>svyciprop()</code>:</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="survey-analysis.html#cb248-1" tabindex="-1"></a><span class="fu">svyciprop</span>(<span class="sc">~</span><span class="fu">I</span>(stype<span class="sc">==</span><span class="st">&quot;Elementary&quot;</span>), <span class="at">design=</span>apiclus2.des)</span></code></pre></div>
<pre><code>##                                 2.5% 97.5%
## I(stype == &quot;Elementary&quot;) 0.681 0.560 0.782</code></pre>
<p>Note that we’ve had to create an indicator variable here using the <code>I()</code>
function for just one level in order to calculate its confidence interval.</p>
<p>To get a confidence interval proportion for every level of a factor
it’s somewhat fiddly with the raw <code>survey</code> package:</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="survey-analysis.html#cb250-1" tabindex="-1"></a>ss <span class="ot">&lt;-</span> <span class="fu">svymean</span>(<span class="sc">~</span>stype, <span class="at">design=</span>apiclus2.des)</span>
<span id="cb250-2"><a href="survey-analysis.html#cb250-2" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">t</span>(<span class="fu">sapply</span>(<span class="fu">levels</span>(apiclus2<span class="sc">$</span>stype),</span>
<span id="cb250-3"><a href="survey-analysis.html#cb250-3" tabindex="-1"></a>       <span class="cf">function</span>(stypelevel) {</span>
<span id="cb250-4"><a href="survey-analysis.html#cb250-4" tabindex="-1"></a>          form <span class="ot">&lt;-</span> <span class="fu">eval</span>(<span class="fu">parse</span>(<span class="at">text=</span><span class="fu">paste0</span>(<span class="st">&quot;formula(~I(stype==</span><span class="sc">\&quot;</span><span class="st">&quot;</span>,stypelevel,<span class="st">&quot;</span><span class="sc">\&quot;</span><span class="st">))&quot;</span>)))</span>
<span id="cb250-5"><a href="survey-analysis.html#cb250-5" tabindex="-1"></a>          <span class="fu">confint</span>(<span class="fu">svyciprop</span>(form, <span class="at">design=</span>apiclus2.des))    </span>
<span id="cb250-6"><a href="survey-analysis.html#cb250-6" tabindex="-1"></a>       }))</span>
<span id="cb250-7"><a href="survey-analysis.html#cb250-7" tabindex="-1"></a>bp <span class="ot">&lt;-</span> <span class="fu">barplot</span>(ss, <span class="at">xlab=</span><span class="st">&quot;School Type&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Estimated Size&quot;</span>,</span>
<span id="cb250-8"><a href="survey-analysis.html#cb250-8" tabindex="-1"></a>              <span class="at">names=</span><span class="fu">levels</span>(apiclus2<span class="sc">$</span>stype),</span>
<span id="cb250-9"><a href="survey-analysis.html#cb250-9" tabindex="-1"></a>              <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fu">max</span>(ci)))</span>
<span id="cb250-10"><a href="survey-analysis.html#cb250-10" tabindex="-1"></a><span class="fu">arrows</span>(bp, ci[,<span class="dv">1</span>], bp, ci[,<span class="dv">2</span>], <span class="at">angle=</span><span class="dv">90</span>, <span class="at">length=</span><span class="fl">0.2</span>, <span class="at">code=</span><span class="dv">3</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-175"></span>
<img src="_main_files/figure-html/unnamed-chunk-175-1.png" alt="Estimated proportions of schools by school type - with asymmetric confidence intervals" width="480" />
<p class="caption">
Figure 7.9: Estimated proportions of schools by school type - with asymmetric confidence intervals
</p>
</div>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="survey-analysis.html#cb251-1" tabindex="-1"></a><span class="fu">names</span>(ss) <span class="ot">&lt;-</span> <span class="fu">levels</span>(apiclus2<span class="sc">$</span>stype)</span>
<span id="cb251-2"><a href="survey-analysis.html#cb251-2" tabindex="-1"></a><span class="fu">cbind</span>(<span class="fu">as.numeric</span>(ss),ci) <span class="sc">|&gt;</span></span>
<span id="cb251-3"><a href="survey-analysis.html#cb251-3" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">col.names=</span><span class="fu">c</span>(<span class="st">&quot;Estimate&quot;</span>,<span class="st">&quot;2.5%&quot;</span>,<span class="st">&quot;97.5%&quot;</span>), </span>
<span id="cb251-4"><a href="survey-analysis.html#cb251-4" tabindex="-1"></a>      <span class="at">digits=</span><span class="dv">3</span>,</span>
<span id="cb251-5"><a href="survey-analysis.html#cb251-5" tabindex="-1"></a>      <span class="at">caption=</span><span class="st">&quot;Asymmetric confidence interval estimates&quot;</span>) <span class="sc">|&gt;</span></span>
<span id="cb251-6"><a href="survey-analysis.html#cb251-6" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:tabci.asymmetric)Asymmetric confidence interval estimates
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
2.5%
</th>
<th style="text-align:right;">
97.5%
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Elementary
</td>
<td style="text-align:right;">
0.681
</td>
<td style="text-align:right;">
0.560
</td>
<td style="text-align:right;">
0.782
</td>
</tr>
<tr>
<td style="text-align:left;">
Middle
</td>
<td style="text-align:right;">
0.185
</td>
<td style="text-align:right;">
0.144
</td>
<td style="text-align:right;">
0.234
</td>
</tr>
<tr>
<td style="text-align:left;">
High
</td>
<td style="text-align:right;">
0.134
</td>
<td style="text-align:right;">
0.055
</td>
<td style="text-align:right;">
0.294
</td>
</tr>
</tbody>
</table>
<p>The biggest thing to notice is that the confidence interval for “High”
is now asymmetric: it’s longer on the high side that the low side, and
more correctly represents our uncertainty. The estimates for “Elementary”
and “Middle” are essentially unchanged.</p>
<p>For <strong>crosstabulations</strong> we can use <code>svytable()</code>, which gives weighted
counts in categories - e.g. of whether School Wide growth targest had been met</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="survey-analysis.html#cb252-1" tabindex="-1"></a><span class="fu">svytable</span>(<span class="sc">~</span>stype<span class="sc">+</span>sch.wide, <span class="at">design=</span>apiclus2.des)</span></code></pre></div>
<pre><code>##             sch.wide
## stype              No      Yes
##   Elementary  242.240 3251.315
##   Middle      446.630  499.620
##   High        586.675  102.195</code></pre>
<p>Which can be displayed with a side-by-side barplot</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="survey-analysis.html#cb254-1" tabindex="-1"></a>st <span class="ot">&lt;-</span> <span class="fu">svytable</span>(<span class="sc">~</span>sch.wide<span class="sc">+</span>stype, <span class="at">design=</span>apiclus2.des)</span>
<span id="cb254-2"><a href="survey-analysis.html#cb254-2" tabindex="-1"></a>bp <span class="ot">&lt;-</span> <span class="fu">barplot</span>(st, <span class="at">beside=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;light blue&quot;</span>,<span class="st">&quot;dark red&quot;</span>),</span>
<span id="cb254-3"><a href="survey-analysis.html#cb254-3" tabindex="-1"></a>              <span class="at">legend=</span><span class="cn">TRUE</span>, <span class="at">args.legend=</span><span class="fu">list</span>(<span class="at">title=</span><span class="st">&quot;Met targets&quot;</span>), </span>
<span id="cb254-4"><a href="survey-analysis.html#cb254-4" tabindex="-1"></a>              <span class="at">xlab=</span><span class="st">&quot;School Type&quot;</span>, <span class="at">ylab=</span><span class="st">&quot;Frequency&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-177"></span>
<img src="_main_files/figure-html/unnamed-chunk-177-1.png" alt="Counts of schools meeting targets, by school type" width="480" />
<p class="caption">
Figure 7.10: Counts of schools meeting targets, by school type
</p>
</div>
<p>A test of association is given by the weighted Chi-Square test</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="survey-analysis.html#cb255-1" tabindex="-1"></a><span class="fu">svychisq</span>(<span class="sc">~</span>stype<span class="sc">+</span>sch.wide, <span class="at">design=</span>apiclus2.des)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s X^2: Rao &amp; Scott adjustment
## 
## data:  svychisq(~stype + sch.wide, design = apiclus2.des)
## F = 11.873, ndf = 1.3825, ddf = 53.9175, p-value = 0.0003221</code></pre>
<p>We can carry out a logistic regression to make a similar test of association.<br />
We have <code>sch.wide</code> as the binary outcome variable and <code>stype</code> as the predictor:</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="survey-analysis.html#cb257-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">svyglm</span>(<span class="fu">I</span>(sch.wide<span class="sc">==</span><span class="st">&quot;Yes&quot;</span>)<span class="sc">~</span>stype, <span class="at">family=</span><span class="fu">quasibinomial</span>(<span class="at">link=</span><span class="st">&quot;logit&quot;</span>), </span>
<span id="cb257-2"><a href="survey-analysis.html#cb257-2" tabindex="-1"></a>               <span class="at">design=</span>apiclus2.des))</span></code></pre></div>
<pre><code>## 
## Call:
## svyglm(formula = I(sch.wide == &quot;Yes&quot;) ~ stype, design = apiclus2.des, 
##     family = quasibinomial(link = &quot;logit&quot;))
## 
## Survey design:
## svydesign(ids = ~dnum + snum, fpc = ~fpc1 + fpc2, data = apiclus2)
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   2.5969     0.5997   4.331 0.000109 ***
## stypeMiddle  -2.4848     1.1565  -2.148 0.038292 *  
## stypeHigh    -4.3445     0.8757  -4.961 1.59e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for quasibinomial family taken to be 1.008)
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>With regular <code>lm()</code> and <code>glm()</code> regression fits we can use F tests to determine
whether specific terms in the model should be included. A similar test
can be done to test for the inclusion of specific terms using <code>regTermTest</code></p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="survey-analysis.html#cb259-1" tabindex="-1"></a>sr <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(<span class="fu">I</span>(sch.wide<span class="sc">==</span><span class="st">&quot;Yes&quot;</span>)<span class="sc">~</span>stype, <span class="at">family=</span><span class="fu">quasibinomial</span>(<span class="at">link=</span><span class="st">&quot;logit&quot;</span>), </span>
<span id="cb259-2"><a href="survey-analysis.html#cb259-2" tabindex="-1"></a>               <span class="at">design=</span>apiclus2.des)</span>
<span id="cb259-3"><a href="survey-analysis.html#cb259-3" tabindex="-1"></a><span class="fu">regTermTest</span>(sr, <span class="sc">~</span>stype)</span></code></pre></div>
<pre><code>## Wald test for stype
##  in svyglm(formula = I(sch.wide == &quot;Yes&quot;) ~ stype, design = apiclus2.des, 
##     family = quasibinomial(link = &quot;logit&quot;))
## F =  13.61363  on  2  and  37  df: p= 3.7061e-05</code></pre>
<p>Here we can see that <code>stype</code> is contributing significantly to the fit of the model.</p>
</div>
<div id="ratio-estimation" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Ratio estimation<a href="survey-analysis.html#ratio-estimation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There often arise circumstances in survey analysis where we can expect one variable
to be proportional to another: for example population and GDP are likely to move together.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-182"></span>
<img src="_main_files/figure-html/unnamed-chunk-182-1.png" alt="Population and GDP (2023) (Source: Our World in Data)" width="480" />
<p class="caption">
Figure 7.11: Population and GDP (2023) (Source: Our World in Data)
</p>
</div>
<p>The are three clear outliers here are the US, China and India.</p>
<p>We have full data on <span class="math inline">\(N=150\)</span> countries, and the total GDP of the world
in 2023 was <span class="math inline">\(Y=9.1046\times 10^{4}\)</span> in billions of US dollars.</p>
<p>Let’s imagine though that we only had a sample of <span class="math inline">\(n=40\)</span> countries out of the
<span class="math inline">\(N=150\)</span> and wanted to estimate the total GDP <span class="math inline">\(Y\)</span>. The first 10 rows of our sample
are shown below.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Country
</th>
<th style="text-align:right;">
Population
</th>
<th style="text-align:right;">
GDP
</th>
<th style="text-align:right;">
bigN
</th>
<th style="text-align:right;">
weight
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Zambia
</td>
<td style="text-align:right;">
20.723967
</td>
<td style="text-align:right;">
27.580696
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
3.75
</td>
</tr>
<tr>
<td style="text-align:left;">
Saudi Arabia
</td>
<td style="text-align:right;">
33.264289
</td>
<td style="text-align:right;">
863.963569
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
3.75
</td>
</tr>
<tr>
<td style="text-align:left;">
Mauritius
</td>
<td style="text-align:right;">
1.273591
</td>
<td style="text-align:right;">
14.170188
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
3.75
</td>
</tr>
<tr>
<td style="text-align:left;">
Bahrain
</td>
<td style="text-align:right;">
1.569674
</td>
<td style="text-align:right;">
39.966811
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
3.75
</td>
</tr>
<tr>
<td style="text-align:left;">
Benin
</td>
<td style="text-align:right;">
14.111035
</td>
<td style="text-align:right;">
17.831007
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
3.75
</td>
</tr>
<tr>
<td style="text-align:left;">
Myanmar
</td>
<td style="text-align:right;">
54.133800
</td>
<td style="text-align:right;">
63.756974
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
3.75
</td>
</tr>
<tr>
<td style="text-align:left;">
Mozambique
</td>
<td style="text-align:right;">
33.635163
</td>
<td style="text-align:right;">
20.532020
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
3.75
</td>
</tr>
<tr>
<td style="text-align:left;">
Bosnia and Herzegovina
</td>
<td style="text-align:right;">
3.185072
</td>
<td style="text-align:right;">
20.681711
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
3.75
</td>
</tr>
<tr>
<td style="text-align:left;">
Montenegro
</td>
<td style="text-align:right;">
0.633553
</td>
<td style="text-align:right;">
5.161591
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
3.75
</td>
</tr>
<tr>
<td style="text-align:left;">
Japan
</td>
<td style="text-align:right;">
124.370947
</td>
<td style="text-align:right;">
4601.203386
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
3.75
</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-184"></span>
<img src="_main_files/figure-html/unnamed-chunk-184-1.png" alt="Sample of 40 countries: Population and GDP (2023) (Source: Our World in Data)" width="480" />
<p class="caption">
Figure 7.12: Sample of 40 countries: Population and GDP (2023) (Source: Our World in Data)
</p>
</div>
<p>Our sample happens to miss out on all three of the big countries here.
Note that there are some mid-size countries with low GDP visible in the
plot, so that the relationship between population and GDP isn’t simple.</p>
<p>Our design specification is:</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="survey-analysis.html#cb261-1" tabindex="-1"></a>gdp.sample.des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id=</span><span class="sc">~</span><span class="dv">1</span>, <span class="at">fpc=</span><span class="sc">~</span>bigN, <span class="at">data=</span>gdp.sample)</span></code></pre></div>
<p>and our total GDP estimate is</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="survey-analysis.html#cb262-1" tabindex="-1"></a>ss1 <span class="ot">&lt;-</span> <span class="fu">svytotal</span>(<span class="sc">~</span>GDP, gdp.sample.des)</span>
<span id="cb262-2"><a href="survey-analysis.html#cb262-2" tabindex="-1"></a>ss1</span></code></pre></div>
<pre><code>##     total    SE
## GDP 81890 22980</code></pre>
<p>This estimate has a very high SE due to the high variability among
countries in GDP, and leads to a very wide confidence interval</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="survey-analysis.html#cb264-1" tabindex="-1"></a>ci1 <span class="ot">&lt;-</span> <span class="fu">confint</span>(ss1)</span>
<span id="cb264-2"><a href="survey-analysis.html#cb264-2" tabindex="-1"></a>ci1</span></code></pre></div>
<pre><code>##        2.5 %   97.5 %
## GDP 36850.06 126930.8</code></pre>
<p>with a very high RSE</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="survey-analysis.html#cb266-1" tabindex="-1"></a><span class="fu">cv</span>(ss1)</span></code></pre></div>
<pre><code>##           GDP
## GDP 0.2806213</code></pre>
<p>indicating an estimate of low quality.</p>
<p>We could use the correlation between population <span class="math inline">\(x_i\)</span> and GDP <span class="math inline">\(y_i\)</span> and
fit a standard regression model
<span class="math display">\[
   y_i = \beta x_i + \varepsilon_i\qquad \varepsilon_i\sim N(0,\sigma^2)
\]</span>
omitting the intercept since we want GDP to be proportional to population.</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="survey-analysis.html#cb268-1" tabindex="-1"></a>lmfit <span class="ot">&lt;-</span> <span class="fu">svyglm</span>(GDP <span class="sc">~</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">+</span> Population, <span class="at">design=</span>gdp.sample.des)</span>
<span id="cb268-2"><a href="survey-analysis.html#cb268-2" tabindex="-1"></a><span class="fu">summary</span>(lmfit)</span></code></pre></div>
<pre><code>## 
## Call:
## svyglm(formula = GDP ~ -1 + Population, design = gdp.sample.des)
## 
## Survey design:
## svydesign(id = ~1, fpc = ~bigN, data = gdp.sample)
## 
## Coefficients:
##            Estimate Std. Error t value Pr(&gt;|t|)    
## Population   27.870      4.117    6.77 4.44e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 423229.9)
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<p>The coefficient <span class="math inline">\(\beta\)</span> is the GDP ($Billions) per million people in the population.
A 95% confidence interval for <span class="math inline">\(\beta\)</span> is</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="survey-analysis.html#cb270-1" tabindex="-1"></a><span class="fu">confint</span>(lmfit)</span></code></pre></div>
<pre><code>##               2.5 %   97.5 %
## Population 19.54262 36.19642</code></pre>
<p>It does have a better RSE than our earlier estimate</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="survey-analysis.html#cb272-1" tabindex="-1"></a><span class="fu">cv</span>(lmfit)</span></code></pre></div>
<pre><code>## Population 
##  0.1477149</code></pre>
<p>Scaling the estimated GDP per million by the total population of the world (<span class="math inline">\(X=7646.716928\)</span> million) we
still get a rather wide confidence interval</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="survey-analysis.html#cb274-1" tabindex="-1"></a>ci2 <span class="ot">&lt;-</span> <span class="fu">confint</span>(lmfit)<span class="sc">*</span>poptotal</span>
<span id="cb274-2"><a href="survey-analysis.html#cb274-2" tabindex="-1"></a>ci2</span></code></pre></div>
<pre><code>##               2.5 %   97.5 %
## Population 149436.9 276783.8</code></pre>
<p>The reason we’re still not doing very well is that the regression model isn’t a good representation of
the situation. Take a look at the residual plot:</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-193"></span>
<img src="_main_files/figure-html/unnamed-chunk-193-1.png" alt="Residual plot" width="480" />
<p class="caption">
Figure 7.13: Residual plot
</p>
</div>
<p>This is a terrible looking residual plot, not least because the variance
so clearly isn’t constant: there is clear <strong>funnelling</strong> of the residuals.
The variance is increasing with population. That isn’t surprising in that
there is enormous variety in GDP per capita among the larger countries.</p>
<p>An improvement on the model is to have a residual variance which
scales with population <span class="math inline">\(x_i\)</span>:
<span class="math display">\[
   y_i = \beta x_i + \varepsilon_i\qquad \varepsilon_i\sim N(0,\sigma^2x_i)
\]</span>
We can estimate this ratio of the total of <span class="math inline">\(Y\)</span> to the total of <span class="math inline">\(X\)</span>
directly using the <code>svyratio()</code> function:</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="survey-analysis.html#cb276-1" tabindex="-1"></a>ss3 <span class="ot">&lt;-</span> <span class="fu">svyratio</span>(<span class="sc">~</span>GDP, <span class="sc">~</span>Population, <span class="at">design=</span>gdp.sample.des)</span>
<span id="cb276-2"><a href="survey-analysis.html#cb276-2" tabindex="-1"></a>ss3</span></code></pre></div>
<pre><code>## Ratio estimator: svyratio.survey.design2(~GDP, ~Population, design = gdp.sample.des)
## Ratios=
##     Population
## GDP   21.55548
## SEs=
##     Population
## GDP   3.809595</code></pre>
<p>The SE is slightly larger than in our first regression model, but we have more
confidence in this model due to its better treatment of the variance. The confidence
interval for the GDP per capita is now</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="survey-analysis.html#cb278-1" tabindex="-1"></a><span class="fu">confint</span>(ss3)</span></code></pre></div>
<pre><code>##                   2.5 %   97.5 %
## GDP/Population 14.08881 29.02215</code></pre>
<p>leading to the following confidence interval for the total GDP of the world in 2023:</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="survey-analysis.html#cb280-1" tabindex="-1"></a>ci3 <span class="ot">&lt;-</span> <span class="fu">confint</span>(ss3)<span class="sc">*</span>poptotal</span>
<span id="cb280-2"><a href="survey-analysis.html#cb280-2" tabindex="-1"></a>ci3</span></code></pre></div>
<pre><code>##                   2.5 %   97.5 %
## GDP/Population 107733.2 221924.2</code></pre>
Collecting all of these results together we see the improvement in our estimate
by using the additional information of population size alongside each country’s GDP.
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Method
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
RSE
</th>
<th style="text-align:left;">
CI
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Simple
</td>
<td style="text-align:right;">
81890
</td>
<td style="text-align:right;">
0.28
</td>
<td style="text-align:left;">
(36850,126931)
</td>
</tr>
<tr>
<td style="text-align:left;">
Regression
</td>
<td style="text-align:right;">
213110
</td>
<td style="text-align:right;">
0.15
</td>
<td style="text-align:left;">
(149437,276784)
</td>
</tr>
<tr>
<td style="text-align:left;">
Ratio
</td>
<td style="text-align:right;">
164829
</td>
<td style="text-align:right;">
0.18
</td>
<td style="text-align:left;">
(107733,221924)
</td>
</tr>
</tbody>
</table>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sample-designs-in-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="weight-adjustments.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf", "_main.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
