<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8 Weight adjustments | STAT395: Sampling</title>
  <meta name="description" content="Sampling notes." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="8 Weight adjustments | STAT395: Sampling" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Sampling notes." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8 Weight adjustments | STAT395: Sampling" />
  
  <meta name="twitter:description" content="Sampling notes." />
  

<meta name="author" content="Richard Arnold et al." />


<meta name="date" content="2026-04-27" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="survey-analysis.html"/>
<link rel="next" href="imputation.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">STAT395: Sampling</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#lecture-plan"><i class="fa fa-check"></i><b>1.1</b> Lecture Plan</a>
<ul>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#week-1-the-survey-process"><i class="fa fa-check"></i>Week 1 – The Survey Process</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#week-2-sampling"><i class="fa fa-check"></i>Week 2 – Sampling</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#week-3---inference-with-the-r-survey-package"><i class="fa fa-check"></i>Week 3 - Inference with the R survey package</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#week-4-non-response-and-complex-designs"><i class="fa fa-check"></i>Week 4 – Non-response and complex designs</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#assignment-4-10-due-end-of-week-12-covers-material-from-weeks-9-11"><i class="fa fa-check"></i>Assignment 4 (10%) [due end of Week 12: covers material from Weeks 9-11]</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html#test-2-25-assessment-period-1.5-hours-closed-book"><i class="fa fa-check"></i>Test 2 (25%) [assessment period] [1.5 hours, closed book]</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#recommended-reading"><i class="fa fa-check"></i><b>1.2</b> Recommended reading</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#r-packages"><i class="fa fa-check"></i><b>1.3</b> R Packages</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="sampling.html"><a href="sampling.html"><i class="fa fa-check"></i><b>2</b> Sampling</a>
<ul>
<li class="chapter" data-level="2.1" data-path="sampling.html"><a href="sampling.html#random-numbers"><i class="fa fa-check"></i><b>2.1</b> Random numbers</a></li>
<li class="chapter" data-level="2.2" data-path="sampling.html"><a href="sampling.html#sampling-from-categorical-random-variables"><i class="fa fa-check"></i><b>2.2</b> Sampling from categorical random variables</a></li>
<li class="chapter" data-level="2.3" data-path="sampling.html"><a href="sampling.html#sampling-from-discrete-numerical-random-variables"><i class="fa fa-check"></i><b>2.3</b> Sampling from discrete numerical random variables</a></li>
<li class="chapter" data-level="2.4" data-path="sampling.html"><a href="sampling.html#sampling-from-continuous-random-variables"><i class="fa fa-check"></i><b>2.4</b> Sampling from continuous random variables</a></li>
<li class="chapter" data-level="2.5" data-path="sampling.html"><a href="sampling.html#sampling-from-a-finite-collection"><i class="fa fa-check"></i><b>2.5</b> Sampling from a finite collection</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="sampling.html"><a href="sampling.html#sampling-without-replacement"><i class="fa fa-check"></i><b>2.5.1</b> Sampling without replacement</a></li>
<li class="chapter" data-level="2.5.2" data-path="sampling.html"><a href="sampling.html#sampling-with-replacement"><i class="fa fa-check"></i><b>2.5.2</b> Sampling with replacement</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="sample-surveys.html"><a href="sample-surveys.html"><i class="fa fa-check"></i><b>3</b> Sample Surveys</a>
<ul>
<li class="chapter" data-level="3.1" data-path="sample-surveys.html"><a href="sample-surveys.html#the-survey-process"><i class="fa fa-check"></i><b>3.1</b> The Survey Process</a></li>
<li class="chapter" data-level="3.2" data-path="sample-surveys.html"><a href="sample-surveys.html#populations-and-frames"><i class="fa fa-check"></i><b>3.2</b> Populations and Frames</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="sample-surveys.html"><a href="sample-surveys.html#what-is-a-sampling-frame"><i class="fa fa-check"></i><b>3.2.1</b> What is a sampling frame?</a></li>
<li class="chapter" data-level="3.2.2" data-path="sample-surveys.html"><a href="sample-surveys.html#what-is-a-good-sampling-frame"><i class="fa fa-check"></i><b>3.2.2</b> What is a <em>good</em> sampling frame?</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="sample-surveys.html"><a href="sample-surveys.html#approaches-to-sampling"><i class="fa fa-check"></i><b>3.3</b> Approaches to sampling</a></li>
<li class="chapter" data-level="3.4" data-path="sample-surveys.html"><a href="sample-surveys.html#example-datasets"><i class="fa fa-check"></i><b>3.4</b> Example datasets</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="sample-surveys.html"><a href="sample-surveys.html#api"><i class="fa fa-check"></i><b>3.4.1</b> API</a></li>
<li class="chapter" data-level="3.4.2" data-path="sample-surveys.html"><a href="sample-surveys.html#from-the-dplyr-package"><i class="fa fa-check"></i><b>3.4.2</b> From the dplyr package</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="statistical-inference.html"><a href="statistical-inference.html"><i class="fa fa-check"></i><b>4</b> Statistical Inference</a>
<ul>
<li class="chapter" data-level="4.1" data-path="statistical-inference.html"><a href="statistical-inference.html#inference-in-infinite-populations"><i class="fa fa-check"></i><b>4.1</b> Inference in infinite populations</a></li>
<li class="chapter" data-level="4.2" data-path="statistical-inference.html"><a href="statistical-inference.html#inference-in-finite-populations"><i class="fa fa-check"></i><b>4.2</b> Inference in finite populations</a></li>
<li class="chapter" data-level="4.3" data-path="statistical-inference.html"><a href="statistical-inference.html#the-survey-inference-process"><i class="fa fa-check"></i><b>4.3</b> The survey inference process</a></li>
<li class="chapter" data-level="4.4" data-path="statistical-inference.html"><a href="statistical-inference.html#example"><i class="fa fa-check"></i><b>4.4</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="sample-designs.html"><a href="sample-designs.html"><i class="fa fa-check"></i><b>5</b> Sample Designs</a>
<ul>
<li class="chapter" data-level="5.1" data-path="sample-designs.html"><a href="sample-designs.html#census"><i class="fa fa-check"></i><b>5.1</b> Census</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations"><i class="fa fa-check"></i>Design considerations</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="sample-designs.html"><a href="sample-designs.html#simple-random-sampling-without-replacement-srswor"><i class="fa fa-check"></i><b>5.2</b> Simple Random Sampling Without Replacement (SRSWOR)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-1"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-1"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="sample-designs.html"><a href="sample-designs.html#simple-random-sampling-with-replacement-srswr"><i class="fa fa-check"></i><b>5.3</b> Simple Random Sampling With Replacement (SRSWR)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-2"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-2"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="sample-designs.html"><a href="sample-designs.html#probability-proportion-to-size-sampling-ppswr"><i class="fa fa-check"></i><b>5.4</b> Probability proportion to size Sampling (PPSWR)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-3"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-3"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="sample-designs.html"><a href="sample-designs.html#linear-systematic-random-sample-lsrs"><i class="fa fa-check"></i><b>5.5</b> Linear Systematic Random Sample (LSRS)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-4"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-4"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="sample-designs.html"><a href="sample-designs.html#stratified-simple-random-sample-stsrs"><i class="fa fa-check"></i><b>5.6</b> Stratified Simple Random Sample (STSRS)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-5"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-5"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="sample-designs.html"><a href="sample-designs.html#one-stage-cluster-sampling-1sc"><i class="fa fa-check"></i><b>5.7</b> One stage cluster sampling (1SC)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-6"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-6"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="sample-designs.html"><a href="sample-designs.html#two-stage-cluster-sampling-2sc"><i class="fa fa-check"></i><b>5.8</b> Two stage cluster sampling (2SC)</a>
<ul>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#design-considerations-7"><i class="fa fa-check"></i>Design considerations</a></li>
<li class="chapter" data-level="" data-path="sample-designs.html"><a href="sample-designs.html#example-7"><i class="fa fa-check"></i>Example</a></li>
</ul></li>
<li class="chapter" data-level="5.9" data-path="sample-designs.html"><a href="sample-designs.html#complex-multistage-designs"><i class="fa fa-check"></i><b>5.9</b> Complex multistage designs</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html"><i class="fa fa-check"></i><b>6</b> Sample Designs in R</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#census-1"><i class="fa fa-check"></i><b>6.1</b> Census</a></li>
<li class="chapter" data-level="6.2" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#simple-random-sample-without-replacement-srswor"><i class="fa fa-check"></i><b>6.2</b> Simple Random Sample WithOut Replacement (SRSWOR)</a></li>
<li class="chapter" data-level="6.3" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#probability-proportional-to-size-with-replacement-ppswr"><i class="fa fa-check"></i><b>6.3</b> Probability Proportional to Size With Replacement (PPSWR)</a></li>
<li class="chapter" data-level="6.4" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#stratified-sample"><i class="fa fa-check"></i><b>6.4</b> Stratified Sample</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#design-effect"><i class="fa fa-check"></i><b>6.4.1</b> Design Effect</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#one-stage-cluster-design-1sc"><i class="fa fa-check"></i><b>6.5</b> One stage cluster design (1SC)</a></li>
<li class="chapter" data-level="6.6" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#two-stage-cluster-design-2sc"><i class="fa fa-check"></i><b>6.6</b> Two stage cluster design (2SC)</a></li>
<li class="chapter" data-level="6.7" data-path="sample-designs-in-r.html"><a href="sample-designs-in-r.html#stratified-two-stage-cluster-design"><i class="fa fa-check"></i><b>6.7</b> Stratified two stage cluster design</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="survey-analysis.html"><a href="survey-analysis.html"><i class="fa fa-check"></i><b>7</b> Survey Analysis</a>
<ul>
<li class="chapter" data-level="7.1" data-path="survey-analysis.html"><a href="survey-analysis.html#continous-variables"><i class="fa fa-check"></i><b>7.1</b> Continous variables</a>
<ul>
<li class="chapter" data-level="" data-path="survey-analysis.html"><a href="survey-analysis.html#display"><i class="fa fa-check"></i>Display</a></li>
<li class="chapter" data-level="" data-path="survey-analysis.html"><a href="survey-analysis.html#estimation"><i class="fa fa-check"></i>Estimation</a></li>
<li class="chapter" data-level="7.1.1" data-path="survey-analysis.html"><a href="survey-analysis.html#relative-sampling-errors-rses"><i class="fa fa-check"></i><b>7.1.1</b> Relative Sampling Errors (RSEs)</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="survey-analysis.html"><a href="survey-analysis.html#categorical-variables"><i class="fa fa-check"></i><b>7.2</b> Categorical Variables</a></li>
<li class="chapter" data-level="7.3" data-path="survey-analysis.html"><a href="survey-analysis.html#ratio-estimation"><i class="fa fa-check"></i><b>7.3</b> Ratio estimation</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="weight-adjustments.html"><a href="weight-adjustments.html"><i class="fa fa-check"></i><b>8</b> Weight adjustments</a>
<ul>
<li class="chapter" data-level="8.1" data-path="weight-adjustments.html"><a href="weight-adjustments.html#weight-calibration"><i class="fa fa-check"></i><b>8.1</b> Weight Calibration</a>
<ul>
<li class="chapter" data-level="" data-path="weight-adjustments.html"><a href="weight-adjustments.html#poststratfication-as-a-treatment-for-non-response"><i class="fa fa-check"></i>Poststratfication as a treatment for non-response</a></li>
<li class="chapter" data-level="" data-path="weight-adjustments.html"><a href="weight-adjustments.html#raking"><i class="fa fa-check"></i>Raking</a></li>
<li class="chapter" data-level="" data-path="weight-adjustments.html"><a href="weight-adjustments.html#another-example"><i class="fa fa-check"></i>Another example</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="weight-adjustments.html"><a href="weight-adjustments.html#replicate-weights"><i class="fa fa-check"></i><b>8.2</b> Replicate weights</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="imputation.html"><a href="imputation.html"><i class="fa fa-check"></i><b>9</b> Imputation</a></li>
<li class="chapter" data-level="10" data-path="package-mice.html"><a href="package-mice.html"><i class="fa fa-check"></i><b>10</b> Package mice</a></li>
<li class="chapter" data-level="11" data-path="designing-surveys.html"><a href="designing-surveys.html"><i class="fa fa-check"></i><b>11</b> Designing Surveys</a>
<ul>
<li class="chapter" data-level="11.1" data-path="designing-surveys.html"><a href="designing-surveys.html#another-interpretation-of-the-deff"><i class="fa fa-check"></i><b>11.1</b> Another interpretation of the Deff</a></li>
<li class="chapter" data-level="11.2" data-path="designing-surveys.html"><a href="designing-surveys.html#computing-the-required-sample-size"><i class="fa fa-check"></i><b>11.2</b> Computing the Required Sample Size</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="appendix"><span><b> </b></span></li>
<li class="chapter" data-level="A" data-path="placeholder-appendix.html"><a href="placeholder-appendix.html"><i class="fa fa-check"></i><b>A</b> Placeholder Appendix</a></li>
<li class="divider"></li>
<li>Lecture notes</li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">STAT395: Sampling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="weight-adjustments" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">8</span> Weight adjustments<a href="weight-adjustments.html#weight-adjustments" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<!--- For HTML Only --- Equivalent code for .pdf must be included in preamble.tex -->
<p><span class="math inline">\(\DeclareMathOperator*{\argmin}{argmin}\)</span>
<span class="math inline">\(\newcommand{\var}{\mathrm{Var}}\)</span>
<span class="math inline">\(\newcommand{\bfa}[2]{{\rm\bf #1}[#2]}\)</span>
<span class="math inline">\(\newcommand{\rma}[2]{{\rm     #1}[#2]}\)</span>
<span class="math inline">\(\newcommand{\estm}{\widehat}\)</span></p>
<div id="weight-calibration" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Weight Calibration<a href="weight-adjustments.html#weight-calibration" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>At the end of a survey we may find ourselves in the undesirable situation that</p>
<ul>
<li><strong>Purely by chance</strong>, the sample is somewhat unbalanced: e.g. by chance we may have
selected many more males than females, or more large households than small ones, or</li>
<li>We may have had <strong>unit nonresponse</strong> - i.e. there may be selected units from
which we have collected no data. In the case of human subjects this may have
been from a failure to contact the selected person, or the refusal of the
person to answer our questions.</li>
</ul>
<p>In both cases we are in the situation that our sample, even when weighted, is
not a good representation of the population from which it is drawn.</p>
<p>For example consider the SURF dataset, which is a synthetic sample of 200 individuals
between the ages of 15 and 45. The first 10 rows are shown below.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Personid
</th>
<th style="text-align:left;">
Gender
</th>
<th style="text-align:left;">
Qualification
</th>
<th style="text-align:right;">
Age
</th>
<th style="text-align:right;">
Hours
</th>
<th style="text-align:right;">
Income
</th>
<th style="text-align:left;">
Marital
</th>
<th style="text-align:left;">
Ethnicity
</th>
<th style="text-align:left;">
AgeGrp
</th>
<th style="text-align:right;">
bigN
</th>
<th style="text-align:right;">
weight
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:left;">
school
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
87
</td>
<td style="text-align:left;">
never
</td>
<td style="text-align:left;">
European
</td>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:right;">
1972719
</td>
<td style="text-align:right;">
9863.595
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:left;">
vocational
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
42
</td>
<td style="text-align:right;">
596
</td>
<td style="text-align:left;">
married
</td>
<td style="text-align:left;">
European
</td>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:right;">
1972719
</td>
<td style="text-align:right;">
9863.595
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:left;">
none
</td>
<td style="text-align:right;">
38
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
497
</td>
<td style="text-align:left;">
married
</td>
<td style="text-align:left;">
Maori
</td>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:right;">
1972719
</td>
<td style="text-align:right;">
9863.595
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:left;">
vocational
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
299
</td>
<td style="text-align:left;">
never
</td>
<td style="text-align:left;">
European
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
1972719
</td>
<td style="text-align:right;">
9863.595
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:left;">
school
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
301
</td>
<td style="text-align:left;">
married
</td>
<td style="text-align:left;">
European
</td>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:right;">
1972719
</td>
<td style="text-align:right;">
9863.595
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:left;">
degree
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
1614
</td>
<td style="text-align:left;">
married
</td>
<td style="text-align:left;">
European
</td>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:right;">
1972719
</td>
<td style="text-align:right;">
9863.595
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:left;">
none
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
201
</td>
<td style="text-align:left;">
other
</td>
<td style="text-align:left;">
European
</td>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:right;">
1972719
</td>
<td style="text-align:right;">
9863.595
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:left;">
degree
</td>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
934
</td>
<td style="text-align:left;">
previously
</td>
<td style="text-align:left;">
European
</td>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:right;">
1972719
</td>
<td style="text-align:right;">
9863.595
</td>
</tr>
<tr>
<td style="text-align:right;">
9
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:left;">
vocational
</td>
<td style="text-align:right;">
38
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
624
</td>
<td style="text-align:left;">
married
</td>
<td style="text-align:left;">
European
</td>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:right;">
1972719
</td>
<td style="text-align:right;">
9863.595
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:left;">
school
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
533
</td>
<td style="text-align:left;">
previously
</td>
<td style="text-align:left;">
European
</td>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:right;">
1972719
</td>
<td style="text-align:right;">
9863.595
</td>
</tr>
</tbody>
</table>
<p>The dataset contains a mixture of numerical and categorical variables, all with very
self explanatory names (except note that <code>Income</code> and <code>Hours</code> are weekly quantities,
and also that the income values are somewhat old!). We’ll treat it as a SRSWOR from
the New Zealand population between the ages of 15 and 45.</p>
<p>The total population in this age range is <span class="math inline">\(N=1.972719\times 10^{6}\)</span>, the sample size is <span class="math inline">\(n=200\)</span>,
and so the weight of each sampled individual is
<span class="math display">\[
   w = \frac{N}{n} = {1.972719\times 10^{6}}{200} = 9863.6
\]</span>
Let’s specify this simple random sampling design to R:</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="weight-adjustments.html#cb277-1" tabindex="-1"></a>surf.des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id=</span><span class="sc">~</span><span class="dv">1</span>, <span class="at">fpc=</span><span class="sc">~</span>bigN, <span class="at">data=</span>surf)</span></code></pre></div>
<p>and then estimate the mean income:</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="weight-adjustments.html#cb278-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Income, <span class="at">design=</span>surf.des)</span></code></pre></div>
<pre><code>##          mean     SE
## Income 575.36 24.508</code></pre>
<p>We should note that the mean income differs considerably between males and females.</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="weight-adjustments.html#cb280-1" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>Income, <span class="at">by=</span><span class="sc">~</span>Gender, <span class="at">design=</span>surf.des, svymean)</span></code></pre></div>
<pre><code>##        Gender   Income       se
## male     male 732.8172 37.02642
## female female 438.5047 26.16272</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-201-1.png" alt="" width="672" /></p>
Let’s also note the distribution of the population by age and sex, as measured
by the most recent census:
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
AgeGrp
</th>
<th style="text-align:right;">
male
</th>
<th style="text-align:right;">
female
</th>
<th style="text-align:right;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:right;">
324888
</td>
<td style="text-align:right;">
310032
</td>
<td style="text-align:right;">
634920
</td>
</tr>
<tr>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
337845
</td>
<td style="text-align:right;">
340668
</td>
<td style="text-align:right;">
678513
</td>
</tr>
<tr>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:right;">
321358
</td>
<td style="text-align:right;">
337928
</td>
<td style="text-align:right;">
659286
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:right;">
984091
</td>
<td style="text-align:right;">
988628
</td>
<td style="text-align:right;">
1972719
</td>
</tr>
</tbody>
</table>
Or we can express these counts as percentages:
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
AgeGrp
</th>
<th style="text-align:left;">
male
</th>
<th style="text-align:left;">
female
</th>
<th style="text-align:left;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:left;">
16.5%
</td>
<td style="text-align:left;">
15.7%
</td>
<td style="text-align:left;">
32.2%
</td>
</tr>
<tr>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:left;">
17.1%
</td>
<td style="text-align:left;">
17.3%
</td>
<td style="text-align:left;">
34.4%
</td>
</tr>
<tr>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:left;">
16.3%
</td>
<td style="text-align:left;">
17.1%
</td>
<td style="text-align:left;">
33.4%
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
49.9%
</td>
<td style="text-align:left;">
50.1%
</td>
<td style="text-align:left;">
100.0%
</td>
</tr>
</tbody>
</table>
<p>The proportions of males and females in the population are roughly equal in the population,
but in the sample they’re not quite equal:</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="weight-adjustments.html#cb282-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Gender, <span class="at">design=</span>surf.des)</span></code></pre></div>
<pre><code>##               mean     SE
## Gendermale   0.465 0.0354
## Genderfemale 0.535 0.0354</code></pre>
<p>This has been caused by our having, by chance, sampled slightly more females than males.</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="weight-adjustments.html#cb284-1" tabindex="-1"></a><span class="fu">table</span>(surf<span class="sc">$</span>Gender)</span></code></pre></div>
<pre><code>## 
##   male female 
##     93    107</code></pre>
<p>The consequence of this is that our estimate of the population mean income is
and underestimate, due to females earning less than males, and their being
slightly overrepresented in the sample.</p>
<p>One obvious solution to this situation is to slightly upweight the males in the sample, and downweight
the females, to take care of the imbalance. Of course we only <strong>know</strong> about the
imbalance because we have the census counts which tell us that the proportions of
males and females are roughly equal: otherwise we’d have no idea that there might be a problem.</p>
<p>These external counts (external to the survey that is) are called <strong>population benchmarks</strong>,
and the weight adjustment that makes the weights match the benchmarks is called
<strong>poststratification</strong>. It’s ‘post-’ here because we’re making the stratification
(breaking into groups) <strong>after</strong> the survey has taken place. Breaking the sample into
groups <strong>beforehand</strong>, and taking separate samples within each group is called stratified
sampling. But that is only possible if we know the group membership of sample members before
we sample them - i.e. if the group membership information is available on the frame.</p>
<p>We have <span class="math inline">\(n=200\)</span> individuals in a SRSWOR drawn from a population
of size <span class="math inline">\(N=1.972719\times 10^{6}\)</span>, with weights <span class="math inline">\(w=1.972719\times 10^{6}/200=9863.6\)</span>. These
correctly add up to the population total
<span class="math display">\[
   n \times w = n \times \frac{N}{n} = 200\times 9863.6 = 1.972719\times 10^{6}
\]</span>
What we want is different weights for the males and females, so that they separately
add up to the total numbers of males <span class="math inline">\(N_1=9.84091\times 10^{5}\)</span> and the total
numbers of females <span class="math inline">\(N_2=9.88628\times 10^{5}\)</span> in the population. We can achieve this
by computing new post-stratified weights using the known benchmarks <span class="math inline">\(N_h\)</span> and sample
sizes <span class="math inline">\(n_h\)</span> in each of the post-strata, and computing new weights
<span class="math display">\[
   w_h = \frac{N_h}{n_h}
\]</span>
i.e. these are the weights we’d have used if we had actually carried out a
stratified sample in the first place.</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Gender
</th>
<th style="text-align:right;">
SampWeight
</th>
<th style="text-align:right;">
nh
</th>
<th style="text-align:right;">
Nh
</th>
<th style="text-align:right;">
PostStratWeight
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
9863.595
</td>
<td style="text-align:right;">
93
</td>
<td style="text-align:right;">
984091
</td>
<td style="text-align:right;">
10581.624
</td>
</tr>
<tr>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
9863.595
</td>
<td style="text-align:right;">
107
</td>
<td style="text-align:right;">
988628
</td>
<td style="text-align:right;">
9239.514
</td>
</tr>
</tbody>
</table>
<p>These new weights are now appropriately higher for males and lower for females.</p>
In R we can modify the weights in the design object using the <code>postStratify()</code> function.
We first need to create a data frame storing the benchmarks:
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Gender
</th>
<th style="text-align:right;">
Nh
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
984091
</td>
</tr>
<tr>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
988628
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb286-1"><a href="weight-adjustments.html#cb286-1" tabindex="-1"></a>surf.des.ps <span class="ot">&lt;-</span> <span class="fu">postStratify</span>(surf.des, <span class="at">strata=</span><span class="sc">~</span>Gender, <span class="at">population=</span>Gender.benchmarks)</span></code></pre></div>
<p>The orignal estimate of the proportions of males and females</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="weight-adjustments.html#cb287-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Gender, <span class="at">design=</span>surf.des)</span></code></pre></div>
<pre><code>##               mean     SE
## Gendermale   0.465 0.0354
## Genderfemale 0.535 0.0354</code></pre>
<p>has been modified to</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="weight-adjustments.html#cb289-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Gender, <span class="at">design=</span>surf.des.ps)</span></code></pre></div>
<pre><code>##                 mean SE
## Gendermale   0.49885  0
## Genderfemale 0.50115  0</code></pre>
<p>Notice that the Standard Errors here are zero: these proportions are no longer
estimates, they have been <strong>imposed</strong> by our benchmarks.</p>
<p>Then we can compare the orginal estimate of mean income</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="weight-adjustments.html#cb291-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Income, surf.des)</span></code></pre></div>
<pre><code>##          mean     SE
## Income 575.36 24.508</code></pre>
<p>with the post-stratified estimate</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="weight-adjustments.html#cb293-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Income, surf.des.ps)</span></code></pre></div>
<pre><code>##          mean     SE
## Income 585.32 22.651</code></pre>
<p>The estimate has been increased slightly as expected. Also note that
the Standard Error has been reduced: this is often the case with
post-stratified estimates: post-stratification makes the properties
of different samples differ less than they otherwise would, and thereby
reduces our overall uncertainty.</p>
<div id="poststratfication-as-a-treatment-for-non-response" class="section level3 unnumbered hasAnchor">
<h3>Poststratfication as a treatment for non-response<a href="weight-adjustments.html#poststratfication-as-a-treatment-for-non-response" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Non-response can make the small chance differences in the previous section even worse.</p>
<p>In population surveys males and young people tend to have the lowest response rates.
So let’s see what happens to our mean income estimate if we take our sample of 200 individuals
and filter out 20% of the male respondents:</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="weight-adjustments.html#cb295-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">234</span>)</span>
<span id="cb295-2"><a href="weight-adjustments.html#cb295-2" tabindex="-1"></a>surf.nonresp <span class="ot">&lt;-</span> surf</span>
<span id="cb295-3"><a href="weight-adjustments.html#cb295-3" tabindex="-1"></a>surf.nonresp<span class="sc">$</span>Responds <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="fu">nrow</span>(surf),<span class="dv">1</span>,<span class="at">prob=</span><span class="fu">ifelse</span>(surf<span class="sc">$</span>Gender<span class="sc">==</span><span class="st">&quot;male&quot;</span>,<span class="fl">0.8</span>,<span class="fl">1.0</span>))</span>
<span id="cb295-4"><a href="weight-adjustments.html#cb295-4" tabindex="-1"></a>surf.nonresp <span class="ot">&lt;-</span> surf.nonresp[surf.nonresp<span class="sc">$</span>Responds<span class="sc">==</span><span class="dv">1</span>,]</span>
<span id="cb295-5"><a href="weight-adjustments.html#cb295-5" tabindex="-1"></a>surf.nonresp<span class="sc">$</span>weight <span class="ot">&lt;-</span> bigN<span class="sc">/</span><span class="fu">nrow</span>(surf.nonresp)</span>
<span id="cb295-6"><a href="weight-adjustments.html#cb295-6" tabindex="-1"></a><span class="fu">table</span>(surf.nonresp<span class="sc">$</span>Gender)</span></code></pre></div>
<pre><code>## 
##   male female 
##     75    107</code></pre>
<p>We’ve now got a lot fewer males than females. Let’s see what this does to the
simple estimate of the population mean income:</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="weight-adjustments.html#cb297-1" tabindex="-1"></a>surf.nonresp.des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id=</span><span class="sc">~</span><span class="dv">1</span>, <span class="at">fpc=</span><span class="sc">~</span>bigN, <span class="at">data=</span>surf.nonresp)</span>
<span id="cb297-2"><a href="weight-adjustments.html#cb297-2" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Income, <span class="at">design=</span>surf.nonresp.des)</span></code></pre></div>
<pre><code>##          mean     SE
## Income 555.99 24.501</code></pre>
<p>The introduction of the non-response has led to a reduction in our original estimate
from 575.36 to 555.99.</p>
<p>Post-stratifying however</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="weight-adjustments.html#cb299-1" tabindex="-1"></a>surf.nonresp.des.ps <span class="ot">&lt;-</span> <span class="fu">postStratify</span>(surf.nonresp.des, <span class="at">strata=</span><span class="sc">~</span>Gender, </span>
<span id="cb299-2"><a href="weight-adjustments.html#cb299-2" tabindex="-1"></a>                                    <span class="at">population=</span>Gender.benchmarks)</span></code></pre></div>
<p>leads to a dramatically improved estimate</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb300-1"><a href="weight-adjustments.html#cb300-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Income, <span class="at">design=</span>surf.nonresp.des.ps)</span></code></pre></div>
<pre><code>##          mean     SE
## Income 580.73 23.354</code></pre>
<p>We know more than just the distribution of the population over Gender, we also know it over the
three age groups. So we can post-stratify by these variables too.</p>
We can store the AgeGrp/Gender benchmarks in a data frame <code>AgeGrp.Gender.benchmarks</code>:
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
AgeGrp
</th>
<th style="text-align:left;">
Gender
</th>
<th style="text-align:right;">
count
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
310032
</td>
</tr>
<tr>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
324888
</td>
</tr>
<tr>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
340668
</td>
</tr>
<tr>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
337845
</td>
</tr>
<tr>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
337928
</td>
</tr>
<tr>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
321358
</td>
</tr>
</tbody>
</table>
<p>and then post-stratify</p>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb302-1"><a href="weight-adjustments.html#cb302-1" tabindex="-1"></a>surf.nonresp.des.ps2 <span class="ot">&lt;-</span> <span class="fu">postStratify</span>(surf.nonresp.des, <span class="at">strata=</span><span class="sc">~</span>AgeGrp<span class="sc">*</span>Gender, </span>
<span id="cb302-2"><a href="weight-adjustments.html#cb302-2" tabindex="-1"></a>                                     <span class="at">population=</span>AgeGrp.Gender.benchmarks)</span>
<span id="cb302-3"><a href="weight-adjustments.html#cb302-3" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Income, <span class="at">design=</span>surf.nonresp.des.ps2)</span></code></pre></div>
<pre><code>##          mean    SE
## Income 580.26 22.66</code></pre>
<p>And this is estimate is going to be even better than before.</p>
<p>However where should we stop? Should we post-stratify by as many variables as we
possibly can?</p>
<p>In general we need to ensure that we have enough individuals in the sample
in every cross-classified cell (in this case AgeGroup by Gender) to be able to
recalculate the weight. Empty cells are going to cause us a problem,
since we’ll be discarding the population weight associated
with people of that type in the population who happen not to have turned up in the sample.</p>
<p>In population surveys run by Statistics NZ we’ll often see post-stratification by age
(in 5 year bands), sex, ethnicity (in large amalgamated groups), and large regions.</p>
<div id="a-warning" class="section level4 hasAnchor" number="8.1.0.1">
<h4><span class="header-section-number">8.1.0.1</span> A warning<a href="weight-adjustments.html#a-warning" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Post-stratification is often used to modify weights in the presence of non-response.
The idea is that in each post-stratum the people who respond represent well the people
who don’t respond.</p>
<p>This is a very big and untestable assumption.</p>
<p>The reasons that people do or don’t respond are complicated. The greatest risk to a
survey is that the non-respondents differ from the respondents on the characteristic
of interest.</p>
<p>For example if we’re doing a survey of incomes, perhaps all the high income
people don’t respond - there’s no way to adjust for this, because the only way to know about
income is to have them answer the survey. So we’ll never find out about high income people,
nor find out what their incomes actually are.</p>
<p>Post-stratifying the income survey above by age and sex means that we’re assuming that
the respondents in each age-sex category are a simple random sample from all of the
sample members selected into the survey. We can cope with, and adjust for, differing response rates
<strong>between</strong> the post-strata, but we can never adjust for different likelihoods of response
<strong>within</strong> the post-strata.</p>
</div>
</div>
<div id="raking" class="section level3 unnumbered hasAnchor">
<h3>Raking<a href="weight-adjustments.html#raking" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We may not have full cross-classified benchmarks, for example we might know the
totals by AgeGrp and totals by Gender, but not totals by AgeGrp and Gender simultaneously.
In that case we can proceed iteratively: we post-stratify first by one variable, and
then by other. Each post-stratification on one variable messes up the post-stratification
on the other. But eventually the weights will converge to approximately match both sets
of benchmarks. This iteration is called <strong>raking</strong> (like raking a lawn one way, then other other),
or <strong>Iterative Proportional Fitting</strong>.</p>
R implements raking in with the <code>rake()</code> function. We need a separate set of benchmarks
for AgeGrp
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
AgeGrp
</th>
<th style="text-align:right;">
Nh
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:right;">
634920
</td>
</tr>
<tr>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
678513
</td>
</tr>
<tr>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:right;">
659286
</td>
</tr>
</tbody>
</table>
<p>and for Gender</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="weight-adjustments.html#cb304-1" tabindex="-1"></a>Gender.benchmarks <span class="sc">|&gt;</span> <span class="fu">kbl</span>() <span class="sc">|&gt;</span> <span class="fu">kable_styling</span>(<span class="at">full_width=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Gender
</th>
<th style="text-align:right;">
Nh
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
male
</td>
<td style="text-align:right;">
984091
</td>
</tr>
<tr>
<td style="text-align:left;">
female
</td>
<td style="text-align:right;">
988628
</td>
</tr>
</tbody>
</table>
<p>With these we can rake the design:</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="weight-adjustments.html#cb305-1" tabindex="-1"></a>surf.nonresp.des.rake <span class="ot">&lt;-</span> <span class="fu">rake</span>(surf.nonresp.des, </span>
<span id="cb305-2"><a href="weight-adjustments.html#cb305-2" tabindex="-1"></a>                              <span class="at">sample=</span><span class="fu">list</span>(<span class="sc">~</span>AgeGrp, <span class="sc">~</span>Gender), </span>
<span id="cb305-3"><a href="weight-adjustments.html#cb305-3" tabindex="-1"></a>                              <span class="at">population=</span><span class="fu">list</span>(AgeGrp.benchmarks, Gender.benchmarks))</span></code></pre></div>
<p>and then calculate our estimates</p>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="weight-adjustments.html#cb306-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>Income, <span class="at">design=</span>surf.nonresp.des.rake)</span></code></pre></div>
<pre><code>##          mean     SE
## Income 579.58 22.798</code></pre>
<p>We can compare estimated population totals with the Population benchmarks:</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="weight-adjustments.html#cb308-1" tabindex="-1"></a>nzpoptab <span class="sc">|&gt;</span> <span class="fu">kbl</span>() <span class="sc">|&gt;</span> <span class="fu">kable_styling</span>(<span class="at">full_width=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
AgeGrp
</th>
<th style="text-align:right;">
male
</th>
<th style="text-align:right;">
female
</th>
<th style="text-align:right;">
Total
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:right;">
324888
</td>
<td style="text-align:right;">
310032
</td>
<td style="text-align:right;">
634920
</td>
</tr>
<tr>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
337845
</td>
<td style="text-align:right;">
340668
</td>
<td style="text-align:right;">
678513
</td>
</tr>
<tr>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:right;">
321358
</td>
<td style="text-align:right;">
337928
</td>
<td style="text-align:right;">
659286
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:right;">
984091
</td>
<td style="text-align:right;">
988628
</td>
<td style="text-align:right;">
1972719
</td>
</tr>
</tbody>
</table>
<p>Estimated counts with no weight adjustments</p>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="weight-adjustments.html#cb309-1" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>Gender, <span class="at">by=</span><span class="sc">~</span>AgeGrp, <span class="at">FUN=</span>svytotal, <span class="at">design=</span>surf.nonresp.des) <span class="sc">|&gt;</span></span>
<span id="cb309-2"><a href="weight-adjustments.html#cb309-2" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">col.names=</span><span class="fu">c</span>(<span class="st">&quot;AgeGrp&quot;</span>,<span class="st">&quot;male&quot;</span>,<span class="st">&quot;female&quot;</span>,<span class="st">&quot;SE(male)&quot;</span>,<span class="st">&quot;SE(female)&quot;</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb309-3"><a href="weight-adjustments.html#cb309-3" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
AgeGrp
</th>
<th style="text-align:right;">
male
</th>
<th style="text-align:right;">
female
</th>
<th style="text-align:right;">
SE(male)
</th>
<th style="text-align:right;">
SE(female)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:right;">
270977.9
</td>
<td style="text-align:right;">
357690.8
</td>
<td style="text-align:right;">
50472.45
</td>
<td style="text-align:right;">
56491.70
</td>
</tr>
<tr>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
260138.8
</td>
<td style="text-align:right;">
346851.7
</td>
<td style="text-align:right;">
49609.94
</td>
<td style="text-align:right;">
55815.54
</td>
</tr>
<tr>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:right;">
281817.0
</td>
<td style="text-align:right;">
455242.8
</td>
<td style="text-align:right;">
51307.81
</td>
<td style="text-align:right;">
61776.48
</td>
</tr>
</tbody>
</table>
<p>Post-stratified by Gender</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="weight-adjustments.html#cb310-1" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>Gender, <span class="at">by=</span><span class="sc">~</span>AgeGrp, <span class="at">FUN=</span>svytotal, <span class="at">design=</span>surf.nonresp.des.ps)  <span class="sc">|&gt;</span></span>
<span id="cb310-2"><a href="weight-adjustments.html#cb310-2" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">col.names=</span><span class="fu">c</span>(<span class="st">&quot;AgeGrp&quot;</span>,<span class="st">&quot;male&quot;</span>,<span class="st">&quot;female&quot;</span>,<span class="st">&quot;SE(male)&quot;</span>,<span class="st">&quot;SE(female)&quot;</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb310-3"><a href="weight-adjustments.html#cb310-3" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
AgeGrp
</th>
<th style="text-align:right;">
male
</th>
<th style="text-align:right;">
female
</th>
<th style="text-align:right;">
SE(male)
</th>
<th style="text-align:right;">
SE(female)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:right;">
328030.3
</td>
<td style="text-align:right;">
304904.0
</td>
<td style="text-align:right;">
53712.42
</td>
<td style="text-align:right;">
44259.49
</td>
</tr>
<tr>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
314909.1
</td>
<td style="text-align:right;">
295664.4
</td>
<td style="text-align:right;">
53150.88
</td>
<td style="text-align:right;">
43877.23
</td>
</tr>
<tr>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:right;">
341151.5
</td>
<td style="text-align:right;">
388059.6
</td>
<td style="text-align:right;">
54225.61
</td>
<td style="text-align:right;">
46796.67
</td>
</tr>
</tbody>
</table>
<p>Post-stratified by Age Group cross classified with Gender: exact match to benchmarks</p>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="weight-adjustments.html#cb311-1" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>Gender, <span class="at">by=</span><span class="sc">~</span>AgeGrp, <span class="at">FUN=</span>svytotal, <span class="at">design=</span>surf.nonresp.des.ps2)  <span class="sc">|&gt;</span></span>
<span id="cb311-2"><a href="weight-adjustments.html#cb311-2" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">col.names=</span><span class="fu">c</span>(<span class="st">&quot;AgeGrp&quot;</span>,<span class="st">&quot;male&quot;</span>,<span class="st">&quot;female&quot;</span>,<span class="st">&quot;SE(male)&quot;</span>,<span class="st">&quot;SE(female)&quot;</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb311-3"><a href="weight-adjustments.html#cb311-3" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
AgeGrp
</th>
<th style="text-align:right;">
male
</th>
<th style="text-align:right;">
female
</th>
<th style="text-align:right;">
SE(male)
</th>
<th style="text-align:right;">
SE(female)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:right;">
324888
</td>
<td style="text-align:right;">
310032
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
337845
</td>
<td style="text-align:right;">
340668
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:right;">
321358
</td>
<td style="text-align:right;">
337928
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p>Post-stratified by raking to Age Group and Gender marginal totals: approximate
match to benchmarks</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb312-1"><a href="weight-adjustments.html#cb312-1" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>Gender, <span class="at">by=</span><span class="sc">~</span>AgeGrp, <span class="at">FUN=</span>svytotal, <span class="at">design=</span>surf.nonresp.des.rake)  <span class="sc">|&gt;</span></span>
<span id="cb312-2"><a href="weight-adjustments.html#cb312-2" tabindex="-1"></a>  <span class="fu">kbl</span>(<span class="at">col.names=</span><span class="fu">c</span>(<span class="st">&quot;AgeGrp&quot;</span>,<span class="st">&quot;male&quot;</span>,<span class="st">&quot;female&quot;</span>,<span class="st">&quot;SE(male)&quot;</span>,<span class="st">&quot;SE(female)&quot;</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb312-3"><a href="weight-adjustments.html#cb312-3" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
AgeGrp
</th>
<th style="text-align:right;">
male
</th>
<th style="text-align:right;">
female
</th>
<th style="text-align:right;">
SE(male)
</th>
<th style="text-align:right;">
SE(female)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:left;">
15-24
</td>
<td style="text-align:right;">
327978.3
</td>
<td style="text-align:right;">
306941.7
</td>
<td style="text-align:right;">
36276.56
</td>
<td style="text-align:right;">
36276.56
</td>
</tr>
<tr>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:left;">
25-34
</td>
<td style="text-align:right;">
348793.8
</td>
<td style="text-align:right;">
329719.2
</td>
<td style="text-align:right;">
38089.76
</td>
<td style="text-align:right;">
38089.76
</td>
</tr>
<tr>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:left;">
35-45
</td>
<td style="text-align:right;">
307318.9
</td>
<td style="text-align:right;">
351967.1
</td>
<td style="text-align:right;">
36046.49
</td>
<td style="text-align:right;">
36046.49
</td>
</tr>
</tbody>
</table>
Finally compare the estimates of mean income
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Method
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
SE
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
True
</td>
<td style="text-align:right;">
575.3600
</td>
<td style="text-align:right;">
0.00000
</td>
</tr>
<tr>
<td style="text-align:left;">
No adjustment
</td>
<td style="text-align:right;">
555.9945
</td>
<td style="text-align:right;">
24.50130
</td>
</tr>
<tr>
<td style="text-align:left;">
PS(Gender)
</td>
<td style="text-align:right;">
580.7311
</td>
<td style="text-align:right;">
23.35388
</td>
</tr>
<tr>
<td style="text-align:left;">
PS(AgeGrp*Gender)
</td>
<td style="text-align:right;">
580.2640
</td>
<td style="text-align:right;">
22.65980
</td>
</tr>
<tr>
<td style="text-align:left;">
Rake(Age+Gender)
</td>
<td style="text-align:right;">
579.5795
</td>
<td style="text-align:right;">
22.79842
</td>
</tr>
</tbody>
</table>
<p>The Standard Errors are all similar, though we do get a small reduction in SE
with post-stratification. However it is the reduction in the biasing
effect of non-response that is most striking.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-232"></span>
<img src="_main_files/figure-html/unnamed-chunk-232-1.png" alt="Estimates of mean income by adjustment method" width="480" />
<p class="caption">
Figure 8.1: Estimates of mean income by adjustment method
</p>
</div>
</div>
<div id="another-example" class="section level3 unnumbered hasAnchor">
<h3>Another example<a href="weight-adjustments.html#another-example" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the Academic Performance Indicator dataset we have full population information
on types of School (<code>stype</code>=Elementary/Middle/High) and whether or not they
met their year round performance indicators (<code>yr.rnd</code>=Yes/No). These counts
will be our benchmarks for post-stratification.</p>
The numbers of schools by type are in <code>stype.benchmnarks</code>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
stype
</th>
<th style="text-align:right;">
Freq
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Elementary
</td>
<td style="text-align:right;">
4397
</td>
</tr>
<tr>
<td style="text-align:left;">
Middle
</td>
<td style="text-align:right;">
1009
</td>
</tr>
<tr>
<td style="text-align:left;">
High
</td>
<td style="text-align:right;">
751
</td>
</tr>
</tbody>
</table>
The number of schools by achievement of year round objectives are in <code>yr.rnd.benchmarks</code>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
yr.rnd
</th>
<th style="text-align:right;">
Freq
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
874
</td>
</tr>
<tr>
<td style="text-align:left;">
Yes
</td>
<td style="text-align:right;">
5283
</td>
</tr>
</tbody>
</table>
and we also have these counts <strong>cross-classified</strong>, i.e. numbers of schools for
each combination of <code>stype</code> and <code>yr.rnd</code>:
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
stype
</th>
<th style="text-align:left;">
yr.rnd
</th>
<th style="text-align:right;">
Freq
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Elementary
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
791
</td>
</tr>
<tr>
<td style="text-align:left;">
Middle
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
60
</td>
</tr>
<tr>
<td style="text-align:left;">
High
</td>
<td style="text-align:left;">
No
</td>
<td style="text-align:right;">
23
</td>
</tr>
<tr>
<td style="text-align:left;">
Elementary
</td>
<td style="text-align:left;">
Yes
</td>
<td style="text-align:right;">
3606
</td>
</tr>
<tr>
<td style="text-align:left;">
Middle
</td>
<td style="text-align:left;">
Yes
</td>
<td style="text-align:right;">
949
</td>
</tr>
<tr>
<td style="text-align:left;">
High
</td>
<td style="text-align:left;">
Yes
</td>
<td style="text-align:right;">
728
</td>
</tr>
</tbody>
</table>
<p>Select a two stage cluster sample - and then make estimates of the mean school
size (<code>enroll</code>)</p>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb313-1"><a href="weight-adjustments.html#cb313-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">111</span>)</span>
<span id="cb313-2"><a href="weight-adjustments.html#cb313-2" tabindex="-1"></a>api2sc <span class="ot">&lt;-</span> apipopc <span class="sc">|&gt;</span> </span>
<span id="cb313-3"><a href="weight-adjustments.html#cb313-3" tabindex="-1"></a>  <span class="fu">select.2sc</span>(<span class="at">n=</span><span class="dv">40</span>, <span class="at">cfraction=</span><span class="fl">0.30</span>, <span class="at">mmin=</span><span class="dv">2</span>, <span class="at">clustervar=</span><span class="st">&quot;dnum&quot;</span>) </span>
<span id="cb313-4"><a href="weight-adjustments.html#cb313-4" tabindex="-1"></a>api2sc.des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">ids=</span><span class="sc">~</span>dnum<span class="sc">+</span>snum, <span class="at">fpc=</span><span class="sc">~</span>bigN1<span class="sc">+</span>bigN2, <span class="at">data=</span>api2sc) </span>
<span id="cb313-5"><a href="weight-adjustments.html#cb313-5" tabindex="-1"></a><span class="fu">table</span>(api2sc<span class="sc">$</span>stype)<span class="sc">/</span><span class="fu">nrow</span>(api2sc)</span></code></pre></div>
<pre><code>## 
## Elementary     Middle       High 
##  0.6224490  0.1428571  0.2346939</code></pre>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="weight-adjustments.html#cb315-1" tabindex="-1"></a><span class="fu">svytable</span>(<span class="sc">~</span>stype, <span class="at">design=</span>api2sc.des)</span></code></pre></div>
<pre><code>## stype
## Elementary     Middle       High 
##  2972.2159   589.3841   946.0500</code></pre>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="weight-adjustments.html#cb317-1" tabindex="-1"></a><span class="fu">svytable</span>(<span class="sc">~</span>stype, <span class="at">design=</span>api2sc.des)<span class="sc">/</span><span class="fu">sum</span>(api2sc<span class="sc">$</span>weight)</span></code></pre></div>
<pre><code>## stype
## Elementary     Middle       High 
##  0.6593715  0.1307520  0.2098765</code></pre>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb319-1"><a href="weight-adjustments.html#cb319-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>enroll, <span class="at">design=</span>api2sc.des)</span></code></pre></div>
<pre><code>##          mean     SE
## enroll 711.45 81.057</code></pre>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="weight-adjustments.html#cb321-1" tabindex="-1"></a><span class="fu">svyby</span>(<span class="sc">~</span>enroll, <span class="at">by=</span><span class="sc">~</span>stype, api2sc.des, svymean)</span></code></pre></div>
<pre><code>##                 stype    enroll        se
## Elementary Elementary  415.6678  46.44827
## Middle         Middle  834.1254 113.51448
## High             High 1564.3007 190.86274</code></pre>
<p>Poststratify by stype and reestimate</p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="weight-adjustments.html#cb323-1" tabindex="-1"></a>api2sc.des.ps <span class="ot">&lt;-</span> <span class="fu">postStratify</span>(api2sc.des, <span class="at">strata=</span><span class="sc">~</span>stype, <span class="at">population=</span>stype.benchmarks)</span>
<span id="cb323-2"><a href="weight-adjustments.html#cb323-2" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.des.ps)</span></code></pre></div>
<pre><code>##          mean     SE
## enroll 624.35 53.142</code></pre>
<p>Postratify by stype by yr.rnd and reestimate</p>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="weight-adjustments.html#cb325-1" tabindex="-1"></a>api2sc.des.ps2 <span class="ot">&lt;-</span> <span class="fu">postStratify</span>(api2sc.des, <span class="at">strata=</span><span class="sc">~</span>stype<span class="sc">+</span>yr.rnd, </span>
<span id="cb325-2"><a href="weight-adjustments.html#cb325-2" tabindex="-1"></a>                               <span class="at">population=</span>stype.yr.rnd.benchmarks)</span>
<span id="cb325-3"><a href="weight-adjustments.html#cb325-3" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.des.ps2)</span></code></pre></div>
<pre><code>##          mean     SE
## enroll 629.45 40.239</code></pre>
<p>Poststratify by stype + yr.rnd (i.e. we only have the marginals so we need to rake)
and reestimate</p>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb327-1"><a href="weight-adjustments.html#cb327-1" tabindex="-1"></a>api2sc.des.rake <span class="ot">&lt;-</span> <span class="fu">rake</span>(api2sc.des, </span>
<span id="cb327-2"><a href="weight-adjustments.html#cb327-2" tabindex="-1"></a>                        <span class="at">sample=</span><span class="fu">list</span>(<span class="sc">~</span>stype, <span class="sc">~</span>yr.rnd), </span>
<span id="cb327-3"><a href="weight-adjustments.html#cb327-3" tabindex="-1"></a>                        <span class="at">population=</span><span class="fu">list</span>(stype.benchmarks, yr.rnd.benchmarks))</span>
<span id="cb327-4"><a href="weight-adjustments.html#cb327-4" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.des.rake)</span></code></pre></div>
<pre><code>##          mean     SE
## enroll 632.04 46.705</code></pre>
Compare
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
SE
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Cenus
</td>
<td style="text-align:right;">
619.0469
</td>
<td style="text-align:right;">
0.00000
</td>
</tr>
<tr>
<td style="text-align:left;">
2SC
</td>
<td style="text-align:right;">
711.4530
</td>
<td style="text-align:right;">
81.05714
</td>
</tr>
<tr>
<td style="text-align:left;">
2SC+PS(stype)
</td>
<td style="text-align:right;">
624.3485
</td>
<td style="text-align:right;">
53.14154
</td>
</tr>
<tr>
<td style="text-align:left;">
2SC+PS(stype x yr.rnd)
</td>
<td style="text-align:right;">
629.4503
</td>
<td style="text-align:right;">
40.23927
</td>
</tr>
<tr>
<td style="text-align:left;">
2SC+Rake(stype+yr.rnd)
</td>
<td style="text-align:right;">
632.0372
</td>
<td style="text-align:right;">
46.70502
</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="replicate-weights" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> Replicate weights<a href="weight-adjustments.html#replicate-weights" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>For some weight adjustments we no longer have a reliable method of computing
the standard errors of our estimates. This can occur when we have very
complex designs. It can also be necessary when we don’t have access to the frame,
and therefore don’t have all the information we need to calculate standard errors.</p>
<p>In such circumstances we often create multiple sets of weights in addition to the
adjusted weights. These <strong>replicate weights</strong> are what are used to estimate the
standard errors, and they have the advantage that they can create standard errors
for a wider range of estimators than the usual means and totals.</p>
<p><strong>Jacknife</strong> weights are calculated by systematically deleting PSUs at the first
stage of selection, and then scaling the weights on the remaining rows so that they
still add up to the same total.</p>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="weight-adjustments.html#cb329-1" tabindex="-1"></a>api2sc.jkdes <span class="ot">&lt;-</span> <span class="fu">as.svrepdesign</span>(api2sc.des, <span class="at">type=</span><span class="st">&quot;JK1&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in as.svrepdesign.default(api2sc.des, type = &quot;JK1&quot;): Finite population
## corrections after first stage have been dropped</code></pre>
<p>There is an informative warning here: no fpc can apply at second stage of selection
(nor any subsequent stages).</p>
<p>Here are the first 3 rows and 8 columns: each row refers to a district <code>dnum</code>
and each column is a replicate.</p>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="weight-adjustments.html#cb331-1" tabindex="-1"></a>api2sc.jkdes<span class="sc">$</span>repweights<span class="sc">$</span>weights[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>]</span></code></pre></div>
<pre><code>##          [,1]     [,2]     [,3]     [,4]     [,5]     [,6]     [,7]     [,8]
## [1,] 0.000000 1.025641 1.025641 1.025641 1.025641 1.025641 1.025641 1.025641
## [2,] 1.025641 0.000000 1.025641 1.025641 1.025641 1.025641 1.025641 1.025641
## [3,] 1.025641 1.025641 0.000000 1.025641 1.025641 1.025641 1.025641 1.025641</code></pre>
<p>Replicate Weights are <span class="math inline">\(n/(n-1)=40/39=1.025641\)</span> - drops one of the 40 districts <code>dnum</code> out for
each replicate, setting all units in that district to zero.
These are scaling weights, and theyneed to be multiplied by the original sampling weight
to get the actual weights.</p>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="weight-adjustments.html#cb333-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>enroll, <span class="at">design=</span>api2sc.jkdes)</span></code></pre></div>
<pre><code>##          mean     SE
## enroll 711.45 82.848</code></pre>
<p>This gives us a better estimate of the SE.</p>
<p>If we are needing to post-stratify our weights to account for non-response, then
we need also to poststratify each set of replicate weights.</p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="weight-adjustments.html#cb335-1" tabindex="-1"></a>api2sc.jkdes.ps <span class="ot">&lt;-</span> <span class="fu">postStratify</span>(api2sc.jkdes, <span class="at">strata=</span><span class="sc">~</span>stype, <span class="at">population=</span>stype.benchmarks)</span>
<span id="cb335-2"><a href="weight-adjustments.html#cb335-2" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>enroll, <span class="at">design=</span>api2sc.jkdes.ps)</span></code></pre></div>
<pre><code>##          mean    SE
## enroll 624.35 60.61</code></pre>
<p>Here post-stratification gives us a strong reduction of the standard errors</p>
<p>Comparison</p>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="weight-adjustments.html#cb337-1" tabindex="-1"></a>ss <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb337-2"><a href="weight-adjustments.html#cb337-2" tabindex="-1"></a>  <span class="fu">c</span>(<span class="fu">mean</span>(apipopc<span class="sc">$</span>enroll), <span class="dv">0</span>),</span>
<span id="cb337-3"><a href="weight-adjustments.html#cb337-3" tabindex="-1"></a>  <span class="fu">ff</span>(<span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.des)), </span>
<span id="cb337-4"><a href="weight-adjustments.html#cb337-4" tabindex="-1"></a>  <span class="fu">ff</span>(<span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.des.ps)), </span>
<span id="cb337-5"><a href="weight-adjustments.html#cb337-5" tabindex="-1"></a>  <span class="fu">ff</span>(<span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.des.ps2)), </span>
<span id="cb337-6"><a href="weight-adjustments.html#cb337-6" tabindex="-1"></a>  <span class="fu">ff</span>(<span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.des.rake)),</span>
<span id="cb337-7"><a href="weight-adjustments.html#cb337-7" tabindex="-1"></a>  <span class="fu">ff</span>(<span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.jkdes)),</span>
<span id="cb337-8"><a href="weight-adjustments.html#cb337-8" tabindex="-1"></a>  <span class="fu">ff</span>(<span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.jkdes.ps))</span>
<span id="cb337-9"><a href="weight-adjustments.html#cb337-9" tabindex="-1"></a>  ) </span>
<span id="cb337-10"><a href="weight-adjustments.html#cb337-10" tabindex="-1"></a><span class="fu">dimnames</span>(ss) <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">&quot;Cenus&quot;</span>,<span class="st">&quot;2SC&quot;</span>,<span class="st">&quot;2SC+PS(stype)&quot;</span>,<span class="st">&quot;2SC+PS(stype x yr.rnd)&quot;</span>,<span class="st">&quot;2SC+Rake(stype+yr.rnd)&quot;</span>,</span>
<span id="cb337-11"><a href="weight-adjustments.html#cb337-11" tabindex="-1"></a>                       <span class="st">&quot;JK1&quot;</span>,<span class="st">&quot;JK1+PS(stype)&quot;</span>),</span>
<span id="cb337-12"><a href="weight-adjustments.html#cb337-12" tabindex="-1"></a>                     <span class="fu">c</span>(<span class="st">&quot;Estimate&quot;</span>,<span class="st">&quot;SE&quot;</span>))</span>
<span id="cb337-13"><a href="weight-adjustments.html#cb337-13" tabindex="-1"></a>ss <span class="sc">|&gt;</span> <span class="fu">kbl</span>() <span class="sc">|&gt;</span> <span class="fu">kable_styling</span>(<span class="at">full_width=</span><span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
SE
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Cenus
</td>
<td style="text-align:right;">
619.0469
</td>
<td style="text-align:right;">
0.00000
</td>
</tr>
<tr>
<td style="text-align:left;">
2SC
</td>
<td style="text-align:right;">
711.4530
</td>
<td style="text-align:right;">
81.05714
</td>
</tr>
<tr>
<td style="text-align:left;">
2SC+PS(stype)
</td>
<td style="text-align:right;">
624.3485
</td>
<td style="text-align:right;">
53.14154
</td>
</tr>
<tr>
<td style="text-align:left;">
2SC+PS(stype x yr.rnd)
</td>
<td style="text-align:right;">
629.4503
</td>
<td style="text-align:right;">
40.23927
</td>
</tr>
<tr>
<td style="text-align:left;">
2SC+Rake(stype+yr.rnd)
</td>
<td style="text-align:right;">
632.0372
</td>
<td style="text-align:right;">
46.70502
</td>
</tr>
<tr>
<td style="text-align:left;">
JK1
</td>
<td style="text-align:right;">
711.4530
</td>
<td style="text-align:right;">
82.84780
</td>
</tr>
<tr>
<td style="text-align:left;">
JK1+PS(stype)
</td>
<td style="text-align:right;">
624.3485
</td>
<td style="text-align:right;">
60.60973
</td>
</tr>
</tbody>
</table>
<p>Let’s take a look at the replicate weights after post-stratification</p>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="weight-adjustments.html#cb338-1" tabindex="-1"></a>api2sc.jkdes.ps<span class="sc">$</span>repweights<span class="sc">$</span>weights[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>]</span></code></pre></div>
<pre><code>##      [,1]    [,2]     [,3]     [,4]    [,5] [,6]    [,7]     [,8]
## 1 0.00000 1.00628 1.047964 1.019081 1.00000    1 1.00628 1.012640
## 3 0.00000 1.00000 1.000000 1.000000 1.04955    1 1.00000 1.067176
## 1 1.00945 0.00000 1.047964 1.019081 1.00000    1 1.00628 1.012640</code></pre>
<p>We might have been <strong>supplied</strong> replicate weights, i.e. someone else might have
created them. This is commonly the case when we have been granted access
to a data set collected by a government department.</p>
<p>In which case our dataset would look like this</p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="weight-adjustments.html#cb340-1" tabindex="-1"></a>fwmat <span class="ot">&lt;-</span> api2sc.jkdes.ps<span class="sc">$</span>repweights<span class="sc">$</span>weights[api2sc.jkdes.ps<span class="sc">$</span>repweights<span class="sc">$</span>index,]</span>
<span id="cb340-2"><a href="weight-adjustments.html#cb340-2" tabindex="-1"></a><span class="fu">colnames</span>(fwmat) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;repweight&quot;</span>,<span class="fu">sprintf</span>(<span class="st">&quot;%0.3d&quot;</span>,<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(fwmat)))</span>
<span id="cb340-3"><a href="weight-adjustments.html#cb340-3" tabindex="-1"></a>pweight <span class="ot">&lt;-</span> api2sc.jkdes.ps<span class="sc">$</span>pweights</span>
<span id="cb340-4"><a href="weight-adjustments.html#cb340-4" tabindex="-1"></a>fwmat <span class="ot">&lt;-</span> <span class="fu">diag</span>(pweight)<span class="sc">%*%</span>fwmat</span>
<span id="cb340-5"><a href="weight-adjustments.html#cb340-5" tabindex="-1"></a><span class="fu">sum</span>(pweight)</span></code></pre></div>
<pre><code>## [1] 6157</code></pre>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="weight-adjustments.html#cb342-1" tabindex="-1"></a><span class="fu">apply</span>(fwmat,<span class="dv">2</span>,sum)</span></code></pre></div>
<pre><code>## repweight001 repweight002 repweight003 repweight004 repweight005 repweight006 
##         6157         6157         6157         6157         6157         6157 
## repweight007 repweight008 repweight009 repweight010 repweight011 repweight012 
##         6157         6157         6157         6157         6157         6157 
## repweight013 repweight014 repweight015 repweight016 repweight017 repweight018 
##         6157         6157         6157         6157         6157         6157 
## repweight019 repweight020 repweight021 repweight022 repweight023 repweight024 
##         6157         6157         6157         6157         6157         6157 
## repweight025 repweight026 repweight027 repweight028 repweight029 repweight030 
##         6157         6157         6157         6157         6157         6157 
## repweight031 repweight032 repweight033 repweight034 repweight035 repweight036 
##         6157         6157         6157         6157         6157         6157 
## repweight037 repweight038 repweight039 repweight040 
##         6157         6157         6157         6157</code></pre>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="weight-adjustments.html#cb344-1" tabindex="-1"></a>api2sc.withrep.ps <span class="ot">&lt;-</span> <span class="fu">cbind</span>(api2sc, pweight, fwmat)</span></code></pre></div>
<p>We create the design using the probability weights <code>pweight</code>
and the set of replicate weights <code>repweight001-repweight040</code>.</p>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="weight-adjustments.html#cb345-1" tabindex="-1"></a>pweightcol <span class="ot">&lt;-</span> <span class="fu">match</span>(<span class="st">&quot;pweight&quot;</span>,<span class="fu">names</span>(api2sc.withrep.ps)) <span class="co"># which column name is exactly equal to pweight</span></span>
<span id="cb345-2"><a href="weight-adjustments.html#cb345-2" tabindex="-1"></a>repweightcols <span class="ot">&lt;-</span> <span class="fu">grep</span>(<span class="st">&quot;^repweight&quot;</span>,<span class="fu">names</span>(api2sc.withrep.ps)) <span class="co"># which columnnames start with repweight?</span></span>
<span id="cb345-3"><a href="weight-adjustments.html#cb345-3" tabindex="-1"></a>varcols <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(api2sc.withrep.ps))</span>
<span id="cb345-4"><a href="weight-adjustments.html#cb345-4" tabindex="-1"></a>varcols <span class="ot">&lt;-</span> varcols[<span class="sc">!</span>(varcols<span class="sc">%in%</span><span class="fu">c</span>(pweightcol,repweightcols))]</span>
<span id="cb345-5"><a href="weight-adjustments.html#cb345-5" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(api2sc<span class="sc">$</span>dnum))</span>
<span id="cb345-6"><a href="weight-adjustments.html#cb345-6" tabindex="-1"></a>api2sc.repdes.ps <span class="ot">&lt;-</span> <span class="fu">svrepdesign</span>(<span class="at">variables=</span>api2sc.withrep.ps[,varcols],</span>
<span id="cb345-7"><a href="weight-adjustments.html#cb345-7" tabindex="-1"></a>                                <span class="at">weights=</span>api2sc.withrep.ps[,pweightcol],</span>
<span id="cb345-8"><a href="weight-adjustments.html#cb345-8" tabindex="-1"></a>                                <span class="at">repweights=</span>api2sc.withrep.ps[,repweightcols],</span>
<span id="cb345-9"><a href="weight-adjustments.html#cb345-9" tabindex="-1"></a>                                <span class="at">combined.weights=</span><span class="cn">TRUE</span>,</span>
<span id="cb345-10"><a href="weight-adjustments.html#cb345-10" tabindex="-1"></a>                                <span class="at">scale=</span>(n<span class="dv">-1</span>)<span class="sc">/</span>n,</span>
<span id="cb345-11"><a href="weight-adjustments.html#cb345-11" tabindex="-1"></a>                                <span class="at">type=</span><span class="st">&quot;JK1&quot;</span>)</span>
<span id="cb345-12"><a href="weight-adjustments.html#cb345-12" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.repdes.ps)</span></code></pre></div>
<pre><code>##          mean     SE
## enroll 624.35 62.313</code></pre>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="weight-adjustments.html#cb347-1" tabindex="-1"></a>ss <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb347-2"><a href="weight-adjustments.html#cb347-2" tabindex="-1"></a>  <span class="fu">c</span>(<span class="fu">mean</span>(apipopc<span class="sc">$</span>enroll), <span class="dv">0</span>),</span>
<span id="cb347-3"><a href="weight-adjustments.html#cb347-3" tabindex="-1"></a>  <span class="fu">ff</span>(<span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.des)), </span>
<span id="cb347-4"><a href="weight-adjustments.html#cb347-4" tabindex="-1"></a>  <span class="fu">ff</span>(<span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.des.ps)), </span>
<span id="cb347-5"><a href="weight-adjustments.html#cb347-5" tabindex="-1"></a>  <span class="fu">ff</span>(<span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.des.ps2)), </span>
<span id="cb347-6"><a href="weight-adjustments.html#cb347-6" tabindex="-1"></a>  <span class="fu">ff</span>(<span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.des.rake)),</span>
<span id="cb347-7"><a href="weight-adjustments.html#cb347-7" tabindex="-1"></a>  <span class="fu">ff</span>(<span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.jkdes)),</span>
<span id="cb347-8"><a href="weight-adjustments.html#cb347-8" tabindex="-1"></a>  <span class="fu">ff</span>(<span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.jkdes.ps)),</span>
<span id="cb347-9"><a href="weight-adjustments.html#cb347-9" tabindex="-1"></a>  <span class="fu">ff</span>(<span class="fu">svymean</span>(<span class="sc">~</span>enroll, api2sc.repdes.ps))</span>
<span id="cb347-10"><a href="weight-adjustments.html#cb347-10" tabindex="-1"></a>  ) </span>
<span id="cb347-11"><a href="weight-adjustments.html#cb347-11" tabindex="-1"></a><span class="fu">dimnames</span>(ss) <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="fu">c</span>(<span class="st">&quot;Cenus&quot;</span>,<span class="st">&quot;2SC&quot;</span>,<span class="st">&quot;2SC+PS(stype)&quot;</span>,<span class="st">&quot;2SC+PS(stype x yr.rnd)&quot;</span>,<span class="st">&quot;2SC+Rake(stype+yr.rnd)&quot;</span>,</span>
<span id="cb347-12"><a href="weight-adjustments.html#cb347-12" tabindex="-1"></a>                       <span class="st">&quot;JK1&quot;</span>,<span class="st">&quot;JK1+PS(stype)&quot;</span>,<span class="st">&quot;JK1+PS(stype)&quot;</span>),</span>
<span id="cb347-13"><a href="weight-adjustments.html#cb347-13" tabindex="-1"></a>                     <span class="fu">c</span>(<span class="st">&quot;Estimate&quot;</span>,<span class="st">&quot;SE&quot;</span>))</span>
<span id="cb347-14"><a href="weight-adjustments.html#cb347-14" tabindex="-1"></a>ss</span></code></pre></div>
<pre><code>##                        Estimate       SE
## Cenus                  619.0469  0.00000
## 2SC                    711.4530 81.05714
## 2SC+PS(stype)          624.3485 53.14154
## 2SC+PS(stype x yr.rnd) 629.4503 40.23927
## 2SC+Rake(stype+yr.rnd) 632.0372 46.70502
## JK1                    711.4530 82.84780
## JK1+PS(stype)          624.3485 60.60973
## JK1+PS(stype)          624.3485 62.31259</code></pre>
<p>The method “JK1” is used for unstratified designs. For stratified
designs the jackknife is specified by “JKn”: we don’t just drop out one PSU over
the whole sample in each replicate, instead we drop out a PSU from every stratum.</p>
<p>E.g. draw a two stage cluster sample within two strata: schools which are or are
not eligible for an awards programme:</p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="weight-adjustments.html#cb349-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">999</span>)</span>
<span id="cb349-2"><a href="weight-adjustments.html#cb349-2" tabindex="-1"></a>apist2sc <span class="ot">&lt;-</span> apipopc <span class="sc">|&gt;</span></span>
<span id="cb349-3"><a href="weight-adjustments.html#cb349-3" tabindex="-1"></a>  <span class="fu">select.st2sc</span>(<span class="at">n=</span><span class="dv">40</span>, <span class="at">stratumvar=</span><span class="st">&quot;awards&quot;</span>, <span class="at">cfraction=</span><span class="fl">0.20</span>, <span class="at">clustervar=</span><span class="st">&quot;dnum&quot;</span>)</span>
<span id="cb349-4"><a href="weight-adjustments.html#cb349-4" tabindex="-1"></a>apist2sc.des <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id=</span><span class="sc">~</span>dnum<span class="sc">+</span>snum, <span class="at">strata=</span><span class="sc">~</span>awards, <span class="at">fpc=</span><span class="sc">~</span>bigN1<span class="sc">+</span>bigN2, </span>
<span id="cb349-5"><a href="weight-adjustments.html#cb349-5" tabindex="-1"></a>                          <span class="at">data=</span>apist2sc, <span class="at">nest=</span><span class="cn">TRUE</span>)</span>
<span id="cb349-6"><a href="weight-adjustments.html#cb349-6" tabindex="-1"></a>apist2sc.des.ps <span class="ot">&lt;-</span> <span class="fu">postStratify</span>(apist2sc.des, <span class="at">strata=</span><span class="sc">~</span>stype, <span class="at">population=</span>stype.benchmarks)</span></code></pre></div>
<p>Note: we need <code>nest=TRUE</code> here because districts <code>dnum</code> do not nest within strata.
I.e. it is the <strong>combination</strong> of <code>awards</code> and <code>dnum</code> that actually defines the clusters here.</p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="weight-adjustments.html#cb350-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>enroll, <span class="at">design=</span>apist2sc.des)</span></code></pre></div>
<pre><code>##          mean     SE
## enroll 497.75 64.645</code></pre>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="weight-adjustments.html#cb352-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>enroll, <span class="at">design=</span>apist2sc.des.ps)</span></code></pre></div>
<pre><code>##          mean     SE
## enroll 523.97 63.001</code></pre>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="weight-adjustments.html#cb354-1" tabindex="-1"></a>apist2sc.jkdes <span class="ot">&lt;-</span> <span class="fu">as.svrepdesign</span>(apist2sc.des, <span class="at">type=</span><span class="st">&quot;JKn&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in as.svrepdesign.default(apist2sc.des, type = &quot;JKn&quot;): Finite
## population corrections after first stage have been dropped</code></pre>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="weight-adjustments.html#cb356-1" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>enroll, <span class="at">design=</span>apist2sc.jkdes)</span></code></pre></div>
<pre><code>##          mean     SE
## enroll 497.75 84.997</code></pre>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="weight-adjustments.html#cb358-1" tabindex="-1"></a>apist2sc.jkdes.ps <span class="ot">&lt;-</span> <span class="fu">postStratify</span>(apist2sc.jkdes, <span class="at">strata=</span><span class="sc">~</span>stype, <span class="at">population=</span>stype.benchmarks)</span>
<span id="cb358-2"><a href="weight-adjustments.html#cb358-2" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>enroll, <span class="at">design=</span>apist2sc.jkdes.ps)</span></code></pre></div>
<pre><code>##          mean     SE
## enroll 523.97 82.125</code></pre>
<p>There are alternative methods to Jacknife generation of replicate weights.
You may hear of Bootstrap weights, and Balanced Repeated Replication. Some
of these have multiple variants. We don’t need to worry about these.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="survey-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="imputation.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf", "_main.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
